#!/usr/bin/env python3
"""
Build all Docker images required for enterprise-dual-site ContainerLab topology.

Run this script on the machine with KVM + Docker (lab host), BEFORE deploying the lab.

Image targets (must match topology.clab.yaml):
  ceos:4.35.2F         — Arista cEOS    (docker import from .tar)
  cisco-iol:17.12      — Cisco IOL L3/L2 (wraps .bin binary)
  vr-vsrx:18.4R3-S3    — Juniper vSRX   (vrnetlab/vr-vsrx, needs KVM)
  vr-pan:11.2.5        — PaloAlto PAN-OS (vrnetlab/vr-pan, needs KVM)
  vr-ftosv:6.4         — Fortinet FortiGate (vrnetlab/vr-ftosv, needs KVM)

Usage:
  python3 scripts/build_images.py            # build all
  python3 scripts/build_images.py --only ceos
  python3 scripts/build_images.py --only iol
  python3 scripts/build_images.py --only vsrx
  python3 scripts/build_images.py --only panos
  python3 scripts/build_images.py --only fortios
  python3 scripts/build_images.py --check   # dry-run: verify source files
"""

import argparse
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# ── Source file paths — all relative to /mnt/data/containerlab on lab host (.12) ──
# Sync lab_sessions to .12 and run this script there via: python3 scripts/remote_build.py
SRC_ROOT      = Path("/mnt/data/containerlab")
CEOS_TAR      = SRC_ROOT / "docker/cEOS-lab-4.35.2F.tar"
IOL_L3_BIN    = SRC_ROOT / "iol/bin/x86_64_crb_linux-adventerprisek9-ms.bin"
IOL_L2_BIN    = SRC_ROOT / "iol/bin/x86_64_crb_linux_l2-adventerprisek9-ms.bin"
IOL_KEYGEN    = SRC_ROOT / "iol/bin/CiscoIOUKeygen.py"
VSRX_QCOW2          = SRC_ROOT / "qemu/vsrxng-18.4R3-S3/virtioa.qcow2"
PANOS_QCOW2         = SRC_ROOT / "qemu/paloalto-11.2.5/virtioa.qcow2"
FORTIOS_QCOW2       = SRC_ROOT / "qemu/fortinet-FGT-v6-4-build1579/virtioa.qcow2"
VJUNOSEVOLVED_QCOW2 = SRC_ROOT / "qemu/vJunosEvolved-25.4R1.13/vJunosEvolved-25.4R1.13-EVO.qcow2"

# ── Target image names (must match topology.clab.yaml) ──────────────────────────
CEOS_IMAGE          = "ceos:4.35.2F"
IOL_IMAGE           = "cisco-iol:17.12"
VSRX_IMAGE          = "vr-vsrx:18.4R3-S3"
PANOS_IMAGE         = "vr-pan:11.2.5"
FORTIOS_IMAGE       = "vr-fortios:6.4"
VJUNOSEVOLVED_IMAGE = "vr-vjunosevolved:25.4R1.13-EVO"

# vrnetlab fork maintained by ContainerLab team (hellt's fork, not original)
VRNETLAB_REPO = "https://github.com/hellt/vrnetlab.git"


def run(cmd: list[str], cwd: Path | None = None) -> None:
    print(f"  $ {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, cwd=cwd)
    if result.returncode != 0:
        print(f"[ERROR] command failed (exit {result.returncode})", file=sys.stderr)
        sys.exit(result.returncode)


def check_docker() -> None:
    if subprocess.run(["docker", "info"], capture_output=True).returncode != 0:
        print("[ERROR] Docker daemon not running or no permission.", file=sys.stderr)
        sys.exit(1)


def check_kvm() -> None:
    if not Path("/dev/kvm").exists():
        print("[ERROR] /dev/kvm not found — vrnetlab images require KVM.", file=sys.stderr)
        sys.exit(1)
    print("[OK] /dev/kvm present")


def image_exists(name: str) -> bool:
    r = subprocess.run(["docker", "image", "inspect", name], capture_output=True)
    return r.returncode == 0


# ── Build: Arista cEOS (docker import from tar) ──────────────────────────────────
def build_ceos() -> None:
    print("\n=== Building ceos image (docker import) ===")
    if not CEOS_TAR.exists():
        print(f"[ERROR] cEOS tar not found: {CEOS_TAR}", file=sys.stderr)
        sys.exit(1)
    run(["docker", "import", str(CEOS_TAR), CEOS_IMAGE])
    print(f"[OK] Imported {CEOS_IMAGE}")


# ── Build: Cisco IOL ─────────────────────────────────────────────────────────
# ContainerLab cisco_iol kind expects:
#   - /usr/local/bin/iol.bin  (the IOL L3 binary)
#   - /usr/local/bin/iol_l2.bin (the IOL L2 binary)
#   - /etc/iourc  (license file generated by CiscoIOUKeygen.py)
# The base image provides the IOL runtime launcher.
# Ref: https://containerlab.dev/manual/kinds/cisco_iol/
IOL_ENTRYPOINT = """\
#!/usr/bin/env python3
\"\"\"ContainerLab cisco_iol entrypoint.

1. Generates per-container iourc (hostname-specific via CiscoIOUKeygen.py).
2. Waits for ContainerLab to create all eth interfaces (veth links take ~2s).
3. Starts iouyap in background — bridges IOL unix-socket interfaces to eth devs.
4. Launches IOS with pexpect:
   - Handles all boot dialog prompts (config dialog, autoinstall, etc.)
   - Reads management IP from eth0 and prepends Ethernet0/0 management config
   - Pushes /iol/config.txt (topology startup-config) via configure terminal
   - Saves to NVRAM with 'write memory'
   - Hands off to interactive console (docker attach <node> gives IOS CLI)
\"\"\"
import os
import re
import subprocess
import sys
import time

import pexpect


# ── Step 1: Generate per-container iourc ─────────────────────────────────────
try:
    out = subprocess.check_output(
        ["python3", "/usr/local/bin/CiscoIOUKeygen.py"],
        stderr=subprocess.STDOUT,
        text=True,
    )
except subprocess.CalledProcessError as e:
    out = e.output or ""

m = re.search(r"=\\s*([a-f0-9]+)", out)
key = m.group(1) if m else "deadbeefdeadbeef"
hostname = os.uname().nodename

with open("/root/.iourc", "w") as fh:
    fh.write(f"[license]\\n{hostname} = {key};\\n")

# Block Cisco license validation endpoint
with open("/etc/hosts", "a") as fh:
    fh.write("127.0.0.127 xml.cisco.com\\n")

# ── Step 2: Read management IP from eth0 ──────────────────────────────────────
mgmt_ip_str = None
mgmt_mask = None
try:
    ip_out = subprocess.check_output(["ip", "-4", "addr", "show", "eth0"], text=True)
    m2 = re.search(r"inet (\\d+\\.\\d+\\.\\d+\\.\\d+)/(\\d+)", ip_out)
    if m2:
        mgmt_ip_str = m2.group(1)
        prefix = int(m2.group(2))
        bits = (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF
        mgmt_mask = ".".join(str((bits >> s) & 0xFF) for s in [24, 16, 8, 0])
except Exception:
    pass

# ── Step 3: Compute IOL instance parameters ───────────────────────────────────
iol_pid = int(os.environ.get("IOL_PID", "1"))
clab_intfs = int(os.environ.get("CLAB_INTFS", "1"))
n = iol_pid + 508      # iouyap instance = IOL_PID + 508

os.chdir("/iol")       # IOL creates unix sockets relative to CWD

# ── Step 4: Wait for ContainerLab to create eth1..N (veth links take ~2s) ─────
# ContainerLab creates eth interfaces AFTER starting the container.
# iouyap needs the eth interfaces to exist before opening pcap handles.
for eth_idx in range(1, clab_intfs + 1):
    eth = f"eth{eth_idx}"
    waited = 0
    while not os.path.exists(f"/sys/class/net/{eth}") and waited < 30:
        time.sleep(0.5)
        waited += 0.5

# ── Step 5: Start iouyap ──────────────────────────────────────────────────────
# iouyap bridges IOL unix-socket interfaces to container eth interfaces via pcap.
# -f specifies the ini config file; final positional arg is the iouyap instance ID.
if os.path.exists("/usr/bin/iouyap") and os.path.exists("/iol/iouyap.ini"):
    subprocess.Popen(["/usr/bin/iouyap", "-f", "/iol/iouyap.ini", str(n)])
    time.sleep(1)

# ── Step 6: Launch IOS with pexpect ──────────────────────────────────────────
child = pexpect.spawn(
    "/usr/local/bin/iol.bin",
    args=[str(iol_pid), "-e", str(clab_intfs + 1), "-n", str(n)],
    timeout=300,
    encoding="utf-8",
    codec_errors="ignore",
)

# Wait for initial config dialog or prompt (IOS takes ~60s to boot)
idx = child.expect(
    [
        r"Would you like to enter the initial configuration dialog",
        r"Press RETURN to get started",
        r"(?i)Router[>#]",
        pexpect.TIMEOUT,
        pexpect.EOF,
    ],
    timeout=180,
)

if idx == 0:  # config dialog — answer no
    child.sendline("no")
    # Handle follow-up prompts: autoinstall, terminate autoinstall, etc.
    # IOS 17.x may ask "Would you like to terminate autoinstall? [yes]: "
    for _ in range(5):
        try:
            idx2 = child.expect(
                [
                    r"[Tt]erminate autoinstall",
                    r"[Ww]ould you like to",
                    r"\\[yes\\]:",
                    r"\\[yes/no\\]:",
                    r"Press RETURN to get started",
                    r"(?i)Router[>#]",
                ],
                timeout=90,
            )
            if idx2 == 0:    # "terminate autoinstall" → yes
                child.sendline("yes")
            elif idx2 == 1:  # another "Would you like to..." → no
                child.sendline("no")
            elif idx2 == 2:  # [yes]: prompt → yes
                child.sendline("yes")
            elif idx2 == 3:  # [yes/no]: prompt → no
                child.sendline("no")
            elif idx2 in [4, 5]:  # "Press RETURN" or at prompt
                break
        except pexpect.TIMEOUT:
            break  # give up and continue

if idx <= 1:  # press return to continue
    child.sendline("")

# Ensure we're at a CLI prompt before proceeding
child.expect(r"[>#]", timeout=90)

# ── Step 7: Push startup-config ───────────────────────────────────────────────
config_file = "/iol/config.txt"
if os.path.exists(config_file):
    with open(config_file) as fh:
        config_lines = [line.rstrip("\\r\\n") for line in fh]

    # Enter enable and configure terminal
    child.sendline("enable")
    child.expect(r"#", timeout=10)
    child.sendline("configure terminal")
    child.expect(r"\\(config\\)#", timeout=10)

    # Prepend management interface + SSH config (dynamically resolved IP)
    if mgmt_ip_str and mgmt_mask:
        mgmt_cmds = [
            "interface Ethernet0/0",
            f" ip address {mgmt_ip_str} {mgmt_mask}",
            " no shutdown",
            "exit",
            "ip domain-name clab.local",
        ]
        for cmd in mgmt_cmds:
            child.sendline(cmd)
            child.expect(r"#", timeout=10)
        # Generate RSA key (required for SSH); IOS 17.x auto-sizes
        child.sendline("crypto key generate rsa modulus 1024")
        child.expect(r"#", timeout=60)
        child.sendline("ip ssh version 2")
        child.expect(r"#", timeout=10)

    # Push config file lines (stops at 'end')
    for line in config_lines:
        if line.strip() == "end":
            break
        child.sendline(line)
        child.expect(r"#", timeout=15)

    child.sendline("end")
    child.expect(r"#", timeout=10)
    child.sendline("write memory")
    child.expect(r"(?i)(ok|\\[ok\\]|#|error)", timeout=30)

# ── Step 8: Hand off to interactive console ───────────────────────────────────
# 'docker attach <node>' will now give interactive IOS CLI access.
try:
    child.interact()
except OSError:
    child.wait()
"""

IOL_DOCKERFILE = """\
# Stage 1: compile iouyap from source (DanPartelly fork, newer gcc compatible)
FROM debian:12 AS iouyap-builder
RUN apt-get update && apt-get install -y --no-install-recommends \\
    ca-certificates gcc git make libpcap-dev pkg-config bison flex \\
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/DanPartelly/iouyap /build/iouyap
WORKDIR /build/iouyap
RUN make

# Stage 2: runtime image
FROM debian:12-slim
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libssl3 libpam-runtime libpam0g \\
    iproute2 net-tools python3 python3-pexpect \\
    libpcap0.8 \\
    && rm -rf /var/lib/apt/lists/*

COPY --from=iouyap-builder /build/iouyap/iouyap /usr/bin/iouyap
COPY iol.bin              /usr/local/bin/iol.bin
COPY iol_l2.bin           /usr/local/bin/iol_l2.bin
# CiscoIOUKeygen.py generates a per-container iourc at runtime (hostname-specific).
COPY CiscoIOUKeygen.py    /usr/local/bin/CiscoIOUKeygen.py
COPY entrypoint.py        /entrypoint.py

RUN chmod +x /usr/local/bin/iol.bin /usr/local/bin/iol_l2.bin \\
             /usr/bin/iouyap /entrypoint.py

ENTRYPOINT ["/entrypoint.py"]
"""


def build_iol() -> None:
    print("\n=== Building cisco-iol image ===")
    for f in [IOL_L3_BIN, IOL_L2_BIN, IOL_KEYGEN]:
        if not f.exists():
            print(f"[ERROR] Source file not found: {f}", file=sys.stderr)
            sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)

        shutil.copy(IOL_L3_BIN, tmpdir / "iol.bin")
        shutil.copy(IOL_L2_BIN, tmpdir / "iol_l2.bin")
        # Embed the keygen script so the entrypoint can generate
        # a correct per-container iourc at runtime (hostname-specific).
        shutil.copy(IOL_KEYGEN, tmpdir / "CiscoIOUKeygen.py")
        (tmpdir / "entrypoint.py").write_text(IOL_ENTRYPOINT)
        (tmpdir / "Dockerfile").write_text(IOL_DOCKERFILE)

        run(["docker", "build", "-t", IOL_IMAGE, "."], cwd=tmpdir)

    print(f"[OK] Built {IOL_IMAGE}")


# ── Build: PAN-OS (vrnetlab/vr-pan) ─────────────────────────────────────────
# hellt/vrnetlab pan directory builds vr-pan Docker image from PAN-OS qcow2.
# Ref: https://github.com/hellt/vrnetlab/tree/master/pan
def build_panos() -> None:
    print("\n=== Building vr-pan (PAN-OS) image ===")
    check_kvm()
    if not PANOS_QCOW2.exists():
        print(f"[ERROR] qcow2 not found: {PANOS_QCOW2}", file=sys.stderr)
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        print("  Cloning hellt/vrnetlab (pan module)...")
        run(["git", "clone", "--depth=1", VRNETLAB_REPO,
             str(tmpdir / "vrnetlab")])

        pan_dir = tmpdir / "vrnetlab" / "paloalto" / "pan"
        shutil.copy(PANOS_QCOW2, pan_dir / "PA-VM-KVM-11.2.5.qcow2")

        run(["make", "docker-image"], cwd=pan_dir)

        # vrnetlab tags as vrnetlab/vr-pan:VERSION — retag to our name
        run(["docker", "tag", "vrnetlab/vr-pan:11.2.5", PANOS_IMAGE])

    print(f"[OK] Built {PANOS_IMAGE}")


# ── Build: Juniper vSRX (vrnetlab/vr-vsrx) ──────────────────────────────────────────────
def build_vsrx() -> None:
    print("\n=== Building vr-vsrx (Juniper vSRX) image ===")
    check_kvm()
    if not VSRX_QCOW2.exists():
        print(f"[ERROR] qcow2 not found: {VSRX_QCOW2}", file=sys.stderr)
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        print("  Cloning hellt/vrnetlab (vsrx module)...")
        run(["git", "clone", "--depth=1", VRNETLAB_REPO,
             str(tmpdir / "vrnetlab")])

        vsrx_dir = tmpdir / "vrnetlab" / "juniper" / "vsrx"
        shutil.copy(VSRX_QCOW2, vsrx_dir / "junos-vsrx3-x86-64-18.4R3-S3.qcow2")
        run(["make", "docker-image"], cwd=vsrx_dir)
        run(["docker", "tag", "vrnetlab/vr-vsrx:18.4R3-S3", VSRX_IMAGE])

    print(f"[OK] Built {VSRX_IMAGE}")


def build_fortios() -> None:
    print("\n=== Building vr-ftosv (FortiGate) image ===")
    check_kvm()
    if not FORTIOS_QCOW2.exists():
        print(f"[ERROR] qcow2 not found: {FORTIOS_QCOW2}", file=sys.stderr)
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        print("  Cloning hellt/vrnetlab (fortios module)...")
        run(["git", "clone", "--depth=1", VRNETLAB_REPO,
             str(tmpdir / "vrnetlab")])

        ftosv_dir = tmpdir / "vrnetlab" / "fortinet" / "fortigate"
        shutil.copy(FORTIOS_QCOW2, ftosv_dir / "fortios-v6.4.qcow2")

        run(["make", "docker-build-fortigate"], cwd=ftosv_dir)

        # vrnetlab tags as vrnetlab/vr-fortios:6.4 — retag to our name
        run(["docker", "tag", "vrnetlab/vr-fortios:6.4", FORTIOS_IMAGE])

    print(f"[OK] Built {FORTIOS_IMAGE}")


# ── Build: Juniper vJunosEvolved (vrnetlab/vr-vjunosevolved) ─────────────────────
def build_vjunosevolved() -> None:
    print("\n=== Building vr-vjunosevolved (Juniper vJunosEvolved) image ===")
    check_kvm()
    if not VJUNOSEVOLVED_QCOW2.exists():
        print(f"[ERROR] qcow2 not found: {VJUNOSEVOLVED_QCOW2}", file=sys.stderr)
        sys.exit(1)

    with tempfile.TemporaryDirectory() as tmp:
        tmpdir = Path(tmp)
        print("  Cloning hellt/vrnetlab (vjunosevolved module)...")
        run(["git", "clone", "--depth=1", VRNETLAB_REPO, str(tmpdir / "vrnetlab")])

        vevo_dir = tmpdir / "vrnetlab" / "juniper" / "vjunosevolved"
        # vrnetlab expects filename matching IMAGE_GLOB=*.qcow2; VERSION extracted by stripping vjunosevolved- prefix
        shutil.copy(VJUNOSEVOLVED_QCOW2, vevo_dir / "vJunosEvolved-25.4R1.13-EVO.qcow2")
        run(["make", "docker-image"], cwd=vevo_dir)
        run(["docker", "tag", "vrnetlab/juniper_vjunosevolved:25.4R1.13-EVO", VJUNOSEVOLVED_IMAGE])

    print(f"[OK] Built {VJUNOSEVOLVED_IMAGE}")


def check_sources() -> None:
    """Dry-run: verify all source files are accessible without building."""
    for label, path in [
        ("cEOS tar",       CEOS_TAR),
        ("IOL L3 binary",  IOL_L3_BIN),
        ("IOL L2 binary",  IOL_L2_BIN),
        ("IOL keygen",     IOL_KEYGEN),
        ("vSRX qcow2",           VSRX_QCOW2),
        ("PAN-OS qcow2",         PANOS_QCOW2),
        ("FortiOS qcow2",        FORTIOS_QCOW2),
        ("vJunosEvolved qcow2",  VJUNOSEVOLVED_QCOW2),
    ]:
        status = "[OK]    " if path.exists() else "[MISSING]"
        print(f"  {status} {label}: {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", choices=["ceos", "iol", "vsrx", "panos", "fortios", "vjunosevolved"],
                        help="Build only this specific image")
    parser.add_argument("--check", action="store_true",
                        help="Verify source files and existing images without building")
    args = parser.parse_args()

    if args.check:
        print("=== Source file check ===")
        check_sources()
        print("\n=== Existing Docker images ===")
        for img in [CEOS_IMAGE, IOL_IMAGE, VSRX_IMAGE, PANOS_IMAGE, FORTIOS_IMAGE, VJUNOSEVOLVED_IMAGE]:
            status = "[OK]    " if image_exists(img) else "[MISSING]"
            print(f"  {status} {img}")
        return

    check_docker()

    if args.only == "ceos" or args.only is None:
        if image_exists(CEOS_IMAGE):
            print(f"[SKIP] {CEOS_IMAGE} already present (docker rmi to rebuild)")
        else:
            build_ceos()

    if args.only == "iol" or args.only is None:
        if image_exists(IOL_IMAGE):
            print(f"[SKIP] {IOL_IMAGE} already present")
        else:
            build_iol()

    if args.only == "vsrx" or args.only is None:
        if image_exists(VSRX_IMAGE):
            print(f"[SKIP] {VSRX_IMAGE} already present")
        else:
            build_vsrx()

    if args.only == "panos" or args.only is None:
        if image_exists(PANOS_IMAGE):
            print(f"[SKIP] {PANOS_IMAGE} already present")
        else:
            build_panos()

    if args.only == "fortios" or args.only is None:
        if image_exists(FORTIOS_IMAGE):
            print(f"[SKIP] {FORTIOS_IMAGE} already present")
        else:
            build_fortios()

    if args.only == "vjunosevolved" or args.only is None:
        if image_exists(VJUNOSEVOLVED_IMAGE):
            print(f"[SKIP] {VJUNOSEVOLVED_IMAGE} already present")
        else:
            build_vjunosevolved()

    print("\n=== All images built ===")
    for img in [CEOS_IMAGE, IOL_IMAGE, VSRX_IMAGE, PANOS_IMAGE, FORTIOS_IMAGE, VJUNOSEVOLVED_IMAGE]:
        status = "[OK]    " if image_exists(img) else "[MISSING]"
        print(f"  {status} {img}")
    print("\nNext: python3 scripts/manage_lab.py")


if __name__ == "__main__":
    main()
