approval_status: null
approval_timestamp: null
approved_by: null
created_at: '2026-02-08T14:06:09.674412'
cron_expression: '*/1 * * * *'
description: null
duration_hours: 0.001
execution_count: 0
expires_at: '2026-02-08T14:06:13.274412'
failure_count: 0
last_execution_at: null
last_execution_result: null
modified_at: '2026-02-08T14:23:54.788606'
name: null
notifications: {}
permission_tier: green
query: SELECT * FROM devices
rejected_by: null
rejection_reason: null
requires_approval: false
status: archived
task_id: 3e074a4f-f03
timeout_seconds: 300
