"""refresh.py — olav refresh: rebuild global agent registry (deterministic, no LLM).

Scans .olav/workspace/*/AGENT.md and:

1. Rewrites PLATFORM.md frontmatter (agents list + body table).
2. Replaces the <!-- BEGIN_AGENT_ROUTING --> ... <!-- END_AGENT_ROUTING --> section
   in .olav/workspace/olav/prompts/system.md with a fresh routing table.

Auto-triggered by:  olav init, olav skill install, olav skill remove.
Manual:             olav refresh

Rev 93 / ISSUE-P2-NO-GLOBAL-AGENT-REGISTRY
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

# Agents skipped from the main routing table (the olav main agent routes to others — not to itself)
_ROUTING_TABLE_SKIP: frozenset[str] = frozenset({"core"})

_ROUTING_START_MARKER = "<!-- BEGIN_AGENT_ROUTING -->"
_ROUTING_END_MARKER = "<!-- END_AGENT_ROUTING -->"


# ── frontmatter helpers ─────────────────────────────────────────────────────


def _parse_agent_frontmatter(agent_md: Path) -> dict[str, Any]:
    """Extract YAML frontmatter from an AGENT.md file.

    Returns an empty dict if the file is missing, has no frontmatter, or
    the YAML cannot be parsed.
    """
    try:
        text = agent_md.read_text(encoding="utf-8")
    except OSError:
        return {}
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 2:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return {}


# ── scanning ────────────────────────────────────────────────────────────────


def _scan_agents(workspace_root: Path) -> list[dict[str, Any]]:
    """Scan workspace_root/*/AGENT.md and return a sorted list of agent dicts.

    Each dict contains:
      flag        — directory name (used as --agent <flag>)
      name        — human name from AGENT.md frontmatter
      description — description from AGENT.md frontmatter
      kind        — kind field (may be empty string)
    """
    agents: list[dict[str, Any]] = []
    for agent_dir in sorted(workspace_root.iterdir()):
        if not agent_dir.is_dir():
            continue
        agent_md = agent_dir / "AGENT.md"
        if not agent_md.exists():
            continue
        meta = _parse_agent_frontmatter(agent_md)
        agents.append(
            {
                "flag": agent_dir.name,
                "name": meta.get("name", agent_dir.name),
                "description": meta.get("description", ""),
                "kind": meta.get("kind", ""),
            }
        )
    return agents


# ── PLATFORM.md ─────────────────────────────────────────────────────────────


def _write_platform_md(workspace_root: Path, agents: list[dict[str, Any]]) -> None:
    """Rewrite PLATFORM.md with the current agent list.

    Preserves the existing ``active`` and ``platform`` frontmatter keys so that
    per-environment configuration (database paths, service URLs) is not lost.
    """
    platform_md = workspace_root / "PLATFORM.md"

    existing_meta: dict[str, Any] = {}
    if platform_md.exists():
        text = platform_md.read_text(encoding="utf-8")
        if text.startswith("---"):
            parts = text.split("---", 2)
            if len(parts) >= 2:
                try:
                    existing_meta = yaml.safe_load(parts[1]) or {}
                except yaml.YAMLError:
                    existing_meta = {}

    flags = [a["flag"] for a in agents]

    new_meta: dict[str, Any] = {}
    new_meta["active"] = existing_meta.get("active", flags[0] if flags else "")
    new_meta["agents"] = flags
    if "platform" in existing_meta:
        new_meta["platform"] = existing_meta["platform"]

    # Build body — agent routing table
    table_lines = [
        "# OLAV Platform",
        "",
        "Agent registry — auto-generated by `olav refresh`.",
        "",
        "## Agents",
        "",
        "| Flag | Name | Description |",
        "|------|------|-------------|",
    ]
    for a in agents:
        desc = a["description"]
        if len(desc) > 80:
            desc = desc[:79] + "…"
        table_lines.append(f"| `{a['flag']}` | {a['name']} | {desc} |")
    table_lines += [
        "",
        "## Usage",
        "",
        "```bash",
        "olav --agent <flag> \"<task>\"",
        "```",
        "",
        "Run `olav refresh` after installing or removing agents.",
        "",
        "## Reflection Rules（运行时自纠正）",
        "",
        "### R1: Tool 错误自动重试",
        "当工具返回错误时，**分析错误信息并重试**，不要直接报错给用户。",
        "",
        "- execute_sql 返回 \"column not found, candidates: X\" → 用 candidate 列名重写 SQL",
        "- execute_cli 返回 \"command not recognized\" → 检查平台（Juniper vs Cisco）后重试",
        "- api_request 返回 404 → 检查 path 拼写或 `load_reference` 确认 API schema",
        "- format_and_export 返回 \"directory not found\" → 创建目录后重试",
        "",
        "最多重试 **2 次**。2 次仍失败 → 报告错误 + 你尝试过什么 + 建议用户怎么做。",
        "",
        "### R2: 结果验证",
        "执行工具后，**验证结果是否合理**：",
        "",
        "- execute_sql 返回 0 行 → 可能 WHERE 条件过严，放宽后重试",
        "- execute_sql 返回 > 1000 行 → 可能缺少 LIMIT，加 LIMIT 重查",
        "- take_snapshot 返回 \"0 parsed_rows\" → TextFSM 模板可能不匹配，告知用户",
        "",
        "### R3: 多步骤任务中间检查",
        "在多步骤任务中，每完成一步 **检查输出再继续**：",
        "",
        "- 查数据 → 检查数据够不够 → 不够？补查 → 够了 → 继续分析",
        "- 生成报告 → 检查有没有遗漏章节 → 有？补写 → 完整了 → 导出",
        "",
        "### R4: HITL 确认门",
        "以下操作在执行前 **必须向用户确认**（格式：\"我计划执行 [操作]，原因是 [原因]。确认？[y/N]\"）：",
        "",
        "- 修改 workspace 文件（SKILL.md、system.md、tools/）",
        "- 删除任何文件",
        "- 执行 deploy_service / stop_service",
        "- API 写操作（已有 --enable-api-write 机制）",
    ]

    body = "\n".join(table_lines)
    new_text = "---\n" + yaml.dump(new_meta, default_flow_style=False) + "---\n\n" + body + "\n"
    platform_md.write_text(new_text, encoding="utf-8")
    logger.info("PLATFORM.md rewritten: %d agents → %s", len(agents), flags)


# ── system.md routing table ─────────────────────────────────────────────────


def _update_main_agent_routing(workspace_root: Path, agents: list[dict[str, Any]]) -> bool:
    """Replace the routing section in olav/prompts/system.md.

    The section is delimited by ``<!-- BEGIN_AGENT_ROUTING -->`` and
    ``<!-- END_AGENT_ROUTING -->`` markers.  Agents in ``_ROUTING_TABLE_SKIP``
    are omitted (the main agent does not route to itself).

    Returns:
        True  — markers found and section updated.
        False — system.md missing or markers absent (no change made).
    """
    system_md = workspace_root / "core" / "prompts" / "system.md"
    if not system_md.exists():
        logger.warning("Main agent system.md not found: %s", system_md)
        return False

    text = system_md.read_text(encoding="utf-8")
    if _ROUTING_START_MARKER not in text or _ROUTING_END_MARKER not in text:
        logger.warning("Routing markers not found in %s — skipping routing update", system_md)
        return False

    routing_agents = [a for a in agents if a["flag"] not in _ROUTING_TABLE_SKIP]

    lines = [_ROUTING_START_MARKER]
    for a in routing_agents:
        desc = a["description"]
        # Use text after em-dash if present, else full description
        short = desc.split("—", 1)[1].strip() if "—" in desc else desc
        # First sentence only
        short = short.split(".")[0].strip()
        if len(short) > 70:
            short = short[:69].rsplit(" ", 1)[0] + "…"
        lines.append(f"  - `{a['flag']}` — {short}")
    lines.append(_ROUTING_END_MARKER)

    new_section = "\n".join(lines)

    start_idx = text.index(_ROUTING_START_MARKER)
    end_idx = text.index(_ROUTING_END_MARKER) + len(_ROUTING_END_MARKER)
    new_text = text[:start_idx] + new_section + text[end_idx:]
    system_md.write_text(new_text, encoding="utf-8")
    logger.info("system.md routing table updated: %d agents", len(routing_agents))
    return True


# ── public API ───────────────────────────────────────────────────────────────


def refresh_workspace(workspace_root: Path | None = None) -> str:
    """Scan workspace and rebuild PLATFORM.md + main agent routing.

    This is a deterministic operation (no LLM calls).  Safe to call repeatedly
    — subsequent runs produce identical output for the same workspace state.

    Args:
        workspace_root: Path to the workspace directory.  Defaults to
            ``.olav/workspace`` relative to the current working directory.

    Returns:
        A human-readable summary string (starts with ``✓`` on success,
        ``warning:`` for non-fatal issues, ``error:`` for fatal errors).
    """
    if workspace_root is None:
        workspace_root = Path(".olav") / "workspace"

    if not workspace_root.exists():
        return f"error: workspace not found: {workspace_root}"

    agents = _scan_agents(workspace_root)
    if not agents:
        return "warning: no AGENT.md files found in workspace"

    _write_platform_md(workspace_root, agents)
    routing_updated = _update_main_agent_routing(workspace_root, agents)

    # Build semantic routing index (non-fatal if LanceDB/embeddings unavailable)
    try:
        from olav.core.router import initialize_router
        initialize_router()
    except Exception as exc:
        logger.debug("initialize_router skipped: %s", exc)

    flags = [a["flag"] for a in agents]
    note = "" if routing_updated else " (routing markers not found in olav/prompts/system.md)"
    return f"✓ {len(agents)} agents registered: {', '.join(flags)}{note}"


# ── CLI command class ─────────────────────────────────────────────────────────


class RefreshCommand:
    """``olav refresh`` — rebuild global agent registry (deterministic, no LLM)."""

    name = "refresh"
    description = "Rebuild global agent registry (PLATFORM.md + routing table)"

    async def execute(self, args: str = "") -> str:  # noqa: ARG002
        return refresh_workspace()
