"""Auto-generated tool: Gitea — Gitea repository endpoints: CRUD operations, branches, contents, releases, hooks, collaborators, forks, etc.

Generated by olav.platform.services.tool_generator
Service: gitea
Tag group: repository
DO NOT EDIT MANUALLY — re-run `olav service register gitea` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def gitea_repository_post_repos_migrate(body: dict | None = None, confirmed: bool = False) -> dict:
    """Migrate a remote git repository

    Service: gitea  |  POST /repos/migrate
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/migrate",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_search(params: dict | None = None) -> dict:
    """Search for repositories

    Service: gitea  |  GET /repos/search
    Query params: q(), topic(), includeDesc(), uid(), priority_owner_id(), team_id(), starredBy(), private(), is_private(), template(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/search",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo(owner, repo, confirmed: bool = False) -> dict:
    """Delete a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo(owner, repo, params: dict | None = None) -> dict:
    """Get a repository

    Service: gitea  |  GET /repos/{owner}/{repo}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Edit a repository's properties. Only fields that are set will be changed.

    Service: gitea  |  PATCH /repos/{owner}/{repo}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_artifacts(owner, repo, params: dict | None = None) -> dict:
    """Lists all artifacts for a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/artifacts
    Query params: name(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/artifacts",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_actions_artifacts_by_artifact_id(owner, repo, artifact_id, confirmed: bool = False) -> dict:
    """Deletes a specific artifact for a workflow run

    Service: gitea  |  DELETE /repos/{owner}/{repo}/actions/artifacts/{artifact_id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/actions/artifacts/{artifact_id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_artifacts_by_artifact_id(owner, repo, artifact_id, params: dict | None = None) -> dict:
    """Gets a specific artifact for a workflow run

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/artifacts/{artifact_id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/artifacts/{artifact_id}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_artifacts_by_artifact_id_zip(owner, repo, artifact_id, params: dict | None = None) -> dict:
    """Downloads a specific artifact for a workflow run redirects to blob url

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/artifacts/{artifact_id}/zip
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/artifacts/{artifact_id}/zip",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_jobs(owner, repo, params: dict | None = None) -> dict:
    """Lists all jobs for a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/jobs
    Query params: status(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/jobs",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_jobs_by_job_id(owner, repo, job_id, params: dict | None = None) -> dict:
    """Gets a specific workflow job for a workflow run

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/jobs/{job_id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/jobs/{job_id}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_jobs_by_job_id_logs(owner, repo, job_id, params: dict | None = None) -> dict:
    """Downloads the job logs for a workflow run

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/jobs/{job_id}/logs
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/jobs/{job_id}/logs",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_runners(owner, repo, params: dict | None = None) -> dict:
    """Get repo-level runners

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/runners
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/runners",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_runners_registration_token(owner, repo, params: dict | None = None) -> dict:
    """Get a repository's actions runner registration token

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/runners/registration-token
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/runners/registration-token",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_actions_runners_registration_token(owner, repo, confirmed: bool = False) -> dict:
    """Get a repository's actions runner registration token

    Service: gitea  |  POST /repos/{owner}/{repo}/actions/runners/registration-token
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/actions/runners/registration-token",
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_actions_runners_by_runner_id(owner, repo, runner_id, confirmed: bool = False) -> dict:
    """Delete an repo-level runner

    Service: gitea  |  DELETE /repos/{owner}/{repo}/actions/runners/{runner_id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/actions/runners/{runner_id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_runners_by_runner_id(owner, repo, runner_id, params: dict | None = None) -> dict:
    """Get an repo-level runner

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/runners/{runner_id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/runners/{runner_id}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_runs(owner, repo, params: dict | None = None) -> dict:
    """Lists all runs for a repository run

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/runs
    Query params: event(), branch(), status(), actor(), head_sha(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/runs",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_actions_runs_by_run(owner, repo, run, confirmed: bool = False) -> dict:
    """Delete a workflow run

    Service: gitea  |  DELETE /repos/{owner}/{repo}/actions/runs/{run}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/actions/runs/{run}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_runs_by_run(owner, repo, run, params: dict | None = None) -> dict:
    """Gets a specific workflow run

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/runs/{run}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/runs/{run}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_runs_by_run_artifacts(owner, repo, run, params: dict | None = None) -> dict:
    """Lists all artifacts for a repository run

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/runs/{run}/artifacts
    Query params: name(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/runs/{run}/artifacts",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_runs_by_run_jobs(owner, repo, run, params: dict | None = None) -> dict:
    """Lists all jobs for a workflow run

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/runs/{run}/jobs
    Query params: status(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/runs/{run}/jobs",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_secrets(owner, repo, params: dict | None = None) -> dict:
    """List an repo's actions secrets

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/secrets
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/secrets",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_actions_secrets_by_secretname(owner, repo, secretname, confirmed: bool = False) -> dict:
    """Delete a secret in a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/actions/secrets/{secretname}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/actions/secrets/{secretname}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_actions_secrets_by_secretname(owner, repo, secretname, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create or Update a secret value in a repository

    Service: gitea  |  PUT /repos/{owner}/{repo}/actions/secrets/{secretname}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/actions/secrets/{secretname}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_tasks(owner, repo, params: dict | None = None) -> dict:
    """List a repository's action tasks

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/tasks
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/tasks",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_variables(owner, repo, params: dict | None = None) -> dict:
    """Get repo-level variables list

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/variables
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/variables",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_actions_variables_by_variablename(owner, repo, variablename, confirmed: bool = False) -> dict:
    """Delete a repo-level variable

    Service: gitea  |  DELETE /repos/{owner}/{repo}/actions/variables/{variablename}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/actions/variables/{variablename}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_variables_by_variablename(owner, repo, variablename, params: dict | None = None) -> dict:
    """Get a repo-level variable

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/variables/{variablename}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/variables/{variablename}",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_actions_variables_by_variablename(owner, repo, variablename, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a repo-level variable

    Service: gitea  |  POST /repos/{owner}/{repo}/actions/variables/{variablename}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/actions/variables/{variablename}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_actions_variables_by_variablename(owner, repo, variablename, body: dict | None = None, confirmed: bool = False) -> dict:
    """Update a repo-level variable

    Service: gitea  |  PUT /repos/{owner}/{repo}/actions/variables/{variablename}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/actions/variables/{variablename}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_workflows(owner, repo, params: dict | None = None) -> dict:
    """List repository workflows

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/workflows
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/workflows",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_actions_workflows_by_workflow_id(owner, repo, workflow_id, params: dict | None = None) -> dict:
    """Get a workflow

    Service: gitea  |  GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/actions/workflows/{workflow_id}",
        params=params,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_actions_workflows_by_workflow_id_disable(owner, repo, workflow_id, confirmed: bool = False) -> dict:
    """Disable a workflow

    Service: gitea  |  PUT /repos/{owner}/{repo}/actions/workflows/{workflow_id}/disable
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/actions/workflows/{workflow_id}/disable",
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_actions_workflows_by_workflow_id_dispatches(owner, repo, workflow_id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a workflow dispatch event

    Service: gitea  |  POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_actions_workflows_by_workflow_id_enable(owner, repo, workflow_id, confirmed: bool = False) -> dict:
    """Enable a workflow

    Service: gitea  |  PUT /repos/{owner}/{repo}/actions/workflows/{workflow_id}/enable
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/actions/workflows/{workflow_id}/enable",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_activities_feeds(owner, repo, params: dict | None = None) -> dict:
    """List a repository's activity feeds

    Service: gitea  |  GET /repos/{owner}/{repo}/activities/feeds
    Query params: date(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/activities/feeds",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_archive_by_archive(owner, repo, archive, params: dict | None = None) -> dict:
    """Get an archive of a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/archive/{archive}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/archive/{archive}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_assignees(owner, repo, params: dict | None = None) -> dict:
    """Return all users that have write access and can be assigned to issues

    Service: gitea  |  GET /repos/{owner}/{repo}/assignees
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/assignees",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_avatar(owner, repo, confirmed: bool = False) -> dict:
    """Delete avatar

    Service: gitea  |  DELETE /repos/{owner}/{repo}/avatar
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/avatar",
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_avatar(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Update avatar

    Service: gitea  |  POST /repos/{owner}/{repo}/avatar
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/avatar",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_branch_protections(owner, repo, params: dict | None = None) -> dict:
    """List branch protections for a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/branch_protections
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/branch_protections",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_branch_protections(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a branch protections for a repository

    Service: gitea  |  POST /repos/{owner}/{repo}/branch_protections
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/branch_protections",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_branch_protections_priority(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Update the priorities of branch protections for a repository.

    Service: gitea  |  POST /repos/{owner}/{repo}/branch_protections/priority
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/branch_protections/priority",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_branch_protections_by_name(owner, repo, name, confirmed: bool = False) -> dict:
    """Delete a specific branch protection for the repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/branch_protections/{name}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/branch_protections/{name}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_branch_protections_by_name(owner, repo, name, params: dict | None = None) -> dict:
    """Get a specific branch protection for the repository

    Service: gitea  |  GET /repos/{owner}/{repo}/branch_protections/{name}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/branch_protections/{name}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_branch_protections_by_name(owner, repo, name, body: dict | None = None, confirmed: bool = False) -> dict:
    """Edit a branch protections for a repository. Only fields that are set will be changed

    Service: gitea  |  PATCH /repos/{owner}/{repo}/branch_protections/{name}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/branch_protections/{name}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_branches(owner, repo, params: dict | None = None) -> dict:
    """List a repository's branches

    Service: gitea  |  GET /repos/{owner}/{repo}/branches
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/branches",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_branches(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a branch

    Service: gitea  |  POST /repos/{owner}/{repo}/branches
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/branches",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_branches_by_branch(owner, repo, branch, confirmed: bool = False) -> dict:
    """Delete a specific branch from a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/branches/{branch}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/branches/{branch}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_branches_by_branch(owner, repo, branch, params: dict | None = None) -> dict:
    """Retrieve a specific branch from a repository, including its effective branch protection

    Service: gitea  |  GET /repos/{owner}/{repo}/branches/{branch}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/branches/{branch}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_branches_by_branch(owner, repo, branch, body: dict | None = None, confirmed: bool = False) -> dict:
    """Rename a branch

    Service: gitea  |  PATCH /repos/{owner}/{repo}/branches/{branch}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/branches/{branch}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_collaborators(owner, repo, params: dict | None = None) -> dict:
    """List a repository's collaborators

    Service: gitea  |  GET /repos/{owner}/{repo}/collaborators
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/collaborators",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_collaborators_by_collaborator(owner, repo, collaborator, confirmed: bool = False) -> dict:
    """Delete a collaborator from a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/collaborators/{collaborator}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/collaborators/{collaborator}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_collaborators_by_collaborator(owner, repo, collaborator, params: dict | None = None) -> dict:
    """Check if a user is a collaborator of a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/collaborators/{collaborator}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/collaborators/{collaborator}",
        params=params,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_collaborators_by_collaborator(owner, repo, collaborator, body: dict | None = None, confirmed: bool = False) -> dict:
    """Add or Update a collaborator to a repository

    Service: gitea  |  PUT /repos/{owner}/{repo}/collaborators/{collaborator}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/collaborators/{collaborator}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_collaborators_by_collaborator_permission(owner, repo, collaborator, params: dict | None = None) -> dict:
    """Get repository permissions for a user

    Service: gitea  |  GET /repos/{owner}/{repo}/collaborators/{collaborator}/permission
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/collaborators/{collaborator}/permission",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_commits(owner, repo, params: dict | None = None) -> dict:
    """Get a list of all commits from a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/commits
    Query params: sha(), path(), since(), until(), stat(), verification(), files(), page(), limit(), not(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/commits",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_commits_by_ref_status(owner, repo, ref, params: dict | None = None) -> dict:
    """Get a commit's combined status, by branch/tag/commit reference

    Service: gitea  |  GET /repos/{owner}/{repo}/commits/{ref}/status
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/commits/{ref}/status",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_commits_by_ref_statuses(owner, repo, ref, params: dict | None = None) -> dict:
    """Get a commit's statuses, by branch/tag/commit reference

    Service: gitea  |  GET /repos/{owner}/{repo}/commits/{ref}/statuses
    Query params: sort(), state(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/commits/{ref}/statuses",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_commits_by_sha_pull(owner, repo, sha, params: dict | None = None) -> dict:
    """Get the merged pull request of the commit

    Service: gitea  |  GET /repos/{owner}/{repo}/commits/{sha}/pull
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/commits/{sha}/pull",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_compare_by_basehead(owner, repo, basehead, params: dict | None = None) -> dict:
    """Get commit comparison information

    Service: gitea  |  GET /repos/{owner}/{repo}/compare/{basehead}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/compare/{basehead}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_contents(owner, repo, params: dict | None = None) -> dict:
    """Gets the metadata of all the entries of the root dir.

    Service: gitea  |  GET /repos/{owner}/{repo}/contents
    Query params: ref(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/contents",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_contents(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Modify multiple files in a repository

    Service: gitea  |  POST /repos/{owner}/{repo}/contents
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/contents",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_contents_ext_by_filepath(owner, repo, filepath, params: dict | None = None) -> dict:
    """The extended "contents" API, to get file metadata and/or content, or list a directory.

    Service: gitea  |  GET /repos/{owner}/{repo}/contents-ext/{filepath}
    Query params: ref(), includes(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/contents-ext/{filepath}",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_contents_by_filepath(owner, repo, filepath, confirmed: bool = False) -> dict:
    """Delete a file in a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/contents/{filepath}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/contents/{filepath}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_contents_by_filepath(owner, repo, filepath, params: dict | None = None) -> dict:
    """Gets the metadata and contents (if a file) of an entry in a repository, or a list of entries if a dir.

    Service: gitea  |  GET /repos/{owner}/{repo}/contents/{filepath}
    Query params: ref(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/contents/{filepath}",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_contents_by_filepath(owner, repo, filepath, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a file in a repository

    Service: gitea  |  POST /repos/{owner}/{repo}/contents/{filepath}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/contents/{filepath}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_contents_by_filepath(owner, repo, filepath, body: dict | None = None, confirmed: bool = False) -> dict:
    """Update a file in a repository

    Service: gitea  |  PUT /repos/{owner}/{repo}/contents/{filepath}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/contents/{filepath}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_diffpatch(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Apply diff patch to repository

    Service: gitea  |  POST /repos/{owner}/{repo}/diffpatch
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/diffpatch",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_editorconfig_by_filepath(owner, repo, filepath, params: dict | None = None) -> dict:
    """Get the EditorConfig definitions of a file in a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/editorconfig/{filepath}
    Query params: ref(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/editorconfig/{filepath}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_file_contents(owner, repo, params: dict | None = None) -> dict:
    """Get the metadata and contents of requested files

    Service: gitea  |  GET /repos/{owner}/{repo}/file-contents
    Query params: ref(), body(*). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/file-contents",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_file_contents(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Get the metadata and contents of requested files

    Service: gitea  |  POST /repos/{owner}/{repo}/file-contents
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/file-contents",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_forks(owner, repo, params: dict | None = None) -> dict:
    """List a repository's forks

    Service: gitea  |  GET /repos/{owner}/{repo}/forks
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/forks",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_forks(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Fork a repository

    Service: gitea  |  POST /repos/{owner}/{repo}/forks
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/forks",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_blobs_by_sha(owner, repo, sha, params: dict | None = None) -> dict:
    """Gets the blob of a repository.

    Service: gitea  |  GET /repos/{owner}/{repo}/git/blobs/{sha}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/blobs/{sha}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_commits_by_sha(owner, repo, sha, params: dict | None = None) -> dict:
    """Get a single commit from a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/git/commits/{sha}
    Query params: stat(), verification(), files(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/commits/{sha}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_commits_by_sha_by_difftype(owner, repo, sha, diffType, params: dict | None = None) -> dict:
    """Get a commit's diff or patch

    Service: gitea  |  GET /repos/{owner}/{repo}/git/commits/{sha}.{diffType}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/commits/{sha}.{diffType}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_notes_by_sha(owner, repo, sha, params: dict | None = None) -> dict:
    """Get a note corresponding to a single commit from a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/git/notes/{sha}
    Query params: verification(), files(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/notes/{sha}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_refs(owner, repo, params: dict | None = None) -> dict:
    """Get specified ref or filtered repository's refs

    Service: gitea  |  GET /repos/{owner}/{repo}/git/refs
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/refs",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_refs_by_ref(owner, repo, ref, params: dict | None = None) -> dict:
    """Get specified ref or filtered repository's refs

    Service: gitea  |  GET /repos/{owner}/{repo}/git/refs/{ref}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/refs/{ref}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_tags_by_sha(owner, repo, sha, params: dict | None = None) -> dict:
    """Gets the tag object of an annotated tag (not lightweight tags)

    Service: gitea  |  GET /repos/{owner}/{repo}/git/tags/{sha}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/tags/{sha}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_git_trees_by_sha(owner, repo, sha, params: dict | None = None) -> dict:
    """Gets the tree of a repository.

    Service: gitea  |  GET /repos/{owner}/{repo}/git/trees/{sha}
    Query params: recursive(), page(), per_page(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/git/trees/{sha}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_hooks(owner, repo, params: dict | None = None) -> dict:
    """List the hooks in a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/hooks
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/hooks",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_hooks(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a hook

    Service: gitea  |  POST /repos/{owner}/{repo}/hooks
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/hooks",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_hooks_git(owner, repo, params: dict | None = None) -> dict:
    """List the Git hooks in a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/hooks/git
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/hooks/git",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_hooks_git_by_id(owner, repo, id, confirmed: bool = False) -> dict:
    """Delete a Git hook in a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/hooks/git/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/hooks/git/{id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_hooks_git_by_id(owner, repo, id, params: dict | None = None) -> dict:
    """Get a Git hook

    Service: gitea  |  GET /repos/{owner}/{repo}/hooks/git/{id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/hooks/git/{id}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_hooks_git_by_id(owner, repo, id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Edit a Git hook in a repository

    Service: gitea  |  PATCH /repos/{owner}/{repo}/hooks/git/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/hooks/git/{id}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_hooks_by_id(owner, repo, id, confirmed: bool = False) -> dict:
    """Delete a hook in a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/hooks/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/hooks/{id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_hooks_by_id(owner, repo, id, params: dict | None = None) -> dict:
    """Get a hook

    Service: gitea  |  GET /repos/{owner}/{repo}/hooks/{id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/hooks/{id}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_hooks_by_id(owner, repo, id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Edit a hook in a repository

    Service: gitea  |  PATCH /repos/{owner}/{repo}/hooks/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/hooks/{id}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_hooks_by_id_tests(owner, repo, id, confirmed: bool = False) -> dict:
    """Test a push webhook

    Service: gitea  |  POST /repos/{owner}/{repo}/hooks/{id}/tests
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/hooks/{id}/tests",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_issue_config(owner, repo, params: dict | None = None) -> dict:
    """Returns the issue config for a repo

    Service: gitea  |  GET /repos/{owner}/{repo}/issue_config
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/issue_config",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_issue_config_validate(owner, repo, params: dict | None = None) -> dict:
    """Returns the validation information for a issue config

    Service: gitea  |  GET /repos/{owner}/{repo}/issue_config/validate
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/issue_config/validate",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_issue_templates(owner, repo, params: dict | None = None) -> dict:
    """Get available issue templates for a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/issue_templates
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/issue_templates",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_issues_pinned(owner, repo, params: dict | None = None) -> dict:
    """List a repo's pinned issues

    Service: gitea  |  GET /repos/{owner}/{repo}/issues/pinned
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/issues/pinned",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_keys(owner, repo, params: dict | None = None) -> dict:
    """List a repository's keys

    Service: gitea  |  GET /repos/{owner}/{repo}/keys
    Query params: key_id(), fingerprint(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/keys",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_keys(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Add a key to a repository

    Service: gitea  |  POST /repos/{owner}/{repo}/keys
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/keys",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_keys_by_id(owner, repo, id, confirmed: bool = False) -> dict:
    """Delete a key from a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/keys/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/keys/{id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_keys_by_id(owner, repo, id, params: dict | None = None) -> dict:
    """Get a repository's key by id

    Service: gitea  |  GET /repos/{owner}/{repo}/keys/{id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/keys/{id}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_languages(owner, repo, params: dict | None = None) -> dict:
    """Get languages and number of bytes of code written

    Service: gitea  |  GET /repos/{owner}/{repo}/languages
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/languages",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_licenses(owner, repo, params: dict | None = None) -> dict:
    """Get repo licenses

    Service: gitea  |  GET /repos/{owner}/{repo}/licenses
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/licenses",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_media_by_filepath(owner, repo, filepath, params: dict | None = None) -> dict:
    """Get a file or it's LFS object from a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/media/{filepath}
    Query params: ref(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/media/{filepath}",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_merge_upstream(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Merge a branch from upstream

    Service: gitea  |  POST /repos/{owner}/{repo}/merge-upstream
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/merge-upstream",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_mirror_sync(owner, repo, confirmed: bool = False) -> dict:
    """Sync a mirrored repository

    Service: gitea  |  POST /repos/{owner}/{repo}/mirror-sync
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/mirror-sync",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_new_pin_allowed(owner, repo, params: dict | None = None) -> dict:
    """Returns if new Issue Pins are allowed

    Service: gitea  |  GET /repos/{owner}/{repo}/new_pin_allowed
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/new_pin_allowed",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls(owner, repo, params: dict | None = None) -> dict:
    """List a repo's pull requests

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls
    Query params: base_branch(), state(), sort(), milestone(), labels(), poster(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a pull request

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_pinned(owner, repo, params: dict | None = None) -> dict:
    """List a repo's pinned pull requests

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/pinned
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/pinned",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_base_by_head(owner, repo, base, head, params: dict | None = None) -> dict:
    """Get a pull request by base and head

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{base}/{head}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{base}/{head}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index(owner, repo, index, params: dict | None = None) -> dict:
    """Get a pull request

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_pulls_by_index(owner, repo, index, body: dict | None = None, confirmed: bool = False) -> dict:
    """Update a pull request. If using deadline only the date will be taken into account, and time of day ignored.

    Service: gitea  |  PATCH /repos/{owner}/{repo}/pulls/{index}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/pulls/{index}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index_by_difftype(owner, repo, index, diffType, params: dict | None = None) -> dict:
    """Get a pull request diff or patch

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}.{diffType}
    Query params: binary(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}.{diffType}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index_commits(owner, repo, index, params: dict | None = None) -> dict:
    """Get commits for a pull request

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}/commits
    Query params: page(), limit(), verification(), files(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}/commits",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index_files(owner, repo, index, params: dict | None = None) -> dict:
    """Get changed files for a pull request

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}/files
    Query params: skip-to(), whitespace(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}/files",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_pulls_by_index_merge(owner, repo, index, confirmed: bool = False) -> dict:
    """Cancel the scheduled auto merge for the given pull request

    Service: gitea  |  DELETE /repos/{owner}/{repo}/pulls/{index}/merge
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/pulls/{index}/merge",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index_merge(owner, repo, index, params: dict | None = None) -> dict:
    """Check if a pull request has been merged

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}/merge
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}/merge",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls_by_index_merge(owner, repo, index, body: dict | None = None, confirmed: bool = False) -> dict:
    """Merge a pull request

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls/{index}/merge
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls/{index}/merge",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_pulls_by_index_requested_reviewers(owner, repo, index, confirmed: bool = False) -> dict:
    """cancel review requests for a pull request

    Service: gitea  |  DELETE /repos/{owner}/{repo}/pulls/{index}/requested_reviewers
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/pulls/{index}/requested_reviewers",
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls_by_index_requested_reviewers(owner, repo, index, body: dict | None = None, confirmed: bool = False) -> dict:
    """create review requests for a pull request

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls/{index}/requested_reviewers
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls/{index}/requested_reviewers",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index_reviews(owner, repo, index, params: dict | None = None) -> dict:
    """List all reviews for a pull request

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}/reviews
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls_by_index_reviews(owner, repo, index, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a review to an pull request

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls/{index}/reviews
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_pulls_by_index_reviews_by_id(owner, repo, index, id, confirmed: bool = False) -> dict:
    """Delete a specific review from a pull request

    Service: gitea  |  DELETE /repos/{owner}/{repo}/pulls/{index}/reviews/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews/{id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index_reviews_by_id(owner, repo, index, id, params: dict | None = None) -> dict:
    """Get a specific review for a pull request

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}/reviews/{id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews/{id}",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls_by_index_reviews_by_id(owner, repo, index, id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Submit a pending review to an pull request

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls/{index}/reviews/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews/{id}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_pulls_by_index_reviews_by_id_comments(owner, repo, index, id, params: dict | None = None) -> dict:
    """Get a specific review for a pull request

    Service: gitea  |  GET /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/comments",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls_by_index_reviews_by_id_dismissals(owner, repo, index, id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Dismiss a review for a pull request

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/dismissals
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/dismissals",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls_by_index_reviews_by_id_undismissals(owner, repo, index, id, confirmed: bool = False) -> dict:
    """Cancel to dismiss a review for a pull request

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls/{index}/reviews/{id}/undismissals
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls/{index}/reviews/{id}/undismissals",
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_pulls_by_index_update(owner, repo, index, confirmed: bool = False) -> dict:
    """Merge PR's baseBranch into headBranch

    Service: gitea  |  POST /repos/{owner}/{repo}/pulls/{index}/update
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/pulls/{index}/update",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_push_mirrors(owner, repo, params: dict | None = None) -> dict:
    """Get all push mirrors of the repository

    Service: gitea  |  GET /repos/{owner}/{repo}/push_mirrors
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/push_mirrors",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_push_mirrors(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """add a push mirror to the repository

    Service: gitea  |  POST /repos/{owner}/{repo}/push_mirrors
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/push_mirrors",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_push_mirrors_sync(owner, repo, confirmed: bool = False) -> dict:
    """Sync all push mirrored repository

    Service: gitea  |  POST /repos/{owner}/{repo}/push_mirrors-sync
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/push_mirrors-sync",
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_push_mirrors_by_name(owner, repo, name, confirmed: bool = False) -> dict:
    """deletes a push mirror from a repository by remoteName

    Service: gitea  |  DELETE /repos/{owner}/{repo}/push_mirrors/{name}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/push_mirrors/{name}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_push_mirrors_by_name(owner, repo, name, params: dict | None = None) -> dict:
    """Get push mirror of the repository by remoteName

    Service: gitea  |  GET /repos/{owner}/{repo}/push_mirrors/{name}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/push_mirrors/{name}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_raw_by_filepath(owner, repo, filepath, params: dict | None = None) -> dict:
    """Get a file from a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/raw/{filepath}
    Query params: ref(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/raw/{filepath}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_releases(owner, repo, params: dict | None = None) -> dict:
    """List a repo's releases

    Service: gitea  |  GET /repos/{owner}/{repo}/releases
    Query params: draft(), pre-release(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/releases",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_releases(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a release

    Service: gitea  |  POST /repos/{owner}/{repo}/releases
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/releases",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_releases_latest(owner, repo, params: dict | None = None) -> dict:
    """Gets the most recent non-prerelease, non-draft release of a repository, sorted by created_at

    Service: gitea  |  GET /repos/{owner}/{repo}/releases/latest
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/releases/latest",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_releases_tags_by_tag(owner, repo, tag, confirmed: bool = False) -> dict:
    """Delete a release by tag name

    Service: gitea  |  DELETE /repos/{owner}/{repo}/releases/tags/{tag}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/releases/tags/{tag}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_releases_tags_by_tag(owner, repo, tag, params: dict | None = None) -> dict:
    """Get a release by tag name

    Service: gitea  |  GET /repos/{owner}/{repo}/releases/tags/{tag}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/releases/tags/{tag}",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_releases_by_id(owner, repo, id, confirmed: bool = False) -> dict:
    """Delete a release

    Service: gitea  |  DELETE /repos/{owner}/{repo}/releases/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/releases/{id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_releases_by_id(owner, repo, id, params: dict | None = None) -> dict:
    """Get a release

    Service: gitea  |  GET /repos/{owner}/{repo}/releases/{id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/releases/{id}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_releases_by_id(owner, repo, id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Update a release

    Service: gitea  |  PATCH /repos/{owner}/{repo}/releases/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/releases/{id}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_releases_by_id_assets(owner, repo, id, params: dict | None = None) -> dict:
    """List release's attachments

    Service: gitea  |  GET /repos/{owner}/{repo}/releases/{id}/assets
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/releases/{id}/assets",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_releases_by_id_assets(owner, repo, id, confirmed: bool = False) -> dict:
    """Create a release attachment

    Service: gitea  |  POST /repos/{owner}/{repo}/releases/{id}/assets
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/releases/{id}/assets",
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_releases_by_id_assets_by_attachment_id(owner, repo, id, attachment_id, confirmed: bool = False) -> dict:
    """Delete a release attachment

    Service: gitea  |  DELETE /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_releases_by_id_assets_by_attachment_id(owner, repo, id, attachment_id, params: dict | None = None) -> dict:
    """Get a release attachment

    Service: gitea  |  GET /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_releases_by_id_assets_by_attachment_id(owner, repo, id, attachment_id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Edit a release attachment

    Service: gitea  |  PATCH /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_reviewers(owner, repo, params: dict | None = None) -> dict:
    """Return all users that can be requested to review in this repo

    Service: gitea  |  GET /repos/{owner}/{repo}/reviewers
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/reviewers",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_signing_key_gpg(owner, repo, params: dict | None = None) -> dict:
    """Get signing-key.gpg for given repository

    Service: gitea  |  GET /repos/{owner}/{repo}/signing-key.gpg
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/signing-key.gpg",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_signing_key_pub(owner, repo, params: dict | None = None) -> dict:
    """Get signing-key.pub for given repository

    Service: gitea  |  GET /repos/{owner}/{repo}/signing-key.pub
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/signing-key.pub",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_stargazers(owner, repo, params: dict | None = None) -> dict:
    """List a repo's stargazers

    Service: gitea  |  GET /repos/{owner}/{repo}/stargazers
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/stargazers",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_statuses_by_sha(owner, repo, sha, params: dict | None = None) -> dict:
    """Get a commit's statuses

    Service: gitea  |  GET /repos/{owner}/{repo}/statuses/{sha}
    Query params: sort(), state(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/statuses/{sha}",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_statuses_by_sha(owner, repo, sha, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a commit status

    Service: gitea  |  POST /repos/{owner}/{repo}/statuses/{sha}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/statuses/{sha}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_subscribers(owner, repo, params: dict | None = None) -> dict:
    """List a repo's watchers

    Service: gitea  |  GET /repos/{owner}/{repo}/subscribers
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/subscribers",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_subscription(owner, repo, confirmed: bool = False) -> dict:
    """Unwatch a repo

    Service: gitea  |  DELETE /repos/{owner}/{repo}/subscription
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/subscription",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_subscription(owner, repo, params: dict | None = None) -> dict:
    """Check if the current user is watching a repo

    Service: gitea  |  GET /repos/{owner}/{repo}/subscription
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/subscription",
        params=params,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_subscription(owner, repo, confirmed: bool = False) -> dict:
    """Watch a repo

    Service: gitea  |  PUT /repos/{owner}/{repo}/subscription
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/subscription",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_tag_protections(owner, repo, params: dict | None = None) -> dict:
    """List tag protections for a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/tag_protections
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/tag_protections",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_tag_protections(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a tag protections for a repository

    Service: gitea  |  POST /repos/{owner}/{repo}/tag_protections
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/tag_protections",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_tag_protections_by_id(owner, repo, id, confirmed: bool = False) -> dict:
    """Delete a specific tag protection for the repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/tag_protections/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/tag_protections/{id}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_tag_protections_by_id(owner, repo, id, params: dict | None = None) -> dict:
    """Get a specific tag protection for the repository

    Service: gitea  |  GET /repos/{owner}/{repo}/tag_protections/{id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/tag_protections/{id}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_tag_protections_by_id(owner, repo, id, body: dict | None = None, confirmed: bool = False) -> dict:
    """Edit a tag protections for a repository. Only fields that are set will be changed

    Service: gitea  |  PATCH /repos/{owner}/{repo}/tag_protections/{id}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/tag_protections/{id}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_tags(owner, repo, params: dict | None = None) -> dict:
    """List a repository's tags

    Service: gitea  |  GET /repos/{owner}/{repo}/tags
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/tags",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_tags(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a new git tag in a repository

    Service: gitea  |  POST /repos/{owner}/{repo}/tags
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/tags",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_tags_by_tag(owner, repo, tag, confirmed: bool = False) -> dict:
    """Delete a repository's tag by name

    Service: gitea  |  DELETE /repos/{owner}/{repo}/tags/{tag}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/tags/{tag}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_tags_by_tag(owner, repo, tag, params: dict | None = None) -> dict:
    """Get the tag of a repository by tag name

    Service: gitea  |  GET /repos/{owner}/{repo}/tags/{tag}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/tags/{tag}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_teams(owner, repo, params: dict | None = None) -> dict:
    """List a repository's teams

    Service: gitea  |  GET /repos/{owner}/{repo}/teams
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/teams",
        params=params,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_teams_by_team(owner, repo, team, confirmed: bool = False) -> dict:
    """Delete a team from a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/teams/{team}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/teams/{team}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_teams_by_team(owner, repo, team, params: dict | None = None) -> dict:
    """Check if a team is assigned to a repository

    Service: gitea  |  GET /repos/{owner}/{repo}/teams/{team}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/teams/{team}",
        params=params,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_teams_by_team(owner, repo, team, confirmed: bool = False) -> dict:
    """Add a team to a repository

    Service: gitea  |  PUT /repos/{owner}/{repo}/teams/{team}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/teams/{team}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_times(owner, repo, params: dict | None = None) -> dict:
    """List a repo's tracked times

    Service: gitea  |  GET /repos/{owner}/{repo}/times
    Query params: user(), since(), before(), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/times",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_times_by_user(owner, repo, user, params: dict | None = None) -> dict:
    """List a user's tracked times in a repo

    Service: gitea  |  GET /repos/{owner}/{repo}/times/{user}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/times/{user}",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_topics(owner, repo, params: dict | None = None) -> dict:
    """Get list of topics that a repository has

    Service: gitea  |  GET /repos/{owner}/{repo}/topics
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/topics",
        params=params,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_topics(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Replace list of topics for a repository

    Service: gitea  |  PUT /repos/{owner}/{repo}/topics
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/topics",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_topics_by_topic(owner, repo, topic, confirmed: bool = False) -> dict:
    """Delete a topic from a repository

    Service: gitea  |  DELETE /repos/{owner}/{repo}/topics/{topic}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/topics/{topic}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_put_repos_by_owner_by_repo_topics_by_topic(owner, repo, topic, confirmed: bool = False) -> dict:
    """Add a topic to a repository

    Service: gitea  |  PUT /repos/{owner}/{repo}/topics/{topic}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PUT",
        f"/repos/{owner}/{repo}/topics/{topic}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_transfer(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Transfer a repo ownership

    Service: gitea  |  POST /repos/{owner}/{repo}/transfer
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/transfer",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_transfer_accept(owner, repo, confirmed: bool = False) -> dict:
    """Accept a repo transfer

    Service: gitea  |  POST /repos/{owner}/{repo}/transfer/accept
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/transfer/accept",
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_transfer_reject(owner, repo, confirmed: bool = False) -> dict:
    """Reject a repo transfer

    Service: gitea  |  POST /repos/{owner}/{repo}/transfer/reject
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/transfer/reject",
        confirmed=confirmed,
    )


@tool
def gitea_repository_post_repos_by_owner_by_repo_wiki_new(owner, repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a wiki page

    Service: gitea  |  POST /repos/{owner}/{repo}/wiki/new
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{owner}/{repo}/wiki/new",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_delete_repos_by_owner_by_repo_wiki_page_by_pagename(owner, repo, pageName, confirmed: bool = False) -> dict:
    """Delete a wiki page

    Service: gitea  |  DELETE /repos/{owner}/{repo}/wiki/page/{pageName}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "DELETE",
        f"/repos/{owner}/{repo}/wiki/page/{pageName}",
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_wiki_page_by_pagename(owner, repo, pageName, params: dict | None = None) -> dict:
    """Get a wiki page

    Service: gitea  |  GET /repos/{owner}/{repo}/wiki/page/{pageName}
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/wiki/page/{pageName}",
        params=params,
    )


@tool
def gitea_repository_patch_repos_by_owner_by_repo_wiki_page_by_pagename(owner, repo, pageName, body: dict | None = None, confirmed: bool = False) -> dict:
    """Edit a wiki page

    Service: gitea  |  PATCH /repos/{owner}/{repo}/wiki/page/{pageName}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "PATCH",
        f"/repos/{owner}/{repo}/wiki/page/{pageName}",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_wiki_pages(owner, repo, params: dict | None = None) -> dict:
    """Get all wiki pages

    Service: gitea  |  GET /repos/{owner}/{repo}/wiki/pages
    Query params: page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/wiki/pages",
        params=params,
    )


@tool
def gitea_repository_get_repos_by_owner_by_repo_wiki_revisions_by_pagename(owner, repo, pageName, params: dict | None = None) -> dict:
    """Get revisions of a wiki page

    Service: gitea  |  GET /repos/{owner}/{repo}/wiki/revisions/{pageName}
    Query params: page(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/repos/{owner}/{repo}/wiki/revisions/{pageName}",
        params=params,
    )


@tool
def gitea_repository_post_repos_by_template_owner_by_template_repo_generate(template_owner, template_repo, body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a repository using a template

    Service: gitea  |  POST /repos/{template_owner}/{template_repo}/generate
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/repos/{template_owner}/{template_repo}/generate",
        body=body,
        confirmed=confirmed,
    )


@tool
def gitea_repository_get_repositories_by_id(id, params: dict | None = None) -> dict:
    """Get a repository by id

    Service: gitea  |  GET /repositories/{id}
    """
    return _call(
        "gitea",
        "GET",
        f"/repositories/{id}",
        params=params,
    )


@tool
def gitea_repository_get_topics_search(params: dict | None = None) -> dict:
    """search topics via keyword

    Service: gitea  |  GET /topics/search
    Query params: q(*), page(), limit(). Pass as params={'key': 'value'}.
    """
    return _call(
        "gitea",
        "GET",
        f"/topics/search",
        params=params,
    )


@tool
def gitea_repository_post_user_repos(body: dict | None = None, confirmed: bool = False) -> dict:
    """Create a repository

    Service: gitea  |  POST /user/repos
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "gitea",
        "POST",
        f"/user/repos",
        body=body,
        confirmed=confirmed,
    )

