"""Auto-generated tool: InfluxDB 2.7 NetOps — Health, ready, ping endpoints

Generated by olav.platform.services.tool_generator
Service: influxdb_netops
Tag group: Health
DO NOT EDIT MANUALLY — re-run `olav service register influxdb_netops` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def influxdb_netops_health_get_health(params: dict | None = None) -> dict:
    """Get the health of an instance

    Service: influxdb_netops  |  GET /health
    """
    return _call(
        "influxdb_netops",
        "GET",
        f"/health",
        params=params,
        response_def="HealthCheck",
    )

