"""Auto-generated tool: InfluxDB 2.7 NetOps — InfluxDB Flux query and data read operations

Generated by olav.platform.services.tool_generator
Service: influxdb_netops
Tag group: Query
DO NOT EDIT MANUALLY — re-run `olav service register influxdb_netops` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def influxdb_netops_query_get_query_suggestions(params: dict | None = None) -> dict:
    """Retrieve query suggestions

    Service: influxdb_netops  |  GET /query/suggestions
    """
    return _call(
        "influxdb_netops",
        "GET",
        f"/query/suggestions",
        params=params,
        response_def="FluxSuggestions",
    )


@tool
def influxdb_netops_query_get_query_suggestions_by_name(name, params: dict | None = None) -> dict:
    """Retrieve query suggestions for a branching suggestion

    Service: influxdb_netops  |  GET /query/suggestions/{name}
    """
    return _call(
        "influxdb_netops",
        "GET",
        f"/query/suggestions/{name}",
        params=params,
        response_def="FluxSuggestion",
    )

