"""Auto-generated tool: InfluxDB v2 — InfluxDB v2 Organizations management (list, get, create, update, delete)

Generated by olav.platform.services.tool_generator
Service: influxdb
Tag group: Organizations
DO NOT EDIT MANUALLY — re-run `olav service register influxdb` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def influxdb_orgs_get_orgs(params: dict | None = None) -> dict:
    """List all organizations

    Service: influxdb  |  GET /orgs
    Query params: org(), orgID(), userID(). Pass as params={'key': 'value'}.
    """
    return _call(
        "influxdb",
        "GET",
        f"/orgs",
        params=params,
        response_def="Organizations",
    )


@tool
def influxdb_orgs_post_orgs(body: dict | None = None, confirmed: bool = False) -> dict:
    """Create an organization

    Service: influxdb  |  POST /orgs
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "influxdb",
        "POST",
        f"/orgs",
        body=body,
        response_def="Organization",
        confirmed=confirmed,
    )


@tool
def influxdb_orgs_delete_orgs_by_orgid(orgID, confirmed: bool = False) -> dict:
    """Delete an organization

    Service: influxdb  |  DELETE /orgs/{orgID}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "influxdb",
        "DELETE",
        f"/orgs/{orgID}",
        confirmed=confirmed,
    )


@tool
def influxdb_orgs_get_orgs_by_orgid(orgID, params: dict | None = None) -> dict:
    """Retrieve an organization

    Service: influxdb  |  GET /orgs/{orgID}
    """
    return _call(
        "influxdb",
        "GET",
        f"/orgs/{orgID}",
        params=params,
        response_def="Organization",
    )


@tool
def influxdb_orgs_patch_orgs_by_orgid(orgID, body: dict | None = None, confirmed: bool = False) -> dict:
    """Update an organization

    Service: influxdb  |  PATCH /orgs/{orgID}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "influxdb",
        "PATCH",
        f"/orgs/{orgID}",
        body=body,
        response_def="Organization",
        confirmed=confirmed,
    )


@tool
def influxdb_orgs_get_orgs_by_orgid_members(orgID, params: dict | None = None) -> dict:
    """List all members of an organization

    Service: influxdb  |  GET /orgs/{orgID}/members
    """
    return _call(
        "influxdb",
        "GET",
        f"/orgs/{orgID}/members",
        params=params,
        response_def="ResourceMembers",
    )


@tool
def influxdb_orgs_post_orgs_by_orgid_members(orgID, body: dict | None = None, confirmed: bool = False) -> dict:
    """Add a member to an organization

    Service: influxdb  |  POST /orgs/{orgID}/members
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "influxdb",
        "POST",
        f"/orgs/{orgID}/members",
        body=body,
        response_def="ResourceMember",
        confirmed=confirmed,
    )


@tool
def influxdb_orgs_delete_orgs_by_orgid_members_by_userid(orgID, userID, confirmed: bool = False) -> dict:
    """Remove a member from an organization

    Service: influxdb  |  DELETE /orgs/{orgID}/members/{userID}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "influxdb",
        "DELETE",
        f"/orgs/{orgID}/members/{userID}",
        confirmed=confirmed,
    )


@tool
def influxdb_orgs_get_orgs_by_orgid_owners(orgID, params: dict | None = None) -> dict:
    """List all owners of an organization

    Service: influxdb  |  GET /orgs/{orgID}/owners
    """
    return _call(
        "influxdb",
        "GET",
        f"/orgs/{orgID}/owners",
        params=params,
        response_def="ResourceOwners",
    )


@tool
def influxdb_orgs_post_orgs_by_orgid_owners(orgID, body: dict | None = None, confirmed: bool = False) -> dict:
    """Add an owner to an organization

    Service: influxdb  |  POST /orgs/{orgID}/owners
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "influxdb",
        "POST",
        f"/orgs/{orgID}/owners",
        body=body,
        response_def="ResourceOwner",
        confirmed=confirmed,
    )


@tool
def influxdb_orgs_delete_orgs_by_orgid_owners_by_userid(orgID, userID, confirmed: bool = False) -> dict:
    """Remove an owner from an organization

    Service: influxdb  |  DELETE /orgs/{orgID}/owners/{userID}
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "influxdb",
        "DELETE",
        f"/orgs/{orgID}/owners/{userID}",
        confirmed=confirmed,
    )

