"""Auto-generated tool: NetBox — Tenants and contacts

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: tenancy
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def netbox_tenancy_delete_api_tenancy_contact_assignments(confirmed: bool = False) -> dict:
    """tenancy_contact_assignments_bulk_destroy

    Service: netbox  |  DELETE /api/tenancy/contact-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contact-assignments/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_assignments(params: dict | None = None) -> dict:
    """tenancy_contact_assignments_list

    Service: netbox  |  GET /api/tenancy/contact-assignments/
    Query params: contact_id(), contact_id__n(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-assignments/",
        params=params,
        response_def="PaginatedContactAssignmentList",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contact_assignments(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_assignments_bulk_partial_update

    Service: netbox  |  PATCH /api/tenancy/contact-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contact-assignments/",
        body=body,
        response_def="ContactAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_post_api_tenancy_contact_assignments(confirmed: bool = False) -> dict:
    """tenancy_contact_assignments_create

    Service: netbox  |  POST /api/tenancy/contact-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/tenancy/contact-assignments/",
        response_def="ContactAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contact_assignments(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_assignments_bulk_update

    Service: netbox  |  PUT /api/tenancy/contact-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contact-assignments/",
        body=body,
        response_def="ContactAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_contact_assignments_by_id(id, confirmed: bool = False) -> dict:
    """tenancy_contact_assignments_destroy

    Service: netbox  |  DELETE /api/tenancy/contact-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contact-assignments/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_assignments_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contact_assignments_retrieve

    Service: netbox  |  GET /api/tenancy/contact-assignments/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-assignments/{id}/",
        params=params,
        response_def="ContactAssignment",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contact_assignments_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_assignments_partial_update

    Service: netbox  |  PATCH /api/tenancy/contact-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contact-assignments/{id}/",
        body=body,
        response_def="ContactAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contact_assignments_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_assignments_update

    Service: netbox  |  PUT /api/tenancy/contact-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contact-assignments/{id}/",
        body=body,
        response_def="ContactAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_contact_groups(confirmed: bool = False) -> dict:
    """tenancy_contact_groups_bulk_destroy

    Service: netbox  |  DELETE /api/tenancy/contact-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contact-groups/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_groups(params: dict | None = None) -> dict:
    """tenancy_contact_groups_list

    Service: netbox  |  GET /api/tenancy/contact-groups/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), contact_id(), contact_id__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-groups/",
        params=params,
        response_def="PaginatedContactGroupList",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contact_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_groups_bulk_partial_update

    Service: netbox  |  PATCH /api/tenancy/contact-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contact-groups/",
        body=body,
        response_def="ContactGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_post_api_tenancy_contact_groups(confirmed: bool = False) -> dict:
    """tenancy_contact_groups_create

    Service: netbox  |  POST /api/tenancy/contact-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/tenancy/contact-groups/",
        response_def="ContactGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contact_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_groups_bulk_update

    Service: netbox  |  PUT /api/tenancy/contact-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contact-groups/",
        body=body,
        response_def="ContactGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_contact_groups_by_id(id, confirmed: bool = False) -> dict:
    """tenancy_contact_groups_destroy

    Service: netbox  |  DELETE /api/tenancy/contact-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contact-groups/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_groups_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contact_groups_retrieve

    Service: netbox  |  GET /api/tenancy/contact-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-groups/{id}/",
        params=params,
        response_def="ContactGroup",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contact_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_groups_partial_update

    Service: netbox  |  PATCH /api/tenancy/contact-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contact-groups/{id}/",
        body=body,
        response_def="ContactGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contact_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_groups_update

    Service: netbox  |  PUT /api/tenancy/contact-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contact-groups/{id}/",
        body=body,
        response_def="ContactGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_contact_roles(confirmed: bool = False) -> dict:
    """tenancy_contact_roles_bulk_destroy

    Service: netbox  |  DELETE /api/tenancy/contact-roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contact-roles/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_roles(params: dict | None = None) -> dict:
    """tenancy_contact_roles_list

    Service: netbox  |  GET /api/tenancy/contact-roles/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-roles/",
        params=params,
        response_def="PaginatedContactRoleList",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contact_roles(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_roles_bulk_partial_update

    Service: netbox  |  PATCH /api/tenancy/contact-roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contact-roles/",
        body=body,
        response_def="ContactRole",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_post_api_tenancy_contact_roles(confirmed: bool = False) -> dict:
    """tenancy_contact_roles_create

    Service: netbox  |  POST /api/tenancy/contact-roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/tenancy/contact-roles/",
        response_def="ContactRole",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contact_roles(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_roles_bulk_update

    Service: netbox  |  PUT /api/tenancy/contact-roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contact-roles/",
        body=body,
        response_def="ContactRole",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_contact_roles_by_id(id, confirmed: bool = False) -> dict:
    """tenancy_contact_roles_destroy

    Service: netbox  |  DELETE /api/tenancy/contact-roles/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contact-roles/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_roles_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contact_roles_retrieve

    Service: netbox  |  GET /api/tenancy/contact-roles/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-roles/{id}/",
        params=params,
        response_def="ContactRole",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contact_roles_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_roles_partial_update

    Service: netbox  |  PATCH /api/tenancy/contact-roles/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contact-roles/{id}/",
        body=body,
        response_def="ContactRole",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contact_roles_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contact_roles_update

    Service: netbox  |  PUT /api/tenancy/contact-roles/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contact-roles/{id}/",
        body=body,
        response_def="ContactRole",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_contacts(confirmed: bool = False) -> dict:
    """tenancy_contacts_bulk_destroy

    Service: netbox  |  DELETE /api/tenancy/contacts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contacts/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contacts(params: dict | None = None) -> dict:
    """tenancy_contacts_list

    Service: netbox  |  GET /api/tenancy/contacts/
    Query params: address(), address__empty(), address__ic(), address__ie(), address__iew(), address__iregex(), address__isw(), address__n(), address__nic(), address__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contacts/",
        params=params,
        response_def="PaginatedContactList",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contacts(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contacts_bulk_partial_update

    Service: netbox  |  PATCH /api/tenancy/contacts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contacts/",
        body=body,
        response_def="Contact",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_post_api_tenancy_contacts(confirmed: bool = False) -> dict:
    """tenancy_contacts_create

    Service: netbox  |  POST /api/tenancy/contacts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/tenancy/contacts/",
        response_def="Contact",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contacts(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contacts_bulk_update

    Service: netbox  |  PUT /api/tenancy/contacts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contacts/",
        body=body,
        response_def="Contact",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_contacts_by_id(id, confirmed: bool = False) -> dict:
    """tenancy_contacts_destroy

    Service: netbox  |  DELETE /api/tenancy/contacts/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/contacts/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_contacts_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contacts_retrieve

    Service: netbox  |  GET /api/tenancy/contacts/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contacts/{id}/",
        params=params,
        response_def="Contact",
    )


@tool
def netbox_tenancy_patch_api_tenancy_contacts_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contacts_partial_update

    Service: netbox  |  PATCH /api/tenancy/contacts/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/contacts/{id}/",
        body=body,
        response_def="Contact",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_contacts_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_contacts_update

    Service: netbox  |  PUT /api/tenancy/contacts/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/contacts/{id}/",
        body=body,
        response_def="Contact",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_tenant_groups(confirmed: bool = False) -> dict:
    """tenancy_tenant_groups_bulk_destroy

    Service: netbox  |  DELETE /api/tenancy/tenant-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/tenant-groups/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_tenant_groups(params: dict | None = None) -> dict:
    """tenancy_tenant_groups_list

    Service: netbox  |  GET /api/tenancy/tenant-groups/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenant-groups/",
        params=params,
        response_def="PaginatedTenantGroupList",
    )


@tool
def netbox_tenancy_patch_api_tenancy_tenant_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenant_groups_bulk_partial_update

    Service: netbox  |  PATCH /api/tenancy/tenant-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/tenant-groups/",
        body=body,
        response_def="TenantGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_post_api_tenancy_tenant_groups(confirmed: bool = False) -> dict:
    """tenancy_tenant_groups_create

    Service: netbox  |  POST /api/tenancy/tenant-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/tenancy/tenant-groups/",
        response_def="TenantGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_tenant_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenant_groups_bulk_update

    Service: netbox  |  PUT /api/tenancy/tenant-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/tenant-groups/",
        body=body,
        response_def="TenantGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_tenant_groups_by_id(id, confirmed: bool = False) -> dict:
    """tenancy_tenant_groups_destroy

    Service: netbox  |  DELETE /api/tenancy/tenant-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/tenant-groups/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_tenant_groups_by_id(id, params: dict | None = None) -> dict:
    """tenancy_tenant_groups_retrieve

    Service: netbox  |  GET /api/tenancy/tenant-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenant-groups/{id}/",
        params=params,
        response_def="TenantGroup",
    )


@tool
def netbox_tenancy_patch_api_tenancy_tenant_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenant_groups_partial_update

    Service: netbox  |  PATCH /api/tenancy/tenant-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/tenant-groups/{id}/",
        body=body,
        response_def="TenantGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_tenant_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenant_groups_update

    Service: netbox  |  PUT /api/tenancy/tenant-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/tenant-groups/{id}/",
        body=body,
        response_def="TenantGroup",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_tenants(confirmed: bool = False) -> dict:
    """tenancy_tenants_bulk_destroy

    Service: netbox  |  DELETE /api/tenancy/tenants/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/tenants/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_tenants(params: dict | None = None) -> dict:
    """tenancy_tenants_list

    Service: netbox  |  GET /api/tenancy/tenants/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenants/",
        params=params,
        response_def="PaginatedTenantList",
    )


@tool
def netbox_tenancy_patch_api_tenancy_tenants(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenants_bulk_partial_update

    Service: netbox  |  PATCH /api/tenancy/tenants/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/tenants/",
        body=body,
        response_def="Tenant",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_post_api_tenancy_tenants(confirmed: bool = False) -> dict:
    """tenancy_tenants_create

    Service: netbox  |  POST /api/tenancy/tenants/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/tenancy/tenants/",
        response_def="Tenant",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_tenants(body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenants_bulk_update

    Service: netbox  |  PUT /api/tenancy/tenants/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/tenants/",
        body=body,
        response_def="Tenant",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_delete_api_tenancy_tenants_by_id(id, confirmed: bool = False) -> dict:
    """tenancy_tenants_destroy

    Service: netbox  |  DELETE /api/tenancy/tenants/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/tenancy/tenants/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_get_api_tenancy_tenants_by_id(id, params: dict | None = None) -> dict:
    """tenancy_tenants_retrieve

    Service: netbox  |  GET /api/tenancy/tenants/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenants/{id}/",
        params=params,
        response_def="Tenant",
    )


@tool
def netbox_tenancy_patch_api_tenancy_tenants_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenants_partial_update

    Service: netbox  |  PATCH /api/tenancy/tenants/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/tenancy/tenants/{id}/",
        body=body,
        response_def="Tenant",
        confirmed=confirmed,
    )


@tool
def netbox_tenancy_put_api_tenancy_tenants_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """tenancy_tenants_update

    Service: netbox  |  PUT /api/tenancy/tenants/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/tenancy/tenants/{id}/",
        body=body,
        response_def="Tenant",
        confirmed=confirmed,
    )

