"""Auto-generated tool: NetBox — IP addresses, prefixes, VLANs, VRFs

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: ipam
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def netbox_ipam_delete_api_ipam_aggregates(confirmed: bool = False) -> dict:
    """ipam_aggregates_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/aggregates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/aggregates/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_aggregates(params: dict | None = None) -> dict:
    """ipam_aggregates_list

    Service: netbox  |  GET /api/ipam/aggregates/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/aggregates/",
        params=params,
        response_def="PaginatedAggregateList",
    )


@tool
def netbox_ipam_patch_api_ipam_aggregates(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_aggregates_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/aggregates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/aggregates/",
        body=body,
        response_def="Aggregate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_aggregates(confirmed: bool = False) -> dict:
    """ipam_aggregates_create

    Service: netbox  |  POST /api/ipam/aggregates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/aggregates/",
        response_def="Aggregate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_aggregates(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_aggregates_bulk_update

    Service: netbox  |  PUT /api/ipam/aggregates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/aggregates/",
        body=body,
        response_def="Aggregate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_aggregates_by_id(id, confirmed: bool = False) -> dict:
    """ipam_aggregates_destroy

    Service: netbox  |  DELETE /api/ipam/aggregates/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/aggregates/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_aggregates_by_id(id, params: dict | None = None) -> dict:
    """ipam_aggregates_retrieve

    Service: netbox  |  GET /api/ipam/aggregates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/aggregates/{id}/",
        params=params,
        response_def="Aggregate",
    )


@tool
def netbox_ipam_patch_api_ipam_aggregates_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_aggregates_partial_update

    Service: netbox  |  PATCH /api/ipam/aggregates/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/aggregates/{id}/",
        body=body,
        response_def="Aggregate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_aggregates_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_aggregates_update

    Service: netbox  |  PUT /api/ipam/aggregates/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/aggregates/{id}/",
        body=body,
        response_def="Aggregate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_asn_ranges(confirmed: bool = False) -> dict:
    """ipam_asn_ranges_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/asn-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/asn-ranges/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_asn_ranges(params: dict | None = None) -> dict:
    """ipam_asn_ranges_list

    Service: netbox  |  GET /api/ipam/asn-ranges/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/asn-ranges/",
        params=params,
        response_def="PaginatedASNRangeList",
    )


@tool
def netbox_ipam_patch_api_ipam_asn_ranges(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asn_ranges_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/asn-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/asn-ranges/",
        body=body,
        response_def="ASNRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_asn_ranges(confirmed: bool = False) -> dict:
    """ipam_asn_ranges_create

    Service: netbox  |  POST /api/ipam/asn-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/asn-ranges/",
        response_def="ASNRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_asn_ranges(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asn_ranges_bulk_update

    Service: netbox  |  PUT /api/ipam/asn-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/asn-ranges/",
        body=body,
        response_def="ASNRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_asn_ranges_by_id(id, confirmed: bool = False) -> dict:
    """ipam_asn_ranges_destroy

    Service: netbox  |  DELETE /api/ipam/asn-ranges/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/asn-ranges/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_asn_ranges_by_id(id, params: dict | None = None) -> dict:
    """ipam_asn_ranges_retrieve

    Service: netbox  |  GET /api/ipam/asn-ranges/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/asn-ranges/{id}/",
        params=params,
        response_def="ASNRange",
    )


@tool
def netbox_ipam_patch_api_ipam_asn_ranges_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asn_ranges_partial_update

    Service: netbox  |  PATCH /api/ipam/asn-ranges/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/asn-ranges/{id}/",
        body=body,
        response_def="ASNRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_asn_ranges_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asn_ranges_update

    Service: netbox  |  PUT /api/ipam/asn-ranges/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/asn-ranges/{id}/",
        body=body,
        response_def="ASNRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_asn_ranges_by_id_available_asns(id, params: dict | None = None) -> dict:
    """ipam_asn_ranges_available_asns_list

    Service: netbox  |  GET /api/ipam/asn-ranges/{id}/available-asns/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/asn-ranges/{id}/available-asns/",
        params=params,
        response_def="AvailableASN",
    )


@tool
def netbox_ipam_post_api_ipam_asn_ranges_by_id_available_asns(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asn_ranges_available_asns_create

    Service: netbox  |  POST /api/ipam/asn-ranges/{id}/available-asns/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/asn-ranges/{id}/available-asns/",
        body=body,
        response_def="ASN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_asns(confirmed: bool = False) -> dict:
    """ipam_asns_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/asns/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/asns/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_asns(params: dict | None = None) -> dict:
    """ipam_asns_list

    Service: netbox  |  GET /api/ipam/asns/
    Query params: asn(), asn__empty(), asn__gt(), asn__gte(), asn__lt(), asn__lte(), asn__n(), created(), created__empty(), created__gt(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/asns/",
        params=params,
        response_def="PaginatedASNList",
    )


@tool
def netbox_ipam_patch_api_ipam_asns(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asns_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/asns/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/asns/",
        body=body,
        response_def="ASN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_asns(confirmed: bool = False) -> dict:
    """ipam_asns_create

    Service: netbox  |  POST /api/ipam/asns/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/asns/",
        response_def="ASN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_asns(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asns_bulk_update

    Service: netbox  |  PUT /api/ipam/asns/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/asns/",
        body=body,
        response_def="ASN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_asns_by_id(id, confirmed: bool = False) -> dict:
    """ipam_asns_destroy

    Service: netbox  |  DELETE /api/ipam/asns/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/asns/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_asns_by_id(id, params: dict | None = None) -> dict:
    """ipam_asns_retrieve

    Service: netbox  |  GET /api/ipam/asns/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/asns/{id}/",
        params=params,
        response_def="ASN",
    )


@tool
def netbox_ipam_patch_api_ipam_asns_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asns_partial_update

    Service: netbox  |  PATCH /api/ipam/asns/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/asns/{id}/",
        body=body,
        response_def="ASN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_asns_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_asns_update

    Service: netbox  |  PUT /api/ipam/asns/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/asns/{id}/",
        body=body,
        response_def="ASN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_fhrp_group_assignments(confirmed: bool = False) -> dict:
    """ipam_fhrp_group_assignments_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/fhrp-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/fhrp-group-assignments/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_fhrp_group_assignments(params: dict | None = None) -> dict:
    """ipam_fhrp_group_assignments_list

    Service: netbox  |  GET /api/ipam/fhrp-group-assignments/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), device(), device_id(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/fhrp-group-assignments/",
        params=params,
        response_def="PaginatedFHRPGroupAssignmentList",
    )


@tool
def netbox_ipam_patch_api_ipam_fhrp_group_assignments(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_group_assignments_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/fhrp-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/fhrp-group-assignments/",
        body=body,
        response_def="FHRPGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_fhrp_group_assignments(confirmed: bool = False) -> dict:
    """ipam_fhrp_group_assignments_create

    Service: netbox  |  POST /api/ipam/fhrp-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/fhrp-group-assignments/",
        response_def="FHRPGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_fhrp_group_assignments(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_group_assignments_bulk_update

    Service: netbox  |  PUT /api/ipam/fhrp-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/fhrp-group-assignments/",
        body=body,
        response_def="FHRPGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_fhrp_group_assignments_by_id(id, confirmed: bool = False) -> dict:
    """ipam_fhrp_group_assignments_destroy

    Service: netbox  |  DELETE /api/ipam/fhrp-group-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/fhrp-group-assignments/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_fhrp_group_assignments_by_id(id, params: dict | None = None) -> dict:
    """ipam_fhrp_group_assignments_retrieve

    Service: netbox  |  GET /api/ipam/fhrp-group-assignments/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/fhrp-group-assignments/{id}/",
        params=params,
        response_def="FHRPGroupAssignment",
    )


@tool
def netbox_ipam_patch_api_ipam_fhrp_group_assignments_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_group_assignments_partial_update

    Service: netbox  |  PATCH /api/ipam/fhrp-group-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/fhrp-group-assignments/{id}/",
        body=body,
        response_def="FHRPGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_fhrp_group_assignments_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_group_assignments_update

    Service: netbox  |  PUT /api/ipam/fhrp-group-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/fhrp-group-assignments/{id}/",
        body=body,
        response_def="FHRPGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_fhrp_groups(confirmed: bool = False) -> dict:
    """ipam_fhrp_groups_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/fhrp-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/fhrp-groups/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_fhrp_groups(params: dict | None = None) -> dict:
    """ipam_fhrp_groups_list

    Service: netbox  |  GET /api/ipam/fhrp-groups/
    Query params: auth_key(), auth_key__empty(), auth_key__ic(), auth_key__ie(), auth_key__iew(), auth_key__iregex(), auth_key__isw(), auth_key__n(), auth_key__nic(), auth_key__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/fhrp-groups/",
        params=params,
        response_def="PaginatedFHRPGroupList",
    )


@tool
def netbox_ipam_patch_api_ipam_fhrp_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_groups_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/fhrp-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/fhrp-groups/",
        body=body,
        response_def="FHRPGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_fhrp_groups(confirmed: bool = False) -> dict:
    """ipam_fhrp_groups_create

    Service: netbox  |  POST /api/ipam/fhrp-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/fhrp-groups/",
        response_def="FHRPGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_fhrp_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_groups_bulk_update

    Service: netbox  |  PUT /api/ipam/fhrp-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/fhrp-groups/",
        body=body,
        response_def="FHRPGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_fhrp_groups_by_id(id, confirmed: bool = False) -> dict:
    """ipam_fhrp_groups_destroy

    Service: netbox  |  DELETE /api/ipam/fhrp-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/fhrp-groups/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_fhrp_groups_by_id(id, params: dict | None = None) -> dict:
    """ipam_fhrp_groups_retrieve

    Service: netbox  |  GET /api/ipam/fhrp-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/fhrp-groups/{id}/",
        params=params,
        response_def="FHRPGroup",
    )


@tool
def netbox_ipam_patch_api_ipam_fhrp_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_groups_partial_update

    Service: netbox  |  PATCH /api/ipam/fhrp-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/fhrp-groups/{id}/",
        body=body,
        response_def="FHRPGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_fhrp_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_fhrp_groups_update

    Service: netbox  |  PUT /api/ipam/fhrp-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/fhrp-groups/{id}/",
        body=body,
        response_def="FHRPGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_ip_addresses(confirmed: bool = False) -> dict:
    """ipam_ip_addresses_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/ip-addresses/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/ip-addresses/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_ip_addresses(params: dict | None = None) -> dict:
    """ipam_ip_addresses_list

    Service: netbox  |  GET /api/ipam/ip-addresses/
    Query params: address(), assigned(), assigned_object_id(), assigned_object_id__empty(), assigned_object_id__gt(), assigned_object_id__gte(), assigned_object_id__lt(), assigned_object_id__lte(), assigned_object_id__n(), assigned_object_type(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/ip-addresses/",
        params=params,
        response_def="PaginatedIPAddressList",
    )


@tool
def netbox_ipam_patch_api_ipam_ip_addresses(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_addresses_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/ip-addresses/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/ip-addresses/",
        body=body,
        response_def="IPAddress",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_ip_addresses(confirmed: bool = False) -> dict:
    """ipam_ip_addresses_create

    Service: netbox  |  POST /api/ipam/ip-addresses/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/ip-addresses/",
        response_def="IPAddress",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_ip_addresses(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_addresses_bulk_update

    Service: netbox  |  PUT /api/ipam/ip-addresses/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/ip-addresses/",
        body=body,
        response_def="IPAddress",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_ip_addresses_by_id(id, confirmed: bool = False) -> dict:
    """ipam_ip_addresses_destroy

    Service: netbox  |  DELETE /api/ipam/ip-addresses/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/ip-addresses/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_ip_addresses_by_id(id, params: dict | None = None) -> dict:
    """ipam_ip_addresses_retrieve

    Service: netbox  |  GET /api/ipam/ip-addresses/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/ip-addresses/{id}/",
        params=params,
        response_def="IPAddress",
    )


@tool
def netbox_ipam_patch_api_ipam_ip_addresses_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_addresses_partial_update

    Service: netbox  |  PATCH /api/ipam/ip-addresses/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/ip-addresses/{id}/",
        body=body,
        response_def="IPAddress",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_ip_addresses_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_addresses_update

    Service: netbox  |  PUT /api/ipam/ip-addresses/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/ip-addresses/{id}/",
        body=body,
        response_def="IPAddress",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_ip_ranges(confirmed: bool = False) -> dict:
    """ipam_ip_ranges_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/ip-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/ip-ranges/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_ip_ranges(params: dict | None = None) -> dict:
    """ipam_ip_ranges_list

    Service: netbox  |  GET /api/ipam/ip-ranges/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), contains(), created(), created__empty(), created__gt(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/ip-ranges/",
        params=params,
        response_def="PaginatedIPRangeList",
    )


@tool
def netbox_ipam_patch_api_ipam_ip_ranges(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_ranges_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/ip-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/ip-ranges/",
        body=body,
        response_def="IPRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_ip_ranges(confirmed: bool = False) -> dict:
    """ipam_ip_ranges_create

    Service: netbox  |  POST /api/ipam/ip-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/ip-ranges/",
        response_def="IPRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_ip_ranges(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_ranges_bulk_update

    Service: netbox  |  PUT /api/ipam/ip-ranges/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/ip-ranges/",
        body=body,
        response_def="IPRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_ip_ranges_by_id(id, confirmed: bool = False) -> dict:
    """ipam_ip_ranges_destroy

    Service: netbox  |  DELETE /api/ipam/ip-ranges/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/ip-ranges/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_ip_ranges_by_id(id, params: dict | None = None) -> dict:
    """ipam_ip_ranges_retrieve

    Service: netbox  |  GET /api/ipam/ip-ranges/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/ip-ranges/{id}/",
        params=params,
        response_def="IPRange",
    )


@tool
def netbox_ipam_patch_api_ipam_ip_ranges_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_ranges_partial_update

    Service: netbox  |  PATCH /api/ipam/ip-ranges/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/ip-ranges/{id}/",
        body=body,
        response_def="IPRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_ip_ranges_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_ranges_update

    Service: netbox  |  PUT /api/ipam/ip-ranges/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/ip-ranges/{id}/",
        body=body,
        response_def="IPRange",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_ip_ranges_by_id_available_ips(id, params: dict | None = None) -> dict:
    """ipam_ip_ranges_available_ips_list

    Service: netbox  |  GET /api/ipam/ip-ranges/{id}/available-ips/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/ip-ranges/{id}/available-ips/",
        params=params,
        response_def="AvailableIP",
    )


@tool
def netbox_ipam_post_api_ipam_ip_ranges_by_id_available_ips(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_ip_ranges_available_ips_create

    Service: netbox  |  POST /api/ipam/ip-ranges/{id}/available-ips/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/ip-ranges/{id}/available-ips/",
        body=body,
        response_def="IPAddress",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_prefixes(confirmed: bool = False) -> dict:
    """ipam_prefixes_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/prefixes/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/prefixes/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_prefixes(params: dict | None = None) -> dict:
    """ipam_prefixes_list

    Service: netbox  |  GET /api/ipam/prefixes/
    Query params: children(), children__empty(), children__gt(), children__gte(), children__lt(), children__lte(), children__n(), contact(), contact__n(), contact_group(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/prefixes/",
        params=params,
        response_def="PaginatedPrefixList",
    )


@tool
def netbox_ipam_patch_api_ipam_prefixes(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_prefixes_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/prefixes/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/prefixes/",
        body=body,
        response_def="Prefix",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_prefixes(confirmed: bool = False) -> dict:
    """ipam_prefixes_create

    Service: netbox  |  POST /api/ipam/prefixes/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/prefixes/",
        response_def="Prefix",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_prefixes(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_prefixes_bulk_update

    Service: netbox  |  PUT /api/ipam/prefixes/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/prefixes/",
        body=body,
        response_def="Prefix",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_prefixes_by_id(id, confirmed: bool = False) -> dict:
    """ipam_prefixes_destroy

    Service: netbox  |  DELETE /api/ipam/prefixes/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/prefixes/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_prefixes_by_id(id, params: dict | None = None) -> dict:
    """ipam_prefixes_retrieve

    Service: netbox  |  GET /api/ipam/prefixes/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/prefixes/{id}/",
        params=params,
        response_def="Prefix",
    )


@tool
def netbox_ipam_patch_api_ipam_prefixes_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_prefixes_partial_update

    Service: netbox  |  PATCH /api/ipam/prefixes/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/prefixes/{id}/",
        body=body,
        response_def="Prefix",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_prefixes_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_prefixes_update

    Service: netbox  |  PUT /api/ipam/prefixes/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/prefixes/{id}/",
        body=body,
        response_def="Prefix",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_prefixes_by_id_available_ips(id, params: dict | None = None) -> dict:
    """ipam_prefixes_available_ips_list

    Service: netbox  |  GET /api/ipam/prefixes/{id}/available-ips/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/prefixes/{id}/available-ips/",
        params=params,
        response_def="AvailableIP",
    )


@tool
def netbox_ipam_post_api_ipam_prefixes_by_id_available_ips(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_prefixes_available_ips_create

    Service: netbox  |  POST /api/ipam/prefixes/{id}/available-ips/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/prefixes/{id}/available-ips/",
        body=body,
        response_def="IPAddress",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_prefixes_by_id_available_prefixes(id, params: dict | None = None) -> dict:
    """ipam_prefixes_available_prefixes_list

    Service: netbox  |  GET /api/ipam/prefixes/{id}/available-prefixes/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/prefixes/{id}/available-prefixes/",
        params=params,
        response_def="AvailablePrefix",
    )


@tool
def netbox_ipam_post_api_ipam_prefixes_by_id_available_prefixes(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_prefixes_available_prefixes_create

    Service: netbox  |  POST /api/ipam/prefixes/{id}/available-prefixes/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/prefixes/{id}/available-prefixes/",
        body=body,
        response_def="Prefix",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_rirs(confirmed: bool = False) -> dict:
    """ipam_rirs_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/rirs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/rirs/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_rirs(params: dict | None = None) -> dict:
    """ipam_rirs_list

    Service: netbox  |  GET /api/ipam/rirs/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/rirs/",
        params=params,
        response_def="PaginatedRIRList",
    )


@tool
def netbox_ipam_patch_api_ipam_rirs(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_rirs_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/rirs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/rirs/",
        body=body,
        response_def="RIR",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_rirs(confirmed: bool = False) -> dict:
    """ipam_rirs_create

    Service: netbox  |  POST /api/ipam/rirs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/rirs/",
        response_def="RIR",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_rirs(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_rirs_bulk_update

    Service: netbox  |  PUT /api/ipam/rirs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/rirs/",
        body=body,
        response_def="RIR",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_rirs_by_id(id, confirmed: bool = False) -> dict:
    """ipam_rirs_destroy

    Service: netbox  |  DELETE /api/ipam/rirs/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/rirs/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_rirs_by_id(id, params: dict | None = None) -> dict:
    """ipam_rirs_retrieve

    Service: netbox  |  GET /api/ipam/rirs/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/rirs/{id}/",
        params=params,
        response_def="RIR",
    )


@tool
def netbox_ipam_patch_api_ipam_rirs_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_rirs_partial_update

    Service: netbox  |  PATCH /api/ipam/rirs/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/rirs/{id}/",
        body=body,
        response_def="RIR",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_rirs_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_rirs_update

    Service: netbox  |  PUT /api/ipam/rirs/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/rirs/{id}/",
        body=body,
        response_def="RIR",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_roles(confirmed: bool = False) -> dict:
    """ipam_roles_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/roles/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_roles(params: dict | None = None) -> dict:
    """ipam_roles_list

    Service: netbox  |  GET /api/ipam/roles/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/roles/",
        params=params,
        response_def="PaginatedRoleList",
    )


@tool
def netbox_ipam_patch_api_ipam_roles(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_roles_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/roles/",
        body=body,
        response_def="Role",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_roles(confirmed: bool = False) -> dict:
    """ipam_roles_create

    Service: netbox  |  POST /api/ipam/roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/roles/",
        response_def="Role",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_roles(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_roles_bulk_update

    Service: netbox  |  PUT /api/ipam/roles/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/roles/",
        body=body,
        response_def="Role",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_roles_by_id(id, confirmed: bool = False) -> dict:
    """ipam_roles_destroy

    Service: netbox  |  DELETE /api/ipam/roles/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/roles/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_roles_by_id(id, params: dict | None = None) -> dict:
    """ipam_roles_retrieve

    Service: netbox  |  GET /api/ipam/roles/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/roles/{id}/",
        params=params,
        response_def="Role",
    )


@tool
def netbox_ipam_patch_api_ipam_roles_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_roles_partial_update

    Service: netbox  |  PATCH /api/ipam/roles/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/roles/{id}/",
        body=body,
        response_def="Role",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_roles_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_roles_update

    Service: netbox  |  PUT /api/ipam/roles/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/roles/{id}/",
        body=body,
        response_def="Role",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_route_targets(confirmed: bool = False) -> dict:
    """ipam_route_targets_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/route-targets/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/route-targets/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_route_targets(params: dict | None = None) -> dict:
    """ipam_route_targets_list

    Service: netbox  |  GET /api/ipam/route-targets/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/route-targets/",
        params=params,
        response_def="PaginatedRouteTargetList",
    )


@tool
def netbox_ipam_patch_api_ipam_route_targets(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_route_targets_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/route-targets/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/route-targets/",
        body=body,
        response_def="RouteTarget",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_route_targets(confirmed: bool = False) -> dict:
    """ipam_route_targets_create

    Service: netbox  |  POST /api/ipam/route-targets/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/route-targets/",
        response_def="RouteTarget",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_route_targets(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_route_targets_bulk_update

    Service: netbox  |  PUT /api/ipam/route-targets/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/route-targets/",
        body=body,
        response_def="RouteTarget",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_route_targets_by_id(id, confirmed: bool = False) -> dict:
    """ipam_route_targets_destroy

    Service: netbox  |  DELETE /api/ipam/route-targets/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/route-targets/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_route_targets_by_id(id, params: dict | None = None) -> dict:
    """ipam_route_targets_retrieve

    Service: netbox  |  GET /api/ipam/route-targets/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/route-targets/{id}/",
        params=params,
        response_def="RouteTarget",
    )


@tool
def netbox_ipam_patch_api_ipam_route_targets_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_route_targets_partial_update

    Service: netbox  |  PATCH /api/ipam/route-targets/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/route-targets/{id}/",
        body=body,
        response_def="RouteTarget",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_route_targets_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_route_targets_update

    Service: netbox  |  PUT /api/ipam/route-targets/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/route-targets/{id}/",
        body=body,
        response_def="RouteTarget",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_service_templates(confirmed: bool = False) -> dict:
    """ipam_service_templates_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/service-templates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/service-templates/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_service_templates(params: dict | None = None) -> dict:
    """ipam_service_templates_list

    Service: netbox  |  GET /api/ipam/service-templates/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/service-templates/",
        params=params,
        response_def="PaginatedServiceTemplateList",
    )


@tool
def netbox_ipam_patch_api_ipam_service_templates(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_service_templates_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/service-templates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/service-templates/",
        body=body,
        response_def="ServiceTemplate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_service_templates(confirmed: bool = False) -> dict:
    """ipam_service_templates_create

    Service: netbox  |  POST /api/ipam/service-templates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/service-templates/",
        response_def="ServiceTemplate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_service_templates(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_service_templates_bulk_update

    Service: netbox  |  PUT /api/ipam/service-templates/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/service-templates/",
        body=body,
        response_def="ServiceTemplate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_service_templates_by_id(id, confirmed: bool = False) -> dict:
    """ipam_service_templates_destroy

    Service: netbox  |  DELETE /api/ipam/service-templates/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/service-templates/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_service_templates_by_id(id, params: dict | None = None) -> dict:
    """ipam_service_templates_retrieve

    Service: netbox  |  GET /api/ipam/service-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/service-templates/{id}/",
        params=params,
        response_def="ServiceTemplate",
    )


@tool
def netbox_ipam_patch_api_ipam_service_templates_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_service_templates_partial_update

    Service: netbox  |  PATCH /api/ipam/service-templates/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/service-templates/{id}/",
        body=body,
        response_def="ServiceTemplate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_service_templates_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_service_templates_update

    Service: netbox  |  PUT /api/ipam/service-templates/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/service-templates/{id}/",
        body=body,
        response_def="ServiceTemplate",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_services(confirmed: bool = False) -> dict:
    """ipam_services_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/services/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/services/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_services(params: dict | None = None) -> dict:
    """ipam_services_list

    Service: netbox  |  GET /api/ipam/services/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/services/",
        params=params,
        response_def="PaginatedServiceList",
    )


@tool
def netbox_ipam_patch_api_ipam_services(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_services_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/services/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/services/",
        body=body,
        response_def="Service",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_services(confirmed: bool = False) -> dict:
    """ipam_services_create

    Service: netbox  |  POST /api/ipam/services/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/services/",
        response_def="Service",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_services(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_services_bulk_update

    Service: netbox  |  PUT /api/ipam/services/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/services/",
        body=body,
        response_def="Service",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_services_by_id(id, confirmed: bool = False) -> dict:
    """ipam_services_destroy

    Service: netbox  |  DELETE /api/ipam/services/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/services/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_services_by_id(id, params: dict | None = None) -> dict:
    """ipam_services_retrieve

    Service: netbox  |  GET /api/ipam/services/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/services/{id}/",
        params=params,
        response_def="Service",
    )


@tool
def netbox_ipam_patch_api_ipam_services_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_services_partial_update

    Service: netbox  |  PATCH /api/ipam/services/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/services/{id}/",
        body=body,
        response_def="Service",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_services_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_services_update

    Service: netbox  |  PUT /api/ipam/services/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/services/{id}/",
        body=body,
        response_def="Service",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlan_groups(confirmed: bool = False) -> dict:
    """ipam_vlan_groups_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/vlan-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlan-groups/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlan_groups(params: dict | None = None) -> dict:
    """ipam_vlan_groups_list

    Service: netbox  |  GET /api/ipam/vlan-groups/
    Query params: cluster(), cluster_group(), contains_vid(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlan-groups/",
        params=params,
        response_def="PaginatedVLANGroupList",
    )


@tool
def netbox_ipam_patch_api_ipam_vlan_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_groups_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/vlan-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlan-groups/",
        body=body,
        response_def="VLANGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_vlan_groups(confirmed: bool = False) -> dict:
    """ipam_vlan_groups_create

    Service: netbox  |  POST /api/ipam/vlan-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/vlan-groups/",
        response_def="VLANGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlan_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_groups_bulk_update

    Service: netbox  |  PUT /api/ipam/vlan-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlan-groups/",
        body=body,
        response_def="VLANGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlan_groups_by_id(id, confirmed: bool = False) -> dict:
    """ipam_vlan_groups_destroy

    Service: netbox  |  DELETE /api/ipam/vlan-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlan-groups/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlan_groups_by_id(id, params: dict | None = None) -> dict:
    """ipam_vlan_groups_retrieve

    Service: netbox  |  GET /api/ipam/vlan-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlan-groups/{id}/",
        params=params,
        response_def="VLANGroup",
    )


@tool
def netbox_ipam_patch_api_ipam_vlan_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_groups_partial_update

    Service: netbox  |  PATCH /api/ipam/vlan-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlan-groups/{id}/",
        body=body,
        response_def="VLANGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlan_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_groups_update

    Service: netbox  |  PUT /api/ipam/vlan-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlan-groups/{id}/",
        body=body,
        response_def="VLANGroup",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlan_groups_by_id_available_vlans(id, params: dict | None = None) -> dict:
    """ipam_vlan_groups_available_vlans_list

    Service: netbox  |  GET /api/ipam/vlan-groups/{id}/available-vlans/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlan-groups/{id}/available-vlans/",
        params=params,
        response_def="AvailableVLAN",
    )


@tool
def netbox_ipam_post_api_ipam_vlan_groups_by_id_available_vlans(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_groups_available_vlans_create

    Service: netbox  |  POST /api/ipam/vlan-groups/{id}/available-vlans/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/vlan-groups/{id}/available-vlans/",
        body=body,
        response_def="VLAN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlan_translation_policies(confirmed: bool = False) -> dict:
    """ipam_vlan_translation_policies_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/vlan-translation-policies/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlan-translation-policies/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlan_translation_policies(params: dict | None = None) -> dict:
    """ipam_vlan_translation_policies_list

    Service: netbox  |  GET /api/ipam/vlan-translation-policies/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlan-translation-policies/",
        params=params,
        response_def="PaginatedVLANTranslationPolicyList",
    )


@tool
def netbox_ipam_patch_api_ipam_vlan_translation_policies(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_policies_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/vlan-translation-policies/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlan-translation-policies/",
        body=body,
        response_def="VLANTranslationPolicy",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_vlan_translation_policies(confirmed: bool = False) -> dict:
    """ipam_vlan_translation_policies_create

    Service: netbox  |  POST /api/ipam/vlan-translation-policies/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/vlan-translation-policies/",
        response_def="VLANTranslationPolicy",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlan_translation_policies(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_policies_bulk_update

    Service: netbox  |  PUT /api/ipam/vlan-translation-policies/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlan-translation-policies/",
        body=body,
        response_def="VLANTranslationPolicy",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlan_translation_policies_by_id(id, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_policies_destroy

    Service: netbox  |  DELETE /api/ipam/vlan-translation-policies/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlan-translation-policies/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlan_translation_policies_by_id(id, params: dict | None = None) -> dict:
    """ipam_vlan_translation_policies_retrieve

    Service: netbox  |  GET /api/ipam/vlan-translation-policies/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlan-translation-policies/{id}/",
        params=params,
        response_def="VLANTranslationPolicy",
    )


@tool
def netbox_ipam_patch_api_ipam_vlan_translation_policies_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_policies_partial_update

    Service: netbox  |  PATCH /api/ipam/vlan-translation-policies/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlan-translation-policies/{id}/",
        body=body,
        response_def="VLANTranslationPolicy",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlan_translation_policies_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_policies_update

    Service: netbox  |  PUT /api/ipam/vlan-translation-policies/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlan-translation-policies/{id}/",
        body=body,
        response_def="VLANTranslationPolicy",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlan_translation_rules(confirmed: bool = False) -> dict:
    """ipam_vlan_translation_rules_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/vlan-translation-rules/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlan-translation-rules/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlan_translation_rules(params: dict | None = None) -> dict:
    """ipam_vlan_translation_rules_list

    Service: netbox  |  GET /api/ipam/vlan-translation-rules/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlan-translation-rules/",
        params=params,
        response_def="PaginatedVLANTranslationRuleList",
    )


@tool
def netbox_ipam_patch_api_ipam_vlan_translation_rules(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_rules_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/vlan-translation-rules/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlan-translation-rules/",
        body=body,
        response_def="VLANTranslationRule",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_vlan_translation_rules(confirmed: bool = False) -> dict:
    """ipam_vlan_translation_rules_create

    Service: netbox  |  POST /api/ipam/vlan-translation-rules/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/vlan-translation-rules/",
        response_def="VLANTranslationRule",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlan_translation_rules(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_rules_bulk_update

    Service: netbox  |  PUT /api/ipam/vlan-translation-rules/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlan-translation-rules/",
        body=body,
        response_def="VLANTranslationRule",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlan_translation_rules_by_id(id, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_rules_destroy

    Service: netbox  |  DELETE /api/ipam/vlan-translation-rules/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlan-translation-rules/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlan_translation_rules_by_id(id, params: dict | None = None) -> dict:
    """ipam_vlan_translation_rules_retrieve

    Service: netbox  |  GET /api/ipam/vlan-translation-rules/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlan-translation-rules/{id}/",
        params=params,
        response_def="VLANTranslationRule",
    )


@tool
def netbox_ipam_patch_api_ipam_vlan_translation_rules_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_rules_partial_update

    Service: netbox  |  PATCH /api/ipam/vlan-translation-rules/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlan-translation-rules/{id}/",
        body=body,
        response_def="VLANTranslationRule",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlan_translation_rules_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlan_translation_rules_update

    Service: netbox  |  PUT /api/ipam/vlan-translation-rules/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlan-translation-rules/{id}/",
        body=body,
        response_def="VLANTranslationRule",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlans(confirmed: bool = False) -> dict:
    """ipam_vlans_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/vlans/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlans/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlans(params: dict | None = None) -> dict:
    """ipam_vlans_list

    Service: netbox  |  GET /api/ipam/vlans/
    Query params: available_at_site(), available_on_device(), available_on_virtualmachine(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlans/",
        params=params,
        response_def="PaginatedVLANList",
    )


@tool
def netbox_ipam_patch_api_ipam_vlans(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlans_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/vlans/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlans/",
        body=body,
        response_def="VLAN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_vlans(confirmed: bool = False) -> dict:
    """ipam_vlans_create

    Service: netbox  |  POST /api/ipam/vlans/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/vlans/",
        response_def="VLAN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlans(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlans_bulk_update

    Service: netbox  |  PUT /api/ipam/vlans/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlans/",
        body=body,
        response_def="VLAN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vlans_by_id(id, confirmed: bool = False) -> dict:
    """ipam_vlans_destroy

    Service: netbox  |  DELETE /api/ipam/vlans/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vlans/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vlans_by_id(id, params: dict | None = None) -> dict:
    """ipam_vlans_retrieve

    Service: netbox  |  GET /api/ipam/vlans/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vlans/{id}/",
        params=params,
        response_def="VLAN",
    )


@tool
def netbox_ipam_patch_api_ipam_vlans_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlans_partial_update

    Service: netbox  |  PATCH /api/ipam/vlans/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vlans/{id}/",
        body=body,
        response_def="VLAN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vlans_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vlans_update

    Service: netbox  |  PUT /api/ipam/vlans/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vlans/{id}/",
        body=body,
        response_def="VLAN",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vrfs(confirmed: bool = False) -> dict:
    """ipam_vrfs_bulk_destroy

    Service: netbox  |  DELETE /api/ipam/vrfs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vrfs/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vrfs(params: dict | None = None) -> dict:
    """ipam_vrfs_list

    Service: netbox  |  GET /api/ipam/vrfs/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vrfs/",
        params=params,
        response_def="PaginatedVRFList",
    )


@tool
def netbox_ipam_patch_api_ipam_vrfs(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vrfs_bulk_partial_update

    Service: netbox  |  PATCH /api/ipam/vrfs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vrfs/",
        body=body,
        response_def="VRF",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_post_api_ipam_vrfs(confirmed: bool = False) -> dict:
    """ipam_vrfs_create

    Service: netbox  |  POST /api/ipam/vrfs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/ipam/vrfs/",
        response_def="VRF",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vrfs(body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vrfs_bulk_update

    Service: netbox  |  PUT /api/ipam/vrfs/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vrfs/",
        body=body,
        response_def="VRF",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_delete_api_ipam_vrfs_by_id(id, confirmed: bool = False) -> dict:
    """ipam_vrfs_destroy

    Service: netbox  |  DELETE /api/ipam/vrfs/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/ipam/vrfs/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_get_api_ipam_vrfs_by_id(id, params: dict | None = None) -> dict:
    """ipam_vrfs_retrieve

    Service: netbox  |  GET /api/ipam/vrfs/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/ipam/vrfs/{id}/",
        params=params,
        response_def="VRF",
    )


@tool
def netbox_ipam_patch_api_ipam_vrfs_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vrfs_partial_update

    Service: netbox  |  PATCH /api/ipam/vrfs/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/ipam/vrfs/{id}/",
        body=body,
        response_def="VRF",
        confirmed=confirmed,
    )


@tool
def netbox_ipam_put_api_ipam_vrfs_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """ipam_vrfs_update

    Service: netbox  |  PUT /api/ipam/vrfs/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/ipam/vrfs/{id}/",
        body=body,
        response_def="VRF",
        confirmed=confirmed,
    )

