"""Auto-generated tool: NetBox DCIM/IPAM — Tenants, contacts, groups

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: tenancy
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def netbox_tenancy_get_api_tenancy_contact_assignments(params: dict | None = None) -> dict:
    """tenancy_contact_assignments_list

    Service: netbox  |  GET /api/tenancy/contact-assignments/
    Query params: contact_id(), contact_id__n(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-assignments/",
        params=params,
        response_def="PaginatedContactAssignmentList",
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_assignments_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contact_assignments_retrieve

    Service: netbox  |  GET /api/tenancy/contact-assignments/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-assignments/{id}/",
        params=params,
        response_def="ContactAssignment",
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_groups(params: dict | None = None) -> dict:
    """tenancy_contact_groups_list

    Service: netbox  |  GET /api/tenancy/contact-groups/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), contact_id(), contact_id__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-groups/",
        params=params,
        response_def="PaginatedContactGroupList",
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_groups_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contact_groups_retrieve

    Service: netbox  |  GET /api/tenancy/contact-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-groups/{id}/",
        params=params,
        response_def="ContactGroup",
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_roles(params: dict | None = None) -> dict:
    """tenancy_contact_roles_list

    Service: netbox  |  GET /api/tenancy/contact-roles/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-roles/",
        params=params,
        response_def="PaginatedContactRoleList",
    )


@tool
def netbox_tenancy_get_api_tenancy_contact_roles_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contact_roles_retrieve

    Service: netbox  |  GET /api/tenancy/contact-roles/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contact-roles/{id}/",
        params=params,
        response_def="ContactRole",
    )


@tool
def netbox_tenancy_get_api_tenancy_contacts(params: dict | None = None) -> dict:
    """tenancy_contacts_list

    Service: netbox  |  GET /api/tenancy/contacts/
    Query params: address(), address__empty(), address__ic(), address__ie(), address__iew(), address__iregex(), address__isw(), address__n(), address__nic(), address__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contacts/",
        params=params,
        response_def="PaginatedContactList",
    )


@tool
def netbox_tenancy_get_api_tenancy_contacts_by_id(id, params: dict | None = None) -> dict:
    """tenancy_contacts_retrieve

    Service: netbox  |  GET /api/tenancy/contacts/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/contacts/{id}/",
        params=params,
        response_def="Contact",
    )


@tool
def netbox_tenancy_get_api_tenancy_tenant_groups(params: dict | None = None) -> dict:
    """tenancy_tenant_groups_list

    Service: netbox  |  GET /api/tenancy/tenant-groups/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenant-groups/",
        params=params,
        response_def="PaginatedTenantGroupList",
    )


@tool
def netbox_tenancy_get_api_tenancy_tenant_groups_by_id(id, params: dict | None = None) -> dict:
    """tenancy_tenant_groups_retrieve

    Service: netbox  |  GET /api/tenancy/tenant-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenant-groups/{id}/",
        params=params,
        response_def="TenantGroup",
    )


@tool
def netbox_tenancy_get_api_tenancy_tenants(params: dict | None = None) -> dict:
    """tenancy_tenants_list

    Service: netbox  |  GET /api/tenancy/tenants/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenants/",
        params=params,
        response_def="PaginatedTenantList",
    )


@tool
def netbox_tenancy_get_api_tenancy_tenants_by_id(id, params: dict | None = None) -> dict:
    """tenancy_tenants_retrieve

    Service: netbox  |  GET /api/tenancy/tenants/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/tenancy/tenants/{id}/",
        params=params,
        response_def="Tenant",
    )

