"""Auto-generated tool: NetBox DCIM/IPAM — Virtualization VMs and clusters

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: virtualization
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from olav.platform.services.client import service_call as _call


def netbox_vm_delete_api_virtualization_cluster_groups(confirmed: bool = False) -> dict:
    """virtualization_cluster_groups_bulk_destroy

    Service: netbox  |  DELETE /api/virtualization/cluster-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/cluster-groups/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_cluster_groups() -> dict:
    """virtualization_cluster_groups_list

    Service: netbox  |  GET /api/virtualization/cluster-groups/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-groups/",
        response_def="PaginatedClusterGroupList",
    )


def netbox_vm_patch_api_virtualization_cluster_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_groups_bulk_partial_update

    Service: netbox  |  PATCH /api/virtualization/cluster-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/cluster-groups/",
        body=body,
        response_def="ClusterGroup",
        confirmed=confirmed,
    )


def netbox_vm_post_api_virtualization_cluster_groups(confirmed: bool = False) -> dict:
    """virtualization_cluster_groups_create

    Service: netbox  |  POST /api/virtualization/cluster-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/virtualization/cluster-groups/",
        response_def="ClusterGroup",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_cluster_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_groups_bulk_update

    Service: netbox  |  PUT /api/virtualization/cluster-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/cluster-groups/",
        body=body,
        response_def="ClusterGroup",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_cluster_groups_by_id(id, confirmed: bool = False) -> dict:
    """virtualization_cluster_groups_destroy

    Service: netbox  |  DELETE /api/virtualization/cluster-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/cluster-groups/{id}/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_cluster_groups_by_id(id) -> dict:
    """virtualization_cluster_groups_retrieve

    Service: netbox  |  GET /api/virtualization/cluster-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-groups/{id}/",
        response_def="ClusterGroup",
    )


def netbox_vm_patch_api_virtualization_cluster_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_groups_partial_update

    Service: netbox  |  PATCH /api/virtualization/cluster-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/cluster-groups/{id}/",
        body=body,
        response_def="ClusterGroup",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_cluster_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_groups_update

    Service: netbox  |  PUT /api/virtualization/cluster-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/cluster-groups/{id}/",
        body=body,
        response_def="ClusterGroup",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_cluster_types(confirmed: bool = False) -> dict:
    """virtualization_cluster_types_bulk_destroy

    Service: netbox  |  DELETE /api/virtualization/cluster-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/cluster-types/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_cluster_types() -> dict:
    """virtualization_cluster_types_list

    Service: netbox  |  GET /api/virtualization/cluster-types/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-types/",
        response_def="PaginatedClusterTypeList",
    )


def netbox_vm_patch_api_virtualization_cluster_types(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_types_bulk_partial_update

    Service: netbox  |  PATCH /api/virtualization/cluster-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/cluster-types/",
        body=body,
        response_def="ClusterType",
        confirmed=confirmed,
    )


def netbox_vm_post_api_virtualization_cluster_types(confirmed: bool = False) -> dict:
    """virtualization_cluster_types_create

    Service: netbox  |  POST /api/virtualization/cluster-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/virtualization/cluster-types/",
        response_def="ClusterType",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_cluster_types(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_types_bulk_update

    Service: netbox  |  PUT /api/virtualization/cluster-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/cluster-types/",
        body=body,
        response_def="ClusterType",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_cluster_types_by_id(id, confirmed: bool = False) -> dict:
    """virtualization_cluster_types_destroy

    Service: netbox  |  DELETE /api/virtualization/cluster-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/cluster-types/{id}/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_cluster_types_by_id(id) -> dict:
    """virtualization_cluster_types_retrieve

    Service: netbox  |  GET /api/virtualization/cluster-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-types/{id}/",
        response_def="ClusterType",
    )


def netbox_vm_patch_api_virtualization_cluster_types_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_types_partial_update

    Service: netbox  |  PATCH /api/virtualization/cluster-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/cluster-types/{id}/",
        body=body,
        response_def="ClusterType",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_cluster_types_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_cluster_types_update

    Service: netbox  |  PUT /api/virtualization/cluster-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/cluster-types/{id}/",
        body=body,
        response_def="ClusterType",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_clusters(confirmed: bool = False) -> dict:
    """virtualization_clusters_bulk_destroy

    Service: netbox  |  DELETE /api/virtualization/clusters/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/clusters/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_clusters() -> dict:
    """virtualization_clusters_list

    Service: netbox  |  GET /api/virtualization/clusters/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/clusters/",
        response_def="PaginatedClusterList",
    )


def netbox_vm_patch_api_virtualization_clusters(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_clusters_bulk_partial_update

    Service: netbox  |  PATCH /api/virtualization/clusters/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/clusters/",
        body=body,
        response_def="Cluster",
        confirmed=confirmed,
    )


def netbox_vm_post_api_virtualization_clusters(confirmed: bool = False) -> dict:
    """virtualization_clusters_create

    Service: netbox  |  POST /api/virtualization/clusters/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/virtualization/clusters/",
        response_def="Cluster",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_clusters(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_clusters_bulk_update

    Service: netbox  |  PUT /api/virtualization/clusters/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/clusters/",
        body=body,
        response_def="Cluster",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_clusters_by_id(id, confirmed: bool = False) -> dict:
    """virtualization_clusters_destroy

    Service: netbox  |  DELETE /api/virtualization/clusters/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/clusters/{id}/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_clusters_by_id(id) -> dict:
    """virtualization_clusters_retrieve

    Service: netbox  |  GET /api/virtualization/clusters/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/clusters/{id}/",
        response_def="Cluster",
    )


def netbox_vm_patch_api_virtualization_clusters_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_clusters_partial_update

    Service: netbox  |  PATCH /api/virtualization/clusters/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/clusters/{id}/",
        body=body,
        response_def="Cluster",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_clusters_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_clusters_update

    Service: netbox  |  PUT /api/virtualization/clusters/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/clusters/{id}/",
        body=body,
        response_def="Cluster",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_interfaces(confirmed: bool = False) -> dict:
    """virtualization_interfaces_bulk_destroy

    Service: netbox  |  DELETE /api/virtualization/interfaces/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/interfaces/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_interfaces() -> dict:
    """virtualization_interfaces_list

    Service: netbox  |  GET /api/virtualization/interfaces/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/interfaces/",
        response_def="PaginatedVMInterfaceList",
    )


def netbox_vm_patch_api_virtualization_interfaces(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_interfaces_bulk_partial_update

    Service: netbox  |  PATCH /api/virtualization/interfaces/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/interfaces/",
        body=body,
        response_def="VMInterface",
        confirmed=confirmed,
    )


def netbox_vm_post_api_virtualization_interfaces(confirmed: bool = False) -> dict:
    """virtualization_interfaces_create

    Service: netbox  |  POST /api/virtualization/interfaces/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/virtualization/interfaces/",
        response_def="VMInterface",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_interfaces(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_interfaces_bulk_update

    Service: netbox  |  PUT /api/virtualization/interfaces/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/interfaces/",
        body=body,
        response_def="VMInterface",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_interfaces_by_id(id, confirmed: bool = False) -> dict:
    """virtualization_interfaces_destroy

    Service: netbox  |  DELETE /api/virtualization/interfaces/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/interfaces/{id}/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_interfaces_by_id(id) -> dict:
    """virtualization_interfaces_retrieve

    Service: netbox  |  GET /api/virtualization/interfaces/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/interfaces/{id}/",
        response_def="VMInterface",
    )


def netbox_vm_patch_api_virtualization_interfaces_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_interfaces_partial_update

    Service: netbox  |  PATCH /api/virtualization/interfaces/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/interfaces/{id}/",
        body=body,
        response_def="VMInterface",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_interfaces_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_interfaces_update

    Service: netbox  |  PUT /api/virtualization/interfaces/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/interfaces/{id}/",
        body=body,
        response_def="VMInterface",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_virtual_disks(confirmed: bool = False) -> dict:
    """virtualization_virtual_disks_bulk_destroy

    Service: netbox  |  DELETE /api/virtualization/virtual-disks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/virtual-disks/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_virtual_disks() -> dict:
    """virtualization_virtual_disks_list

    Service: netbox  |  GET /api/virtualization/virtual-disks/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-disks/",
        response_def="PaginatedVirtualDiskList",
    )


def netbox_vm_patch_api_virtualization_virtual_disks(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_disks_bulk_partial_update

    Service: netbox  |  PATCH /api/virtualization/virtual-disks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/virtual-disks/",
        body=body,
        response_def="VirtualDisk",
        confirmed=confirmed,
    )


def netbox_vm_post_api_virtualization_virtual_disks(confirmed: bool = False) -> dict:
    """virtualization_virtual_disks_create

    Service: netbox  |  POST /api/virtualization/virtual-disks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/virtualization/virtual-disks/",
        response_def="VirtualDisk",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_virtual_disks(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_disks_bulk_update

    Service: netbox  |  PUT /api/virtualization/virtual-disks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/virtual-disks/",
        body=body,
        response_def="VirtualDisk",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_virtual_disks_by_id(id, confirmed: bool = False) -> dict:
    """virtualization_virtual_disks_destroy

    Service: netbox  |  DELETE /api/virtualization/virtual-disks/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/virtual-disks/{id}/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_virtual_disks_by_id(id) -> dict:
    """virtualization_virtual_disks_retrieve

    Service: netbox  |  GET /api/virtualization/virtual-disks/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-disks/{id}/",
        response_def="VirtualDisk",
    )


def netbox_vm_patch_api_virtualization_virtual_disks_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_disks_partial_update

    Service: netbox  |  PATCH /api/virtualization/virtual-disks/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/virtual-disks/{id}/",
        body=body,
        response_def="VirtualDisk",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_virtual_disks_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_disks_update

    Service: netbox  |  PUT /api/virtualization/virtual-disks/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/virtual-disks/{id}/",
        body=body,
        response_def="VirtualDisk",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_virtual_machines(confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_bulk_destroy

    Service: netbox  |  DELETE /api/virtualization/virtual-machines/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/virtual-machines/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_virtual_machines() -> dict:
    """virtualization_virtual_machines_list

    Service: netbox  |  GET /api/virtualization/virtual-machines/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-machines/",
        response_def="PaginatedVirtualMachineWithConfigContextList",
    )


def netbox_vm_patch_api_virtualization_virtual_machines(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_bulk_partial_update

    Service: netbox  |  PATCH /api/virtualization/virtual-machines/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/virtual-machines/",
        body=body,
        response_def="VirtualMachineWithConfigContext",
        confirmed=confirmed,
    )


def netbox_vm_post_api_virtualization_virtual_machines(confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_create

    Service: netbox  |  POST /api/virtualization/virtual-machines/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/virtualization/virtual-machines/",
        response_def="VirtualMachineWithConfigContext",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_virtual_machines(body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_bulk_update

    Service: netbox  |  PUT /api/virtualization/virtual-machines/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/virtual-machines/",
        body=body,
        response_def="VirtualMachineWithConfigContext",
        confirmed=confirmed,
    )


def netbox_vm_delete_api_virtualization_virtual_machines_by_id(id, confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_destroy

    Service: netbox  |  DELETE /api/virtualization/virtual-machines/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/virtualization/virtual-machines/{id}/",
        confirmed=confirmed,
    )


def netbox_vm_get_api_virtualization_virtual_machines_by_id(id) -> dict:
    """virtualization_virtual_machines_retrieve

    Service: netbox  |  GET /api/virtualization/virtual-machines/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-machines/{id}/",
        response_def="VirtualMachineWithConfigContext",
    )


def netbox_vm_patch_api_virtualization_virtual_machines_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_partial_update

    Service: netbox  |  PATCH /api/virtualization/virtual-machines/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/virtualization/virtual-machines/{id}/",
        body=body,
        response_def="VirtualMachineWithConfigContext",
        confirmed=confirmed,
    )


def netbox_vm_put_api_virtualization_virtual_machines_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_update

    Service: netbox  |  PUT /api/virtualization/virtual-machines/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/virtualization/virtual-machines/{id}/",
        body=body,
        response_def="VirtualMachineWithConfigContext",
        confirmed=confirmed,
    )


def netbox_vm_post_api_virtualization_virtual_machines_by_id_render_config(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """virtualization_virtual_machines_render_config_create

    Service: netbox  |  POST /api/virtualization/virtual-machines/{id}/render-config/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/virtualization/virtual-machines/{id}/render-config/",
        body=body,
        response_def="VirtualMachineWithConfigContext",
        confirmed=confirmed,
    )

