"""Auto-generated tool: NetBox DCIM/IPAM — Virtual machines, clusters, interfaces

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: virtualization
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def netbox_virtualization_get_api_virtualization_cluster_groups(params: dict | None = None) -> dict:
    """virtualization_cluster_groups_list

    Service: netbox  |  GET /api/virtualization/cluster-groups/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-groups/",
        params=params,
        response_def="PaginatedClusterGroupList",
    )


@tool
def netbox_virtualization_get_api_virtualization_cluster_groups_by_id(id, params: dict | None = None) -> dict:
    """virtualization_cluster_groups_retrieve

    Service: netbox  |  GET /api/virtualization/cluster-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-groups/{id}/",
        params=params,
        response_def="ClusterGroup",
    )


@tool
def netbox_virtualization_get_api_virtualization_cluster_types(params: dict | None = None) -> dict:
    """virtualization_cluster_types_list

    Service: netbox  |  GET /api/virtualization/cluster-types/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-types/",
        params=params,
        response_def="PaginatedClusterTypeList",
    )


@tool
def netbox_virtualization_get_api_virtualization_cluster_types_by_id(id, params: dict | None = None) -> dict:
    """virtualization_cluster_types_retrieve

    Service: netbox  |  GET /api/virtualization/cluster-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/cluster-types/{id}/",
        params=params,
        response_def="ClusterType",
    )


@tool
def netbox_virtualization_get_api_virtualization_clusters(params: dict | None = None) -> dict:
    """virtualization_clusters_list

    Service: netbox  |  GET /api/virtualization/clusters/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/clusters/",
        params=params,
        response_def="PaginatedClusterList",
    )


@tool
def netbox_virtualization_get_api_virtualization_clusters_by_id(id, params: dict | None = None) -> dict:
    """virtualization_clusters_retrieve

    Service: netbox  |  GET /api/virtualization/clusters/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/clusters/{id}/",
        params=params,
        response_def="Cluster",
    )


@tool
def netbox_virtualization_get_api_virtualization_interfaces(params: dict | None = None) -> dict:
    """virtualization_interfaces_list

    Service: netbox  |  GET /api/virtualization/interfaces/
    Query params: bridge_id(), bridge_id__n(), cluster(), cluster__n(), cluster_id(), cluster_id__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/interfaces/",
        params=params,
        response_def="PaginatedVMInterfaceList",
    )


@tool
def netbox_virtualization_get_api_virtualization_interfaces_by_id(id, params: dict | None = None) -> dict:
    """virtualization_interfaces_retrieve

    Service: netbox  |  GET /api/virtualization/interfaces/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/interfaces/{id}/",
        params=params,
        response_def="VMInterface",
    )


@tool
def netbox_virtualization_get_api_virtualization_virtual_disks(params: dict | None = None) -> dict:
    """virtualization_virtual_disks_list

    Service: netbox  |  GET /api/virtualization/virtual-disks/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-disks/",
        params=params,
        response_def="PaginatedVirtualDiskList",
    )


@tool
def netbox_virtualization_get_api_virtualization_virtual_disks_by_id(id, params: dict | None = None) -> dict:
    """virtualization_virtual_disks_retrieve

    Service: netbox  |  GET /api/virtualization/virtual-disks/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-disks/{id}/",
        params=params,
        response_def="VirtualDisk",
    )


@tool
def netbox_virtualization_get_api_virtualization_virtual_machines(params: dict | None = None) -> dict:
    """virtualization_virtual_machines_list

    Service: netbox  |  GET /api/virtualization/virtual-machines/
    Query params: cluster(), cluster__n(), cluster_group(), cluster_group__n(), cluster_group_id(), cluster_group_id__n(), cluster_id(), cluster_id__n(), cluster_type(), cluster_type__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-machines/",
        params=params,
        response_def="PaginatedVirtualMachineWithConfigContextList",
    )


@tool
def netbox_virtualization_get_api_virtualization_virtual_machines_by_id(id, params: dict | None = None) -> dict:
    """virtualization_virtual_machines_retrieve

    Service: netbox  |  GET /api/virtualization/virtual-machines/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/virtualization/virtual-machines/{id}/",
        params=params,
        response_def="VirtualMachineWithConfigContext",
    )

