"""Auto-generated tool: Netbox — Circuit providers, circuits, terminations, and virtual circuits management

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: circuits
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from olav.platform.services.client import service_call as _call


def netbox_circuits_get_api_circuits_circuit_group_assignments() -> dict:
    """circuits_circuit_group_assignments_list

    Service: netbox  |  GET /api/circuits/circuit-group-assignments/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-group-assignments/",
        response_def="PaginatedCircuitGroupAssignmentList",
    )


def netbox_circuits_get_api_circuits_circuit_group_assignments_by_id(id) -> dict:
    """circuits_circuit_group_assignments_retrieve

    Service: netbox  |  GET /api/circuits/circuit-group-assignments/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-group-assignments/{id}/",
        response_def="CircuitGroupAssignment",
    )


def netbox_circuits_get_api_circuits_circuit_groups() -> dict:
    """circuits_circuit_groups_list

    Service: netbox  |  GET /api/circuits/circuit-groups/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-groups/",
        response_def="PaginatedCircuitGroupList",
    )


def netbox_circuits_get_api_circuits_circuit_groups_by_id(id) -> dict:
    """circuits_circuit_groups_retrieve

    Service: netbox  |  GET /api/circuits/circuit-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-groups/{id}/",
        response_def="CircuitGroup",
    )


def netbox_circuits_get_api_circuits_circuit_terminations() -> dict:
    """circuits_circuit_terminations_list

    Service: netbox  |  GET /api/circuits/circuit-terminations/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/",
        response_def="PaginatedCircuitTerminationList",
    )


def netbox_circuits_get_api_circuits_circuit_terminations_by_id(id) -> dict:
    """circuits_circuit_terminations_retrieve

    Service: netbox  |  GET /api/circuits/circuit-terminations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/{id}/",
        response_def="CircuitTermination",
    )


def netbox_circuits_get_api_circuits_circuit_terminations_by_id_paths(id) -> dict:
    """circuits_circuit_terminations_paths_retrieve

    Service: netbox  |  GET /api/circuits/circuit-terminations/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/{id}/paths/",
        response_def="CircuitTermination",
    )


def netbox_circuits_get_api_circuits_circuit_types() -> dict:
    """circuits_circuit_types_list

    Service: netbox  |  GET /api/circuits/circuit-types/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-types/",
        response_def="PaginatedCircuitTypeList",
    )


def netbox_circuits_get_api_circuits_circuit_types_by_id(id) -> dict:
    """circuits_circuit_types_retrieve

    Service: netbox  |  GET /api/circuits/circuit-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-types/{id}/",
        response_def="CircuitType",
    )


def netbox_circuits_get_api_circuits_circuits() -> dict:
    """circuits_circuits_list

    Service: netbox  |  GET /api/circuits/circuits/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuits/",
        response_def="PaginatedCircuitList",
    )


def netbox_circuits_get_api_circuits_circuits_by_id(id) -> dict:
    """circuits_circuits_retrieve

    Service: netbox  |  GET /api/circuits/circuits/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuits/{id}/",
        response_def="Circuit",
    )


def netbox_circuits_get_api_circuits_provider_accounts() -> dict:
    """circuits_provider_accounts_list

    Service: netbox  |  GET /api/circuits/provider-accounts/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-accounts/",
        response_def="PaginatedProviderAccountList",
    )


def netbox_circuits_get_api_circuits_provider_accounts_by_id(id) -> dict:
    """circuits_provider_accounts_retrieve

    Service: netbox  |  GET /api/circuits/provider-accounts/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-accounts/{id}/",
        response_def="ProviderAccount",
    )


def netbox_circuits_get_api_circuits_provider_networks() -> dict:
    """circuits_provider_networks_list

    Service: netbox  |  GET /api/circuits/provider-networks/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-networks/",
        response_def="PaginatedProviderNetworkList",
    )


def netbox_circuits_get_api_circuits_provider_networks_by_id(id) -> dict:
    """circuits_provider_networks_retrieve

    Service: netbox  |  GET /api/circuits/provider-networks/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-networks/{id}/",
        response_def="ProviderNetwork",
    )


def netbox_circuits_get_api_circuits_providers() -> dict:
    """circuits_providers_list

    Service: netbox  |  GET /api/circuits/providers/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/providers/",
        response_def="PaginatedProviderList",
    )


def netbox_circuits_get_api_circuits_providers_by_id(id) -> dict:
    """circuits_providers_retrieve

    Service: netbox  |  GET /api/circuits/providers/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/providers/{id}/",
        response_def="Provider",
    )


def netbox_circuits_get_api_circuits_virtual_circuit_terminations() -> dict:
    """circuits_virtual_circuit_terminations_list

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/",
        response_def="PaginatedVirtualCircuitTerminationList",
    )


def netbox_circuits_get_api_circuits_virtual_circuit_terminations_by_id(id) -> dict:
    """circuits_virtual_circuit_terminations_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/{id}/",
        response_def="VirtualCircuitTermination",
    )


def netbox_circuits_get_api_circuits_virtual_circuit_terminations_by_id_paths(id) -> dict:
    """circuits_virtual_circuit_terminations_paths_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/{id}/paths/",
        response_def="VirtualCircuitTermination",
    )


def netbox_circuits_get_api_circuits_virtual_circuit_types() -> dict:
    """circuits_virtual_circuit_types_list

    Service: netbox  |  GET /api/circuits/virtual-circuit-types/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-types/",
        response_def="PaginatedVirtualCircuitTypeList",
    )


def netbox_circuits_get_api_circuits_virtual_circuit_types_by_id(id) -> dict:
    """circuits_virtual_circuit_types_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-types/{id}/",
        response_def="VirtualCircuitType",
    )


def netbox_circuits_get_api_circuits_virtual_circuits() -> dict:
    """circuits_virtual_circuits_list

    Service: netbox  |  GET /api/circuits/virtual-circuits/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuits/",
        response_def="PaginatedVirtualCircuitList",
    )


def netbox_circuits_get_api_circuits_virtual_circuits_by_id(id) -> dict:
    """circuits_virtual_circuits_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuits/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuits/{id}/",
        response_def="VirtualCircuit",
    )

