"""Auto-generated tool: NetBox DCIM/IPAM — DCIM: Devices, racks, sites, cables, interfaces, power, inventory

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: dcim
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def netbox_dcim_get_api_dcim_cable_terminations(params: dict | None = None) -> dict:
    """dcim_cable_terminations_list

    Service: netbox  |  GET /api/dcim/cable-terminations/
    Query params: cable(), cable__n(), cable_end(), cable_end__empty(), cable_end__ic(), cable_end__ie(), cable_end__iew(), cable_end__iregex(), cable_end__isw(), cable_end__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/cable-terminations/",
        params=params,
        response_def="PaginatedCableTerminationList",
    )


@tool
def netbox_dcim_get_api_dcim_cable_terminations_by_id(id, params: dict | None = None) -> dict:
    """dcim_cable_terminations_retrieve

    Service: netbox  |  GET /api/dcim/cable-terminations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/cable-terminations/{id}/",
        params=params,
        response_def="CableTermination",
    )


@tool
def netbox_dcim_get_api_dcim_cables(params: dict | None = None) -> dict:
    """dcim_cables_list

    Service: netbox  |  GET /api/dcim/cables/
    Query params: circuittermination_id(), color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/cables/",
        params=params,
        response_def="PaginatedCableList",
    )


@tool
def netbox_dcim_get_api_dcim_cables_by_id(id, params: dict | None = None) -> dict:
    """dcim_cables_retrieve

    Service: netbox  |  GET /api/dcim/cables/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/cables/{id}/",
        params=params,
        response_def="Cable",
    )


@tool
def netbox_dcim_get_api_dcim_connected_device(params: dict | None = None) -> dict:
    """dcim_connected_device_list

    Service: netbox  |  GET /api/dcim/connected-device/
    Query params: peer_device(*), peer_interface(*). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/connected-device/",
        params=params,
        response_def="Device",
    )


@tool
def netbox_dcim_get_api_dcim_console_port_templates(params: dict | None = None) -> dict:
    """dcim_console_port_templates_list

    Service: netbox  |  GET /api/dcim/console-port-templates/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-port-templates/",
        params=params,
        response_def="PaginatedConsolePortTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_console_port_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_console_port_templates_retrieve

    Service: netbox  |  GET /api/dcim/console-port-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-port-templates/{id}/",
        params=params,
        response_def="ConsolePortTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_console_ports(params: dict | None = None) -> dict:
    """dcim_console_ports_list

    Service: netbox  |  GET /api/dcim/console-ports/
    Query params: cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(), cable_end__empty(), cable_end__ic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-ports/",
        params=params,
        response_def="PaginatedConsolePortList",
    )


@tool
def netbox_dcim_get_api_dcim_console_ports_by_id(id, params: dict | None = None) -> dict:
    """dcim_console_ports_retrieve

    Service: netbox  |  GET /api/dcim/console-ports/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-ports/{id}/",
        params=params,
        response_def="ConsolePort",
    )


@tool
def netbox_dcim_get_api_dcim_console_ports_by_id_trace(id, params: dict | None = None) -> dict:
    """dcim_console_ports_trace_retrieve

    Service: netbox  |  GET /api/dcim/console-ports/{id}/trace/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-ports/{id}/trace/",
        params=params,
        response_def="ConsolePort",
    )


@tool
def netbox_dcim_get_api_dcim_console_server_port_templates(params: dict | None = None) -> dict:
    """dcim_console_server_port_templates_list

    Service: netbox  |  GET /api/dcim/console-server-port-templates/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-server-port-templates/",
        params=params,
        response_def="PaginatedConsoleServerPortTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_console_server_port_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_console_server_port_templates_retrieve

    Service: netbox  |  GET /api/dcim/console-server-port-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-server-port-templates/{id}/",
        params=params,
        response_def="ConsoleServerPortTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_console_server_ports(params: dict | None = None) -> dict:
    """dcim_console_server_ports_list

    Service: netbox  |  GET /api/dcim/console-server-ports/
    Query params: cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(), cable_end__empty(), cable_end__ic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-server-ports/",
        params=params,
        response_def="PaginatedConsoleServerPortList",
    )


@tool
def netbox_dcim_get_api_dcim_console_server_ports_by_id(id, params: dict | None = None) -> dict:
    """dcim_console_server_ports_retrieve

    Service: netbox  |  GET /api/dcim/console-server-ports/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-server-ports/{id}/",
        params=params,
        response_def="ConsoleServerPort",
    )


@tool
def netbox_dcim_get_api_dcim_console_server_ports_by_id_trace(id, params: dict | None = None) -> dict:
    """dcim_console_server_ports_trace_retrieve

    Service: netbox  |  GET /api/dcim/console-server-ports/{id}/trace/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/console-server-ports/{id}/trace/",
        params=params,
        response_def="ConsoleServerPort",
    )


@tool
def netbox_dcim_get_api_dcim_device_bay_templates(params: dict | None = None) -> dict:
    """dcim_device_bay_templates_list

    Service: netbox  |  GET /api/dcim/device-bay-templates/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-bay-templates/",
        params=params,
        response_def="PaginatedDeviceBayTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_device_bay_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_device_bay_templates_retrieve

    Service: netbox  |  GET /api/dcim/device-bay-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-bay-templates/{id}/",
        params=params,
        response_def="DeviceBayTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_device_bays(params: dict | None = None) -> dict:
    """dcim_device_bays_list

    Service: netbox  |  GET /api/dcim/device-bays/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-bays/",
        params=params,
        response_def="PaginatedDeviceBayList",
    )


@tool
def netbox_dcim_get_api_dcim_device_bays_by_id(id, params: dict | None = None) -> dict:
    """dcim_device_bays_retrieve

    Service: netbox  |  GET /api/dcim/device-bays/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-bays/{id}/",
        params=params,
        response_def="DeviceBay",
    )


@tool
def netbox_dcim_get_api_dcim_device_roles(params: dict | None = None) -> dict:
    """dcim_device_roles_list

    Service: netbox  |  GET /api/dcim/device-roles/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-roles/",
        params=params,
        response_def="PaginatedDeviceRoleList",
    )


@tool
def netbox_dcim_get_api_dcim_device_roles_by_id(id, params: dict | None = None) -> dict:
    """dcim_device_roles_retrieve

    Service: netbox  |  GET /api/dcim/device-roles/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-roles/{id}/",
        params=params,
        response_def="DeviceRole",
    )


@tool
def netbox_dcim_get_api_dcim_device_types(params: dict | None = None) -> dict:
    """dcim_device_types_list

    Service: netbox  |  GET /api/dcim/device-types/
    Query params: airflow(), airflow__empty(), airflow__ic(), airflow__ie(), airflow__iew(), airflow__iregex(), airflow__isw(), airflow__n(), airflow__nic(), airflow__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-types/",
        params=params,
        response_def="PaginatedDeviceTypeList",
    )


@tool
def netbox_dcim_get_api_dcim_device_types_by_id(id, params: dict | None = None) -> dict:
    """dcim_device_types_retrieve

    Service: netbox  |  GET /api/dcim/device-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/device-types/{id}/",
        params=params,
        response_def="DeviceType",
    )


@tool
def netbox_dcim_get_api_dcim_devices(params: dict | None = None) -> dict:
    """dcim_devices_list

    Service: netbox  |  GET /api/dcim/devices/
    Query params: airflow(), airflow__empty(), airflow__ic(), airflow__ie(), airflow__iew(), airflow__iregex(), airflow__isw(), airflow__n(), airflow__nic(), airflow__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/devices/",
        params=params,
        response_def="PaginatedDeviceWithConfigContextList",
    )


@tool
def netbox_dcim_get_api_dcim_devices_by_id(id, params: dict | None = None) -> dict:
    """dcim_devices_retrieve

    Service: netbox  |  GET /api/dcim/devices/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/devices/{id}/",
        params=params,
        response_def="DeviceWithConfigContext",
    )


@tool
def netbox_dcim_get_api_dcim_front_port_templates(params: dict | None = None) -> dict:
    """dcim_front_port_templates_list

    Service: netbox  |  GET /api/dcim/front-port-templates/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/front-port-templates/",
        params=params,
        response_def="PaginatedFrontPortTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_front_port_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_front_port_templates_retrieve

    Service: netbox  |  GET /api/dcim/front-port-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/front-port-templates/{id}/",
        params=params,
        response_def="FrontPortTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_front_ports(params: dict | None = None) -> dict:
    """dcim_front_ports_list

    Service: netbox  |  GET /api/dcim/front-ports/
    Query params: cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(), cable_end__empty(), cable_end__ic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/front-ports/",
        params=params,
        response_def="PaginatedFrontPortList",
    )


@tool
def netbox_dcim_get_api_dcim_front_ports_by_id(id, params: dict | None = None) -> dict:
    """dcim_front_ports_retrieve

    Service: netbox  |  GET /api/dcim/front-ports/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/front-ports/{id}/",
        params=params,
        response_def="FrontPort",
    )


@tool
def netbox_dcim_get_api_dcim_front_ports_by_id_paths(id, params: dict | None = None) -> dict:
    """dcim_front_ports_paths_retrieve

    Service: netbox  |  GET /api/dcim/front-ports/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/front-ports/{id}/paths/",
        params=params,
        response_def="FrontPort",
    )


@tool
def netbox_dcim_get_api_dcim_interface_templates(params: dict | None = None) -> dict:
    """dcim_interface_templates_list

    Service: netbox  |  GET /api/dcim/interface-templates/
    Query params: bridge_id(), bridge_id__n(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/interface-templates/",
        params=params,
        response_def="PaginatedInterfaceTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_interface_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_interface_templates_retrieve

    Service: netbox  |  GET /api/dcim/interface-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/interface-templates/{id}/",
        params=params,
        response_def="InterfaceTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_interfaces(params: dict | None = None) -> dict:
    """dcim_interfaces_list

    Service: netbox  |  GET /api/dcim/interfaces/
    Query params: bridge_id(), bridge_id__n(), cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/interfaces/",
        params=params,
        response_def="PaginatedInterfaceList",
    )


@tool
def netbox_dcim_get_api_dcim_interfaces_by_id(id, params: dict | None = None) -> dict:
    """dcim_interfaces_retrieve

    Service: netbox  |  GET /api/dcim/interfaces/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/interfaces/{id}/",
        params=params,
        response_def="Interface",
    )


@tool
def netbox_dcim_get_api_dcim_interfaces_by_id_trace(id, params: dict | None = None) -> dict:
    """dcim_interfaces_trace_retrieve

    Service: netbox  |  GET /api/dcim/interfaces/{id}/trace/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/interfaces/{id}/trace/",
        params=params,
        response_def="Interface",
    )


@tool
def netbox_dcim_get_api_dcim_inventory_item_roles(params: dict | None = None) -> dict:
    """dcim_inventory_item_roles_list

    Service: netbox  |  GET /api/dcim/inventory-item-roles/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/inventory-item-roles/",
        params=params,
        response_def="PaginatedInventoryItemRoleList",
    )


@tool
def netbox_dcim_get_api_dcim_inventory_item_roles_by_id(id, params: dict | None = None) -> dict:
    """dcim_inventory_item_roles_retrieve

    Service: netbox  |  GET /api/dcim/inventory-item-roles/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/inventory-item-roles/{id}/",
        params=params,
        response_def="InventoryItemRole",
    )


@tool
def netbox_dcim_get_api_dcim_inventory_item_templates(params: dict | None = None) -> dict:
    """dcim_inventory_item_templates_list

    Service: netbox  |  GET /api/dcim/inventory-item-templates/
    Query params: component_id(), component_id__empty(), component_id__gt(), component_id__gte(), component_id__lt(), component_id__lte(), component_id__n(), component_type(), component_type__n(), created(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/inventory-item-templates/",
        params=params,
        response_def="PaginatedInventoryItemTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_inventory_item_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_inventory_item_templates_retrieve

    Service: netbox  |  GET /api/dcim/inventory-item-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/inventory-item-templates/{id}/",
        params=params,
        response_def="InventoryItemTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_inventory_items(params: dict | None = None) -> dict:
    """dcim_inventory_items_list

    Service: netbox  |  GET /api/dcim/inventory-items/
    Query params: asset_tag(), asset_tag__empty(), asset_tag__ic(), asset_tag__ie(), asset_tag__iew(), asset_tag__iregex(), asset_tag__isw(), asset_tag__n(), asset_tag__nic(), asset_tag__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/inventory-items/",
        params=params,
        response_def="PaginatedInventoryItemList",
    )


@tool
def netbox_dcim_get_api_dcim_inventory_items_by_id(id, params: dict | None = None) -> dict:
    """dcim_inventory_items_retrieve

    Service: netbox  |  GET /api/dcim/inventory-items/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/inventory-items/{id}/",
        params=params,
        response_def="InventoryItem",
    )


@tool
def netbox_dcim_get_api_dcim_locations(params: dict | None = None) -> dict:
    """dcim_locations_list

    Service: netbox  |  GET /api/dcim/locations/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/locations/",
        params=params,
        response_def="PaginatedLocationList",
    )


@tool
def netbox_dcim_get_api_dcim_locations_by_id(id, params: dict | None = None) -> dict:
    """dcim_locations_retrieve

    Service: netbox  |  GET /api/dcim/locations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/locations/{id}/",
        params=params,
        response_def="Location",
    )


@tool
def netbox_dcim_get_api_dcim_mac_addresses(params: dict | None = None) -> dict:
    """dcim_mac_addresses_list

    Service: netbox  |  GET /api/dcim/mac-addresses/
    Query params: assigned(), assigned_object_id(), assigned_object_id__empty(), assigned_object_id__gt(), assigned_object_id__gte(), assigned_object_id__lt(), assigned_object_id__lte(), assigned_object_id__n(), assigned_object_type(), assigned_object_type__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/mac-addresses/",
        params=params,
        response_def="PaginatedMACAddressList",
    )


@tool
def netbox_dcim_get_api_dcim_mac_addresses_by_id(id, params: dict | None = None) -> dict:
    """dcim_mac_addresses_retrieve

    Service: netbox  |  GET /api/dcim/mac-addresses/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/mac-addresses/{id}/",
        params=params,
        response_def="MACAddress",
    )


@tool
def netbox_dcim_get_api_dcim_manufacturers(params: dict | None = None) -> dict:
    """dcim_manufacturers_list

    Service: netbox  |  GET /api/dcim/manufacturers/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/manufacturers/",
        params=params,
        response_def="PaginatedManufacturerList",
    )


@tool
def netbox_dcim_get_api_dcim_manufacturers_by_id(id, params: dict | None = None) -> dict:
    """dcim_manufacturers_retrieve

    Service: netbox  |  GET /api/dcim/manufacturers/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/manufacturers/{id}/",
        params=params,
        response_def="Manufacturer",
    )


@tool
def netbox_dcim_get_api_dcim_module_bay_templates(params: dict | None = None) -> dict:
    """dcim_module_bay_templates_list

    Service: netbox  |  GET /api/dcim/module-bay-templates/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-bay-templates/",
        params=params,
        response_def="PaginatedModuleBayTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_module_bay_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_module_bay_templates_retrieve

    Service: netbox  |  GET /api/dcim/module-bay-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-bay-templates/{id}/",
        params=params,
        response_def="ModuleBayTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_module_bays(params: dict | None = None) -> dict:
    """dcim_module_bays_list

    Service: netbox  |  GET /api/dcim/module-bays/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-bays/",
        params=params,
        response_def="PaginatedModuleBayList",
    )


@tool
def netbox_dcim_get_api_dcim_module_bays_by_id(id, params: dict | None = None) -> dict:
    """dcim_module_bays_retrieve

    Service: netbox  |  GET /api/dcim/module-bays/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-bays/{id}/",
        params=params,
        response_def="ModuleBay",
    )


@tool
def netbox_dcim_get_api_dcim_module_type_profiles(params: dict | None = None) -> dict:
    """dcim_module_type_profiles_list

    Service: netbox  |  GET /api/dcim/module-type-profiles/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-type-profiles/",
        params=params,
        response_def="PaginatedModuleTypeProfileList",
    )


@tool
def netbox_dcim_get_api_dcim_module_type_profiles_by_id(id, params: dict | None = None) -> dict:
    """dcim_module_type_profiles_retrieve

    Service: netbox  |  GET /api/dcim/module-type-profiles/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-type-profiles/{id}/",
        params=params,
        response_def="ModuleTypeProfile",
    )


@tool
def netbox_dcim_get_api_dcim_module_types(params: dict | None = None) -> dict:
    """dcim_module_types_list

    Service: netbox  |  GET /api/dcim/module-types/
    Query params: airflow(), airflow__empty(), airflow__ic(), airflow__ie(), airflow__iew(), airflow__iregex(), airflow__isw(), airflow__n(), airflow__nic(), airflow__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-types/",
        params=params,
        response_def="PaginatedModuleTypeList",
    )


@tool
def netbox_dcim_get_api_dcim_module_types_by_id(id, params: dict | None = None) -> dict:
    """dcim_module_types_retrieve

    Service: netbox  |  GET /api/dcim/module-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/module-types/{id}/",
        params=params,
        response_def="ModuleType",
    )


@tool
def netbox_dcim_get_api_dcim_modules(params: dict | None = None) -> dict:
    """dcim_modules_list

    Service: netbox  |  GET /api/dcim/modules/
    Query params: asset_tag(), asset_tag__empty(), asset_tag__ic(), asset_tag__ie(), asset_tag__iew(), asset_tag__iregex(), asset_tag__isw(), asset_tag__n(), asset_tag__nic(), asset_tag__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/modules/",
        params=params,
        response_def="PaginatedModuleList",
    )


@tool
def netbox_dcim_get_api_dcim_modules_by_id(id, params: dict | None = None) -> dict:
    """dcim_modules_retrieve

    Service: netbox  |  GET /api/dcim/modules/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/modules/{id}/",
        params=params,
        response_def="Module",
    )


@tool
def netbox_dcim_get_api_dcim_platforms(params: dict | None = None) -> dict:
    """dcim_platforms_list

    Service: netbox  |  GET /api/dcim/platforms/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), available_for_device_type(), config_template_id(), config_template_id__n(), created(), created__empty(), created__gt(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/platforms/",
        params=params,
        response_def="PaginatedPlatformList",
    )


@tool
def netbox_dcim_get_api_dcim_platforms_by_id(id, params: dict | None = None) -> dict:
    """dcim_platforms_retrieve

    Service: netbox  |  GET /api/dcim/platforms/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/platforms/{id}/",
        params=params,
        response_def="Platform",
    )


@tool
def netbox_dcim_get_api_dcim_power_feeds(params: dict | None = None) -> dict:
    """dcim_power_feeds_list

    Service: netbox  |  GET /api/dcim/power-feeds/
    Query params: amperage(), amperage__empty(), amperage__gt(), amperage__gte(), amperage__lt(), amperage__lte(), amperage__n(), available_power(), available_power__empty(), available_power__gt(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-feeds/",
        params=params,
        response_def="PaginatedPowerFeedList",
    )


@tool
def netbox_dcim_get_api_dcim_power_feeds_by_id(id, params: dict | None = None) -> dict:
    """dcim_power_feeds_retrieve

    Service: netbox  |  GET /api/dcim/power-feeds/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-feeds/{id}/",
        params=params,
        response_def="PowerFeed",
    )


@tool
def netbox_dcim_get_api_dcim_power_feeds_by_id_trace(id, params: dict | None = None) -> dict:
    """dcim_power_feeds_trace_retrieve

    Service: netbox  |  GET /api/dcim/power-feeds/{id}/trace/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-feeds/{id}/trace/",
        params=params,
        response_def="PowerFeed",
    )


@tool
def netbox_dcim_get_api_dcim_power_outlet_templates(params: dict | None = None) -> dict:
    """dcim_power_outlet_templates_list

    Service: netbox  |  GET /api/dcim/power-outlet-templates/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-outlet-templates/",
        params=params,
        response_def="PaginatedPowerOutletTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_power_outlet_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_power_outlet_templates_retrieve

    Service: netbox  |  GET /api/dcim/power-outlet-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-outlet-templates/{id}/",
        params=params,
        response_def="PowerOutletTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_power_outlets(params: dict | None = None) -> dict:
    """dcim_power_outlets_list

    Service: netbox  |  GET /api/dcim/power-outlets/
    Query params: cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(), cable_end__empty(), cable_end__ic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-outlets/",
        params=params,
        response_def="PaginatedPowerOutletList",
    )


@tool
def netbox_dcim_get_api_dcim_power_outlets_by_id(id, params: dict | None = None) -> dict:
    """dcim_power_outlets_retrieve

    Service: netbox  |  GET /api/dcim/power-outlets/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-outlets/{id}/",
        params=params,
        response_def="PowerOutlet",
    )


@tool
def netbox_dcim_get_api_dcim_power_outlets_by_id_trace(id, params: dict | None = None) -> dict:
    """dcim_power_outlets_trace_retrieve

    Service: netbox  |  GET /api/dcim/power-outlets/{id}/trace/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-outlets/{id}/trace/",
        params=params,
        response_def="PowerOutlet",
    )


@tool
def netbox_dcim_get_api_dcim_power_panels(params: dict | None = None) -> dict:
    """dcim_power_panels_list

    Service: netbox  |  GET /api/dcim/power-panels/
    Query params: contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(), created(), created__empty(), created__gt(), created__gte(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-panels/",
        params=params,
        response_def="PaginatedPowerPanelList",
    )


@tool
def netbox_dcim_get_api_dcim_power_panels_by_id(id, params: dict | None = None) -> dict:
    """dcim_power_panels_retrieve

    Service: netbox  |  GET /api/dcim/power-panels/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-panels/{id}/",
        params=params,
        response_def="PowerPanel",
    )


@tool
def netbox_dcim_get_api_dcim_power_port_templates(params: dict | None = None) -> dict:
    """dcim_power_port_templates_list

    Service: netbox  |  GET /api/dcim/power-port-templates/
    Query params: allocated_draw(), allocated_draw__empty(), allocated_draw__gt(), allocated_draw__gte(), allocated_draw__lt(), allocated_draw__lte(), allocated_draw__n(), created(), created__empty(), created__gt(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-port-templates/",
        params=params,
        response_def="PaginatedPowerPortTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_power_port_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_power_port_templates_retrieve

    Service: netbox  |  GET /api/dcim/power-port-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-port-templates/{id}/",
        params=params,
        response_def="PowerPortTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_power_ports(params: dict | None = None) -> dict:
    """dcim_power_ports_list

    Service: netbox  |  GET /api/dcim/power-ports/
    Query params: allocated_draw(), allocated_draw__empty(), allocated_draw__gt(), allocated_draw__gte(), allocated_draw__lt(), allocated_draw__lte(), allocated_draw__n(), cable_connector(), cable_connector__empty(), cable_connector__gt(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-ports/",
        params=params,
        response_def="PaginatedPowerPortList",
    )


@tool
def netbox_dcim_get_api_dcim_power_ports_by_id(id, params: dict | None = None) -> dict:
    """dcim_power_ports_retrieve

    Service: netbox  |  GET /api/dcim/power-ports/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-ports/{id}/",
        params=params,
        response_def="PowerPort",
    )


@tool
def netbox_dcim_get_api_dcim_power_ports_by_id_trace(id, params: dict | None = None) -> dict:
    """dcim_power_ports_trace_retrieve

    Service: netbox  |  GET /api/dcim/power-ports/{id}/trace/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/power-ports/{id}/trace/",
        params=params,
        response_def="PowerPort",
    )


@tool
def netbox_dcim_get_api_dcim_rack_reservations(params: dict | None = None) -> dict:
    """dcim_rack_reservations_list

    Service: netbox  |  GET /api/dcim/rack-reservations/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rack-reservations/",
        params=params,
        response_def="PaginatedRackReservationList",
    )


@tool
def netbox_dcim_get_api_dcim_rack_reservations_by_id(id, params: dict | None = None) -> dict:
    """dcim_rack_reservations_retrieve

    Service: netbox  |  GET /api/dcim/rack-reservations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rack-reservations/{id}/",
        params=params,
        response_def="RackReservation",
    )


@tool
def netbox_dcim_get_api_dcim_rack_roles(params: dict | None = None) -> dict:
    """dcim_rack_roles_list

    Service: netbox  |  GET /api/dcim/rack-roles/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rack-roles/",
        params=params,
        response_def="PaginatedRackRoleList",
    )


@tool
def netbox_dcim_get_api_dcim_rack_roles_by_id(id, params: dict | None = None) -> dict:
    """dcim_rack_roles_retrieve

    Service: netbox  |  GET /api/dcim/rack-roles/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rack-roles/{id}/",
        params=params,
        response_def="RackRole",
    )


@tool
def netbox_dcim_get_api_dcim_rack_types(params: dict | None = None) -> dict:
    """dcim_rack_types_list

    Service: netbox  |  GET /api/dcim/rack-types/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), desc_units(), description(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rack-types/",
        params=params,
        response_def="PaginatedRackTypeList",
    )


@tool
def netbox_dcim_get_api_dcim_rack_types_by_id(id, params: dict | None = None) -> dict:
    """dcim_rack_types_retrieve

    Service: netbox  |  GET /api/dcim/rack-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rack-types/{id}/",
        params=params,
        response_def="RackType",
    )


@tool
def netbox_dcim_get_api_dcim_racks(params: dict | None = None) -> dict:
    """dcim_racks_list

    Service: netbox  |  GET /api/dcim/racks/
    Query params: airflow(), airflow__empty(), airflow__ic(), airflow__ie(), airflow__iew(), airflow__iregex(), airflow__isw(), airflow__n(), airflow__nic(), airflow__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/racks/",
        params=params,
        response_def="PaginatedRackList",
    )


@tool
def netbox_dcim_get_api_dcim_racks_by_id(id, params: dict | None = None) -> dict:
    """dcim_racks_retrieve

    Service: netbox  |  GET /api/dcim/racks/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/racks/{id}/",
        params=params,
        response_def="Rack",
    )


@tool
def netbox_dcim_get_api_dcim_racks_by_id_elevation(id, params: dict | None = None) -> dict:
    """dcim_racks_elevation_retrieve

    Service: netbox  |  GET /api/dcim/racks/{id}/elevation/
    Query params: exclude(), expand_devices(), face(), include_images(), legend_width(), limit(), margin_width(), offset(), q(), render(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/racks/{id}/elevation/",
        params=params,
        response_def="PaginatedRackUnitList",
    )


@tool
def netbox_dcim_get_api_dcim_rear_port_templates(params: dict | None = None) -> dict:
    """dcim_rear_port_templates_list

    Service: netbox  |  GET /api/dcim/rear-port-templates/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rear-port-templates/",
        params=params,
        response_def="PaginatedRearPortTemplateList",
    )


@tool
def netbox_dcim_get_api_dcim_rear_port_templates_by_id(id, params: dict | None = None) -> dict:
    """dcim_rear_port_templates_retrieve

    Service: netbox  |  GET /api/dcim/rear-port-templates/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rear-port-templates/{id}/",
        params=params,
        response_def="RearPortTemplate",
    )


@tool
def netbox_dcim_get_api_dcim_rear_ports(params: dict | None = None) -> dict:
    """dcim_rear_ports_list

    Service: netbox  |  GET /api/dcim/rear-ports/
    Query params: cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(), cable_end__empty(), cable_end__ic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rear-ports/",
        params=params,
        response_def="PaginatedRearPortList",
    )


@tool
def netbox_dcim_get_api_dcim_rear_ports_by_id(id, params: dict | None = None) -> dict:
    """dcim_rear_ports_retrieve

    Service: netbox  |  GET /api/dcim/rear-ports/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rear-ports/{id}/",
        params=params,
        response_def="RearPort",
    )


@tool
def netbox_dcim_get_api_dcim_rear_ports_by_id_paths(id, params: dict | None = None) -> dict:
    """dcim_rear_ports_paths_retrieve

    Service: netbox  |  GET /api/dcim/rear-ports/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/rear-ports/{id}/paths/",
        params=params,
        response_def="RearPort",
    )


@tool
def netbox_dcim_get_api_dcim_regions(params: dict | None = None) -> dict:
    """dcim_regions_list

    Service: netbox  |  GET /api/dcim/regions/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/regions/",
        params=params,
        response_def="PaginatedRegionList",
    )


@tool
def netbox_dcim_get_api_dcim_regions_by_id(id, params: dict | None = None) -> dict:
    """dcim_regions_retrieve

    Service: netbox  |  GET /api/dcim/regions/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/regions/{id}/",
        params=params,
        response_def="Region",
    )


@tool
def netbox_dcim_get_api_dcim_site_groups(params: dict | None = None) -> dict:
    """dcim_site_groups_list

    Service: netbox  |  GET /api/dcim/site-groups/
    Query params: ancestor(), ancestor__n(), ancestor_id(), ancestor_id__n(), contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/site-groups/",
        params=params,
        response_def="PaginatedSiteGroupList",
    )


@tool
def netbox_dcim_get_api_dcim_site_groups_by_id(id, params: dict | None = None) -> dict:
    """dcim_site_groups_retrieve

    Service: netbox  |  GET /api/dcim/site-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/site-groups/{id}/",
        params=params,
        response_def="SiteGroup",
    )


@tool
def netbox_dcim_get_api_dcim_sites(params: dict | None = None) -> dict:
    """dcim_sites_list

    Service: netbox  |  GET /api/dcim/sites/
    Query params: asn(), asn__n(), asn_id(), asn_id__n(), contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/sites/",
        params=params,
        response_def="PaginatedSiteList",
    )


@tool
def netbox_dcim_get_api_dcim_sites_by_id(id, params: dict | None = None) -> dict:
    """dcim_sites_retrieve

    Service: netbox  |  GET /api/dcim/sites/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/sites/{id}/",
        params=params,
        response_def="Site",
    )


@tool
def netbox_dcim_get_api_dcim_virtual_chassis(params: dict | None = None) -> dict:
    """dcim_virtual_chassis_list

    Service: netbox  |  GET /api/dcim/virtual-chassis/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/virtual-chassis/",
        params=params,
        response_def="PaginatedVirtualChassisList",
    )


@tool
def netbox_dcim_get_api_dcim_virtual_chassis_by_id(id, params: dict | None = None) -> dict:
    """dcim_virtual_chassis_retrieve

    Service: netbox  |  GET /api/dcim/virtual-chassis/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/virtual-chassis/{id}/",
        params=params,
        response_def="VirtualChassis",
    )


@tool
def netbox_dcim_get_api_dcim_virtual_device_contexts(params: dict | None = None) -> dict:
    """dcim_virtual_device_contexts_list

    Service: netbox  |  GET /api/dcim/virtual-device-contexts/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/virtual-device-contexts/",
        params=params,
        response_def="PaginatedVirtualDeviceContextList",
    )


@tool
def netbox_dcim_get_api_dcim_virtual_device_contexts_by_id(id, params: dict | None = None) -> dict:
    """dcim_virtual_device_contexts_retrieve

    Service: netbox  |  GET /api/dcim/virtual-device-contexts/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/dcim/virtual-device-contexts/{id}/",
        params=params,
        response_def="VirtualDeviceContext",
    )

