"""Auto-generated tool: NetBox DCIM/IPAM — Circuits, providers, terminations

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: circuits
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def netbox_circuits_get_api_circuits_circuit_group_assignments(params: dict | None = None) -> dict:
    """circuits_circuit_group_assignments_list

    Service: netbox  |  GET /api/circuits/circuit-group-assignments/
    Query params: circuit(), circuit_id(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-group-assignments/",
        params=params,
        response_def="PaginatedCircuitGroupAssignmentList",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_group_assignments_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_group_assignments_retrieve

    Service: netbox  |  GET /api/circuits/circuit-group-assignments/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-group-assignments/{id}/",
        params=params,
        response_def="CircuitGroupAssignment",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_groups(params: dict | None = None) -> dict:
    """circuits_circuit_groups_list

    Service: netbox  |  GET /api/circuits/circuit-groups/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-groups/",
        params=params,
        response_def="PaginatedCircuitGroupList",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_groups_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_groups_retrieve

    Service: netbox  |  GET /api/circuits/circuit-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-groups/{id}/",
        params=params,
        response_def="CircuitGroup",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_terminations(params: dict | None = None) -> dict:
    """circuits_circuit_terminations_list

    Service: netbox  |  GET /api/circuits/circuit-terminations/
    Query params: cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(), cable_end__empty(), cable_end__ic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/",
        params=params,
        response_def="PaginatedCircuitTerminationList",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_terminations_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_terminations_retrieve

    Service: netbox  |  GET /api/circuits/circuit-terminations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/{id}/",
        params=params,
        response_def="CircuitTermination",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_terminations_by_id_paths(id, params: dict | None = None) -> dict:
    """circuits_circuit_terminations_paths_retrieve

    Service: netbox  |  GET /api/circuits/circuit-terminations/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/{id}/paths/",
        params=params,
        response_def="CircuitTermination",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_types(params: dict | None = None) -> dict:
    """circuits_circuit_types_list

    Service: netbox  |  GET /api/circuits/circuit-types/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-types/",
        params=params,
        response_def="PaginatedCircuitTypeList",
    )


@tool
def netbox_circuits_get_api_circuits_circuit_types_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_types_retrieve

    Service: netbox  |  GET /api/circuits/circuit-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-types/{id}/",
        params=params,
        response_def="CircuitType",
    )


@tool
def netbox_circuits_get_api_circuits_circuits(params: dict | None = None) -> dict:
    """circuits_circuits_list

    Service: netbox  |  GET /api/circuits/circuits/
    Query params: cid(), cid__empty(), cid__ic(), cid__ie(), cid__iew(), cid__iregex(), cid__isw(), cid__n(), cid__nic(), cid__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuits/",
        params=params,
        response_def="PaginatedCircuitList",
    )


@tool
def netbox_circuits_get_api_circuits_circuits_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuits_retrieve

    Service: netbox  |  GET /api/circuits/circuits/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuits/{id}/",
        params=params,
        response_def="Circuit",
    )


@tool
def netbox_circuits_get_api_circuits_provider_accounts(params: dict | None = None) -> dict:
    """circuits_provider_accounts_list

    Service: netbox  |  GET /api/circuits/provider-accounts/
    Query params: account(), account__empty(), account__ic(), account__ie(), account__iew(), account__iregex(), account__isw(), account__n(), account__nic(), account__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-accounts/",
        params=params,
        response_def="PaginatedProviderAccountList",
    )


@tool
def netbox_circuits_get_api_circuits_provider_accounts_by_id(id, params: dict | None = None) -> dict:
    """circuits_provider_accounts_retrieve

    Service: netbox  |  GET /api/circuits/provider-accounts/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-accounts/{id}/",
        params=params,
        response_def="ProviderAccount",
    )


@tool
def netbox_circuits_get_api_circuits_provider_networks(params: dict | None = None) -> dict:
    """circuits_provider_networks_list

    Service: netbox  |  GET /api/circuits/provider-networks/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-networks/",
        params=params,
        response_def="PaginatedProviderNetworkList",
    )


@tool
def netbox_circuits_get_api_circuits_provider_networks_by_id(id, params: dict | None = None) -> dict:
    """circuits_provider_networks_retrieve

    Service: netbox  |  GET /api/circuits/provider-networks/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-networks/{id}/",
        params=params,
        response_def="ProviderNetwork",
    )


@tool
def netbox_circuits_get_api_circuits_providers(params: dict | None = None) -> dict:
    """circuits_providers_list

    Service: netbox  |  GET /api/circuits/providers/
    Query params: asn(), asn__n(), asn_id(), asn_id__n(), contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/providers/",
        params=params,
        response_def="PaginatedProviderList",
    )


@tool
def netbox_circuits_get_api_circuits_providers_by_id(id, params: dict | None = None) -> dict:
    """circuits_providers_retrieve

    Service: netbox  |  GET /api/circuits/providers/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/providers/{id}/",
        params=params,
        response_def="Provider",
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_terminations(params: dict | None = None) -> dict:
    """circuits_virtual_circuit_terminations_list

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/",
        params=params,
        response_def="PaginatedVirtualCircuitTerminationList",
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_terminations_by_id(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuit_terminations_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/{id}/",
        params=params,
        response_def="VirtualCircuitTermination",
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_terminations_by_id_paths(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuit_terminations_paths_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/{id}/paths/",
        params=params,
        response_def="VirtualCircuitTermination",
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_types(params: dict | None = None) -> dict:
    """circuits_virtual_circuit_types_list

    Service: netbox  |  GET /api/circuits/virtual-circuit-types/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-types/",
        params=params,
        response_def="PaginatedVirtualCircuitTypeList",
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_types_by_id(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuit_types_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-types/{id}/",
        params=params,
        response_def="VirtualCircuitType",
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuits(params: dict | None = None) -> dict:
    """circuits_virtual_circuits_list

    Service: netbox  |  GET /api/circuits/virtual-circuits/
    Query params: cid(), cid__empty(), cid__ic(), cid__ie(), cid__iew(), cid__iregex(), cid__isw(), cid__n(), cid__nic(), cid__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuits/",
        params=params,
        response_def="PaginatedVirtualCircuitList",
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuits_by_id(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuits_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuits/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuits/{id}/",
        params=params,
        response_def="VirtualCircuit",
    )

