"""Auto-generated tool: NetBox — Circuits and circuit types

Generated by olav.platform.services.tool_generator
Service: netbox
Tag group: circuits
DO NOT EDIT MANUALLY — re-run `olav service register netbox` to update.
"""

from __future__ import annotations

from langchain_core.tools import tool

from olav.platform.services.client import service_call as _call


@tool
def netbox_circuits_delete_api_circuits_circuit_group_assignments(confirmed: bool = False) -> dict:
    """circuits_circuit_group_assignments_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-group-assignments/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_group_assignments(params: dict | None = None) -> dict:
    """circuits_circuit_group_assignments_list

    Service: netbox  |  GET /api/circuits/circuit-group-assignments/
    Query params: circuit(), circuit_id(), created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-group-assignments/",
        params=params,
        response_def="PaginatedCircuitGroupAssignmentList",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_group_assignments(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_group_assignments_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-group-assignments/",
        body=body,
        response_def="CircuitGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_circuit_group_assignments(confirmed: bool = False) -> dict:
    """circuits_circuit_group_assignments_create

    Service: netbox  |  POST /api/circuits/circuit-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/circuit-group-assignments/",
        response_def="CircuitGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_group_assignments(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_group_assignments_bulk_update

    Service: netbox  |  PUT /api/circuits/circuit-group-assignments/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-group-assignments/",
        body=body,
        response_def="CircuitGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuit_group_assignments_by_id(id, confirmed: bool = False) -> dict:
    """circuits_circuit_group_assignments_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-group-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-group-assignments/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_group_assignments_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_group_assignments_retrieve

    Service: netbox  |  GET /api/circuits/circuit-group-assignments/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-group-assignments/{id}/",
        params=params,
        response_def="CircuitGroupAssignment",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_group_assignments_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_group_assignments_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-group-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-group-assignments/{id}/",
        body=body,
        response_def="CircuitGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_group_assignments_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_group_assignments_update

    Service: netbox  |  PUT /api/circuits/circuit-group-assignments/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-group-assignments/{id}/",
        body=body,
        response_def="CircuitGroupAssignment",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuit_groups(confirmed: bool = False) -> dict:
    """circuits_circuit_groups_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-groups/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_groups(params: dict | None = None) -> dict:
    """circuits_circuit_groups_list

    Service: netbox  |  GET /api/circuits/circuit-groups/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-groups/",
        params=params,
        response_def="PaginatedCircuitGroupList",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_groups_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-groups/",
        body=body,
        response_def="CircuitGroup",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_circuit_groups(confirmed: bool = False) -> dict:
    """circuits_circuit_groups_create

    Service: netbox  |  POST /api/circuits/circuit-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/circuit-groups/",
        response_def="CircuitGroup",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_groups(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_groups_bulk_update

    Service: netbox  |  PUT /api/circuits/circuit-groups/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-groups/",
        body=body,
        response_def="CircuitGroup",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuit_groups_by_id(id, confirmed: bool = False) -> dict:
    """circuits_circuit_groups_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-groups/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_groups_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_groups_retrieve

    Service: netbox  |  GET /api/circuits/circuit-groups/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-groups/{id}/",
        params=params,
        response_def="CircuitGroup",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_groups_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-groups/{id}/",
        body=body,
        response_def="CircuitGroup",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_groups_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_groups_update

    Service: netbox  |  PUT /api/circuits/circuit-groups/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-groups/{id}/",
        body=body,
        response_def="CircuitGroup",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuit_terminations(confirmed: bool = False) -> dict:
    """circuits_circuit_terminations_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-terminations/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_terminations(params: dict | None = None) -> dict:
    """circuits_circuit_terminations_list

    Service: netbox  |  GET /api/circuits/circuit-terminations/
    Query params: cable_connector(), cable_connector__empty(), cable_connector__gt(), cable_connector__gte(), cable_connector__lt(), cable_connector__lte(), cable_connector__n(), cable_end(), cable_end__empty(), cable_end__ic(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/",
        params=params,
        response_def="PaginatedCircuitTerminationList",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_terminations(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_terminations_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-terminations/",
        body=body,
        response_def="CircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_circuit_terminations(confirmed: bool = False) -> dict:
    """circuits_circuit_terminations_create

    Service: netbox  |  POST /api/circuits/circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/circuit-terminations/",
        response_def="CircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_terminations(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_terminations_bulk_update

    Service: netbox  |  PUT /api/circuits/circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-terminations/",
        body=body,
        response_def="CircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuit_terminations_by_id(id, confirmed: bool = False) -> dict:
    """circuits_circuit_terminations_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-terminations/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-terminations/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_terminations_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_terminations_retrieve

    Service: netbox  |  GET /api/circuits/circuit-terminations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/{id}/",
        params=params,
        response_def="CircuitTermination",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_terminations_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_terminations_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-terminations/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-terminations/{id}/",
        body=body,
        response_def="CircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_terminations_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_terminations_update

    Service: netbox  |  PUT /api/circuits/circuit-terminations/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-terminations/{id}/",
        body=body,
        response_def="CircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_terminations_by_id_paths(id, params: dict | None = None) -> dict:
    """circuits_circuit_terminations_paths_retrieve

    Service: netbox  |  GET /api/circuits/circuit-terminations/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-terminations/{id}/paths/",
        params=params,
        response_def="CircuitTermination",
    )


@tool
def netbox_circuits_delete_api_circuits_circuit_types(confirmed: bool = False) -> dict:
    """circuits_circuit_types_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-types/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_types(params: dict | None = None) -> dict:
    """circuits_circuit_types_list

    Service: netbox  |  GET /api/circuits/circuit-types/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-types/",
        params=params,
        response_def="PaginatedCircuitTypeList",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_types(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_types_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-types/",
        body=body,
        response_def="CircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_circuit_types(confirmed: bool = False) -> dict:
    """circuits_circuit_types_create

    Service: netbox  |  POST /api/circuits/circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/circuit-types/",
        response_def="CircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_types(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_types_bulk_update

    Service: netbox  |  PUT /api/circuits/circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-types/",
        body=body,
        response_def="CircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuit_types_by_id(id, confirmed: bool = False) -> dict:
    """circuits_circuit_types_destroy

    Service: netbox  |  DELETE /api/circuits/circuit-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuit-types/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuit_types_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuit_types_retrieve

    Service: netbox  |  GET /api/circuits/circuit-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuit-types/{id}/",
        params=params,
        response_def="CircuitType",
    )


@tool
def netbox_circuits_patch_api_circuits_circuit_types_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_types_partial_update

    Service: netbox  |  PATCH /api/circuits/circuit-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuit-types/{id}/",
        body=body,
        response_def="CircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuit_types_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuit_types_update

    Service: netbox  |  PUT /api/circuits/circuit-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuit-types/{id}/",
        body=body,
        response_def="CircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuits(confirmed: bool = False) -> dict:
    """circuits_circuits_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuits/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuits(params: dict | None = None) -> dict:
    """circuits_circuits_list

    Service: netbox  |  GET /api/circuits/circuits/
    Query params: cid(), cid__empty(), cid__ic(), cid__ie(), cid__iew(), cid__iregex(), cid__isw(), cid__n(), cid__nic(), cid__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuits/",
        params=params,
        response_def="PaginatedCircuitList",
    )


@tool
def netbox_circuits_patch_api_circuits_circuits(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuits_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuits/",
        body=body,
        response_def="Circuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_circuits(confirmed: bool = False) -> dict:
    """circuits_circuits_create

    Service: netbox  |  POST /api/circuits/circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/circuits/",
        response_def="Circuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuits(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuits_bulk_update

    Service: netbox  |  PUT /api/circuits/circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuits/",
        body=body,
        response_def="Circuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_circuits_by_id(id, confirmed: bool = False) -> dict:
    """circuits_circuits_destroy

    Service: netbox  |  DELETE /api/circuits/circuits/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/circuits/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_circuits_by_id(id, params: dict | None = None) -> dict:
    """circuits_circuits_retrieve

    Service: netbox  |  GET /api/circuits/circuits/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/circuits/{id}/",
        params=params,
        response_def="Circuit",
    )


@tool
def netbox_circuits_patch_api_circuits_circuits_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuits_partial_update

    Service: netbox  |  PATCH /api/circuits/circuits/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/circuits/{id}/",
        body=body,
        response_def="Circuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_circuits_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_circuits_update

    Service: netbox  |  PUT /api/circuits/circuits/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/circuits/{id}/",
        body=body,
        response_def="Circuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_provider_accounts(confirmed: bool = False) -> dict:
    """circuits_provider_accounts_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/provider-accounts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/provider-accounts/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_provider_accounts(params: dict | None = None) -> dict:
    """circuits_provider_accounts_list

    Service: netbox  |  GET /api/circuits/provider-accounts/
    Query params: account(), account__empty(), account__ic(), account__ie(), account__iew(), account__iregex(), account__isw(), account__n(), account__nic(), account__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-accounts/",
        params=params,
        response_def="PaginatedProviderAccountList",
    )


@tool
def netbox_circuits_patch_api_circuits_provider_accounts(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_accounts_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/provider-accounts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/provider-accounts/",
        body=body,
        response_def="ProviderAccount",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_provider_accounts(confirmed: bool = False) -> dict:
    """circuits_provider_accounts_create

    Service: netbox  |  POST /api/circuits/provider-accounts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/provider-accounts/",
        response_def="ProviderAccount",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_provider_accounts(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_accounts_bulk_update

    Service: netbox  |  PUT /api/circuits/provider-accounts/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/provider-accounts/",
        body=body,
        response_def="ProviderAccount",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_provider_accounts_by_id(id, confirmed: bool = False) -> dict:
    """circuits_provider_accounts_destroy

    Service: netbox  |  DELETE /api/circuits/provider-accounts/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/provider-accounts/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_provider_accounts_by_id(id, params: dict | None = None) -> dict:
    """circuits_provider_accounts_retrieve

    Service: netbox  |  GET /api/circuits/provider-accounts/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-accounts/{id}/",
        params=params,
        response_def="ProviderAccount",
    )


@tool
def netbox_circuits_patch_api_circuits_provider_accounts_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_accounts_partial_update

    Service: netbox  |  PATCH /api/circuits/provider-accounts/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/provider-accounts/{id}/",
        body=body,
        response_def="ProviderAccount",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_provider_accounts_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_accounts_update

    Service: netbox  |  PUT /api/circuits/provider-accounts/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/provider-accounts/{id}/",
        body=body,
        response_def="ProviderAccount",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_provider_networks(confirmed: bool = False) -> dict:
    """circuits_provider_networks_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/provider-networks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/provider-networks/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_provider_networks(params: dict | None = None) -> dict:
    """circuits_provider_networks_list

    Service: netbox  |  GET /api/circuits/provider-networks/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-networks/",
        params=params,
        response_def="PaginatedProviderNetworkList",
    )


@tool
def netbox_circuits_patch_api_circuits_provider_networks(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_networks_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/provider-networks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/provider-networks/",
        body=body,
        response_def="ProviderNetwork",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_provider_networks(confirmed: bool = False) -> dict:
    """circuits_provider_networks_create

    Service: netbox  |  POST /api/circuits/provider-networks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/provider-networks/",
        response_def="ProviderNetwork",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_provider_networks(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_networks_bulk_update

    Service: netbox  |  PUT /api/circuits/provider-networks/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/provider-networks/",
        body=body,
        response_def="ProviderNetwork",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_provider_networks_by_id(id, confirmed: bool = False) -> dict:
    """circuits_provider_networks_destroy

    Service: netbox  |  DELETE /api/circuits/provider-networks/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/provider-networks/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_provider_networks_by_id(id, params: dict | None = None) -> dict:
    """circuits_provider_networks_retrieve

    Service: netbox  |  GET /api/circuits/provider-networks/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/provider-networks/{id}/",
        params=params,
        response_def="ProviderNetwork",
    )


@tool
def netbox_circuits_patch_api_circuits_provider_networks_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_networks_partial_update

    Service: netbox  |  PATCH /api/circuits/provider-networks/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/provider-networks/{id}/",
        body=body,
        response_def="ProviderNetwork",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_provider_networks_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_provider_networks_update

    Service: netbox  |  PUT /api/circuits/provider-networks/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/provider-networks/{id}/",
        body=body,
        response_def="ProviderNetwork",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_providers(confirmed: bool = False) -> dict:
    """circuits_providers_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/providers/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/providers/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_providers(params: dict | None = None) -> dict:
    """circuits_providers_list

    Service: netbox  |  GET /api/circuits/providers/
    Query params: asn(), asn__n(), asn_id(), asn_id__n(), contact(), contact__n(), contact_group(), contact_group__n(), contact_role(), contact_role__n(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/providers/",
        params=params,
        response_def="PaginatedProviderList",
    )


@tool
def netbox_circuits_patch_api_circuits_providers(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_providers_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/providers/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/providers/",
        body=body,
        response_def="Provider",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_providers(confirmed: bool = False) -> dict:
    """circuits_providers_create

    Service: netbox  |  POST /api/circuits/providers/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/providers/",
        response_def="Provider",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_providers(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_providers_bulk_update

    Service: netbox  |  PUT /api/circuits/providers/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/providers/",
        body=body,
        response_def="Provider",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_providers_by_id(id, confirmed: bool = False) -> dict:
    """circuits_providers_destroy

    Service: netbox  |  DELETE /api/circuits/providers/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/providers/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_providers_by_id(id, params: dict | None = None) -> dict:
    """circuits_providers_retrieve

    Service: netbox  |  GET /api/circuits/providers/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/providers/{id}/",
        params=params,
        response_def="Provider",
    )


@tool
def netbox_circuits_patch_api_circuits_providers_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_providers_partial_update

    Service: netbox  |  PATCH /api/circuits/providers/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/providers/{id}/",
        body=body,
        response_def="Provider",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_providers_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_providers_update

    Service: netbox  |  PUT /api/circuits/providers/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/providers/{id}/",
        body=body,
        response_def="Provider",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_virtual_circuit_terminations(confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_terminations_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/virtual-circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/virtual-circuit-terminations/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_terminations(params: dict | None = None) -> dict:
    """circuits_virtual_circuit_terminations_list

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/
    Query params: created(), created__empty(), created__gt(), created__gte(), created__lt(), created__lte(), created__n(), created_by_request(), description(), description__empty(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/",
        params=params,
        response_def="PaginatedVirtualCircuitTerminationList",
    )


@tool
def netbox_circuits_patch_api_circuits_virtual_circuit_terminations(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_terminations_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/virtual-circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/virtual-circuit-terminations/",
        body=body,
        response_def="VirtualCircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_virtual_circuit_terminations(confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_terminations_create

    Service: netbox  |  POST /api/circuits/virtual-circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/virtual-circuit-terminations/",
        response_def="VirtualCircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_virtual_circuit_terminations(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_terminations_bulk_update

    Service: netbox  |  PUT /api/circuits/virtual-circuit-terminations/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/virtual-circuit-terminations/",
        body=body,
        response_def="VirtualCircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_virtual_circuit_terminations_by_id(id, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_terminations_destroy

    Service: netbox  |  DELETE /api/circuits/virtual-circuit-terminations/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/virtual-circuit-terminations/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_terminations_by_id(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuit_terminations_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/{id}/",
        params=params,
        response_def="VirtualCircuitTermination",
    )


@tool
def netbox_circuits_patch_api_circuits_virtual_circuit_terminations_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_terminations_partial_update

    Service: netbox  |  PATCH /api/circuits/virtual-circuit-terminations/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/virtual-circuit-terminations/{id}/",
        body=body,
        response_def="VirtualCircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_virtual_circuit_terminations_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_terminations_update

    Service: netbox  |  PUT /api/circuits/virtual-circuit-terminations/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/virtual-circuit-terminations/{id}/",
        body=body,
        response_def="VirtualCircuitTermination",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_terminations_by_id_paths(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuit_terminations_paths_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-terminations/{id}/paths/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-terminations/{id}/paths/",
        params=params,
        response_def="VirtualCircuitTermination",
    )


@tool
def netbox_circuits_delete_api_circuits_virtual_circuit_types(confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_types_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/virtual-circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/virtual-circuit-types/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_types(params: dict | None = None) -> dict:
    """circuits_virtual_circuit_types_list

    Service: netbox  |  GET /api/circuits/virtual-circuit-types/
    Query params: color(), color__empty(), color__ic(), color__ie(), color__iew(), color__iregex(), color__isw(), color__n(), color__nic(), color__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-types/",
        params=params,
        response_def="PaginatedVirtualCircuitTypeList",
    )


@tool
def netbox_circuits_patch_api_circuits_virtual_circuit_types(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_types_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/virtual-circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/virtual-circuit-types/",
        body=body,
        response_def="VirtualCircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_virtual_circuit_types(confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_types_create

    Service: netbox  |  POST /api/circuits/virtual-circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/virtual-circuit-types/",
        response_def="VirtualCircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_virtual_circuit_types(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_types_bulk_update

    Service: netbox  |  PUT /api/circuits/virtual-circuit-types/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/virtual-circuit-types/",
        body=body,
        response_def="VirtualCircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_virtual_circuit_types_by_id(id, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_types_destroy

    Service: netbox  |  DELETE /api/circuits/virtual-circuit-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/virtual-circuit-types/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuit_types_by_id(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuit_types_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuit-types/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuit-types/{id}/",
        params=params,
        response_def="VirtualCircuitType",
    )


@tool
def netbox_circuits_patch_api_circuits_virtual_circuit_types_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_types_partial_update

    Service: netbox  |  PATCH /api/circuits/virtual-circuit-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/virtual-circuit-types/{id}/",
        body=body,
        response_def="VirtualCircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_virtual_circuit_types_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuit_types_update

    Service: netbox  |  PUT /api/circuits/virtual-circuit-types/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/virtual-circuit-types/{id}/",
        body=body,
        response_def="VirtualCircuitType",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_virtual_circuits(confirmed: bool = False) -> dict:
    """circuits_virtual_circuits_bulk_destroy

    Service: netbox  |  DELETE /api/circuits/virtual-circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/virtual-circuits/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuits(params: dict | None = None) -> dict:
    """circuits_virtual_circuits_list

    Service: netbox  |  GET /api/circuits/virtual-circuits/
    Query params: cid(), cid__empty(), cid__ic(), cid__ie(), cid__iew(), cid__iregex(), cid__isw(), cid__n(), cid__nic(), cid__nie(). Pass as params={'key': 'value'}.
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuits/",
        params=params,
        response_def="PaginatedVirtualCircuitList",
    )


@tool
def netbox_circuits_patch_api_circuits_virtual_circuits(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuits_bulk_partial_update

    Service: netbox  |  PATCH /api/circuits/virtual-circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/virtual-circuits/",
        body=body,
        response_def="VirtualCircuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_post_api_circuits_virtual_circuits(confirmed: bool = False) -> dict:
    """circuits_virtual_circuits_create

    Service: netbox  |  POST /api/circuits/virtual-circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "POST",
        f"/api/circuits/virtual-circuits/",
        response_def="VirtualCircuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_virtual_circuits(body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuits_bulk_update

    Service: netbox  |  PUT /api/circuits/virtual-circuits/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/virtual-circuits/",
        body=body,
        response_def="VirtualCircuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_delete_api_circuits_virtual_circuits_by_id(id, confirmed: bool = False) -> dict:
    """circuits_virtual_circuits_destroy

    Service: netbox  |  DELETE /api/circuits/virtual-circuits/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "DELETE",
        f"/api/circuits/virtual-circuits/{id}/",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_get_api_circuits_virtual_circuits_by_id(id, params: dict | None = None) -> dict:
    """circuits_virtual_circuits_retrieve

    Service: netbox  |  GET /api/circuits/virtual-circuits/{id}/
    """
    return _call(
        "netbox",
        "GET",
        f"/api/circuits/virtual-circuits/{id}/",
        params=params,
        response_def="VirtualCircuit",
    )


@tool
def netbox_circuits_patch_api_circuits_virtual_circuits_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuits_partial_update

    Service: netbox  |  PATCH /api/circuits/virtual-circuits/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PATCH",
        f"/api/circuits/virtual-circuits/{id}/",
        body=body,
        response_def="VirtualCircuit",
        confirmed=confirmed,
    )


@tool
def netbox_circuits_put_api_circuits_virtual_circuits_by_id(id, body: dict | None = None, confirmed: bool = False) -> dict:
    """circuits_virtual_circuits_update

    Service: netbox  |  PUT /api/circuits/virtual-circuits/{id}/
    Write op — first call returns requires_approval; re-call with confirmed=True after user confirms."""
    return _call(
        "netbox",
        "PUT",
        f"/api/circuits/virtual-circuits/{id}/",
        body=body,
        response_def="VirtualCircuit",
        confirmed=confirmed,
    )

