#!/bin/bash
# Daily Network Inspection Script
# Auto-generated by OLAV - Network Operations AI Assistant
# 
# Usage:
#   ./scripts/daily_inspection.sh              # Run now
#   crontab -e                                  # Add to cron
#   0 6 * * * /path/to/daily_inspection.sh     # Every day at 06:00
#
# Logs: .olav/logs/inspection_YYYYMMDD.log
#       .olav/logs/cron.log (when run by cron)

set -e  # Exit on error
set -u  # Exit on undefined variable

# ============================================================================
# Configuration
# ============================================================================

# Project directory (auto-detect)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Workflow name
WORKFLOW="daily-inspection"

# Logs directory
LOG_DIR="$PROJECT_ROOT/.olav/logs"
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
DATE_ONLY=$(date '+%Y%m%d')
LOG_FILE="$LOG_DIR/inspection_${DATE_ONLY}.log"

# Lock file (prevent concurrent execution)
LOCK_FILE="/tmp/olav_inspection.lock"

# Timeout (30 minutes)
TIMEOUT=1800

# Notification settings (optional)
ENABLE_NOTIFICATION=false
WEBHOOK_URL=""  # Slack/Teams webhook URL

# ============================================================================
# Helper Functions
# ============================================================================

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" | tee -a "$LOG_FILE" >&2
}

cleanup() {
    # Remove lock file on exit
    rm -f "$LOCK_FILE"
}

trap cleanup EXIT INT TERM

send_notification() {
    local status="$1"
    local message="$2"
    
    if [ "$ENABLE_NOTIFICATION" = true ] && [ -n "$WEBHOOK_URL" ]; then
        curl -s -X POST "$WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d "{\"text\":\"🤖 OLAV Inspection [$status]: $message\"}" \
            >/dev/null 2>&1 || true
    fi
}

# ============================================================================
# Pre-flight Checks
# ============================================================================

log "========================================"
log "OLAV Daily Inspection"
log "========================================"
log "Project: $PROJECT_ROOT"
log "Workflow: $WORKFLOW"
log "Log: $LOG_FILE"

# Check if already running
if [ -f "$LOCK_FILE" ]; then
    error "Another inspection is already running (lock file exists)"
    error "If this is incorrect, remove: $LOCK_FILE"
    exit 1
fi

# Create lock file
touch "$LOCK_FILE"
echo $$ > "$LOCK_FILE"

# Check if uv is installed
if ! command -v uv &> /dev/null; then
    error "uv is not installed. Please install: curl -LsSf https://astral.sh/uv/install.sh | sh"
    send_notification "FAILED" "uv not installed"
    exit 1
fi

# Check if project exists
if [ ! -d "$PROJECT_ROOT/.olav" ]; then
    error "OLAV directory not found: $PROJECT_ROOT/.olav"
    send_notification "FAILED" ".olav directory not found"
    exit 1
fi

# Create logs directory
mkdir -p "$LOG_DIR"

# ============================================================================
# Execute Workflow
# ============================================================================

log "Starting workflow execution..."

cd "$PROJECT_ROOT"

# Execute with timeout
if timeout "$TIMEOUT" uv run olav inspect "$WORKFLOW" >> "$LOG_FILE" 2>&1; then
    log "✅ Workflow completed successfully"
    
    # Check if report was generated
    REPORT_FILE="$PROJECT_ROOT/exports/reports/snapshots/${DATE_ONLY}.md"
    if [ -f "$REPORT_FILE" ]; then
        log "📊 Report generated: $REPORT_FILE"
        
        # Extract summary from report
        SUMMARY=$(head -20 "$REPORT_FILE" | grep -E "Summary|Healthy|Warning|Critical" | head -3 || echo "Report generated")
        
        send_notification "SUCCESS" "$SUMMARY"
    else
        log "⚠️  Report file not found: $REPORT_FILE"
        send_notification "WARNING" "Workflow completed but report not found"
    fi
    
    exit 0
else
    EXIT_CODE=$?
    
    if [ $EXIT_CODE -eq 124 ]; then
        error "❌ Workflow timeout after $TIMEOUT seconds"
        send_notification "FAILED" "Timeout after ${TIMEOUT}s"
    else
        error "❌ Workflow failed with exit code: $EXIT_CODE"
        send_notification "FAILED" "Exit code: $EXIT_CODE"
    fi
    
    # Show last 10 lines of log
    log "Last 10 lines of execution log:"
    tail -10 "$LOG_FILE" | while read -r line; do
        log "  $line"
    done
    
    exit $EXIT_CODE
fi
