"""
tool_generator.py — Auto-generate @tool Python files from registered service schemas

Flow:
  1. Fetch OpenAPI spec from service endpoint
  2. Store in api_registry DuckDB (load_schema)
  3. Group operations by tag
  4. Render one Python file per tool group using the embedded template
  5. Write to tool_generation.output_dir

Generated tools use service_call() for authentication and schema-aware trimming.

Reference: dev_docs/16. SERVICE_REGISTRY_DESIGN.md §Phase2
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from textwrap import dedent
from typing import Any

from olav.core.api_registry import load_schema, list_apis, is_loaded
from olav.platform.services.registry import ServiceConfig, ServiceRegistry, ToolGroupConfig

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Tool file template
# ---------------------------------------------------------------------------

_TOOL_TEMPLATE = '''\
"""Auto-generated tool: {display_name} — {group_description}

Generated by olav.platform.services.tool_generator
Service: {service_name}
Tag group: {tag}
DO NOT EDIT MANUALLY — re-run `olav service register {service_name}` to update.
"""

from __future__ import annotations

from olav.platform.services.client import service_call as _call


{tool_functions}
'''

_FUNCTION_TEMPLATE = '''\
def {func_name}({params}) -> dict:
    """{summary}

    Service: {service_name}  |  {method} {path}
    """
    return _call(
        "{service_name}",
        "{method}",
        f"{path_template}",{body_arg}{response_def_arg}
    )
'''


# ---------------------------------------------------------------------------
# Name helpers
# ---------------------------------------------------------------------------

def _to_func_name(prefix: str, method: str, path: str) -> str:
    """Build a Python function name from a tool prefix + HTTP method + path.

    Example: ("clab", "GET", "/api/v1/labs/{name}") → "clab_get_labs_by_name"
    """
    # Strip leading /api/v1/ prefixes
    slug = re.sub(r"^(/api/v\d+)?/", "", path).strip("/")
    # Replace path params {name} → by_name
    slug = re.sub(r"\{(\w+)\}", lambda m: f"by_{m.group(1)}", slug)
    # Slugify
    slug = re.sub(r"[^a-z0-9]+", "_", slug.lower()).strip("_")
    return f"{prefix}_{method.lower()}_{slug}" if slug else f"{prefix}_{method.lower()}"


def _path_to_fstring(path: str) -> str:
    """Convert OpenAPI path /labs/{name} to Python f-string body /labs/{name}."""
    return path  # Python f-string syntax matches OpenAPI {} style


def _build_function(
    svc_name: str,
    prefix: str,
    method: str,
    path: str,
    summary: str | None,
    request_body_def: str | None,
    response_200_def: str | None,
) -> str:
    """Render a single tool function string."""
    func_name = _to_func_name(prefix, method, path)

    # Build parameter list
    # Path params → required positional; body → optional kwarg
    path_params = re.findall(r"\{(\w+)\}", path)
    param_parts = list(path_params)  # positional
    if request_body_def and method.upper() in ("POST", "PUT", "PATCH"):
        param_parts.append("body: dict | None = None")
    params = ", ".join(param_parts)

    # Body kwarg for service_call
    has_body = request_body_def and method.upper() in ("POST", "PUT", "PATCH")
    body_arg = "\n        body=body," if has_body else ""

    # response_def arg
    response_def_arg = f'\n        response_def="{response_200_def}",' if response_200_def else ""

    return _FUNCTION_TEMPLATE.format(
        func_name=func_name,
        params=params,
        summary=summary or f"{method} {path}",
        service_name=svc_name,
        method=method.upper(),
        path=path,
        path_template=_path_to_fstring(path),
        body_arg=body_arg,
        response_def_arg=response_def_arg,
    )


# ---------------------------------------------------------------------------
# Registration flow
# ---------------------------------------------------------------------------

def register_service(service_name: str, force: bool = False) -> dict[str, Any]:
    """Full registration flow for a service.

    1. Load OpenAPI schema into api_registry
    2. Generate tool files for each tag group
    3. Return registration summary

    Args:
        service_name: Key in services.yaml
        force:        Re-fetch schema even if already loaded

    Returns:
        {"service": name, "ops_loaded": int, "files_written": [str, ...]}
    """
    registry = ServiceRegistry.get_instance()
    svc = registry.get(service_name)

    if not svc.schema_url:
        raise ValueError(f"Service '{service_name}' has no schema_url configured")

    # Step 1: load schema into api_registry
    logger.info("Fetching schema for '%s' from %s", service_name, svc.schema_url)
    ops_count = load_schema(
        api_name=service_name,
        schema_url=svc.schema_url,
        base_url=svc.endpoint,
        force=force,
    )
    logger.info("Loaded %d operations for '%s'", ops_count, service_name)

    # Step 2: generate tool files
    files_written: list[str] = []
    for group in svc.tool_generation.groups:
        path = _generate_group_tool_file(svc, group)
        if path:
            files_written.append(path)

    return {
        "service": service_name,
        "ops_loaded": ops_count,
        "files_written": files_written,
    }


def _generate_group_tool_file(svc: ServiceConfig, group: ToolGroupConfig) -> str | None:
    """Generate a Python tool file for one tag group. Returns file path or None."""
    import duckdb
    from olav.core.api_registry import DEFAULT_DB

    tag = group.tag
    prefix = group.tool_prefix or svc.name

    # Query operations for this tag from api_registry
    try:
        with duckdb.connect(str(DEFAULT_DB), read_only=True) as con:
            rows = con.execute(
                """
                SELECT method, path, summary, request_body_def, response_200_def
                FROM api_registry.operations
                WHERE api_name = ? AND list_contains(tags, ?)
                ORDER BY path, method
                """,
                [svc.name, tag],
            ).fetchall()
    except Exception as e:
        logger.warning("Could not query operations for '%s' tag '%s': %s", svc.name, tag, e)
        return None

    if not rows:
        logger.warning("No operations found for '%s' tag '%s'", svc.name, tag)
        return None

    # Build function strings
    functions: list[str] = []
    for method, path, summary, req_def, resp_def in rows:
        fn = _build_function(svc.name, prefix, method, path, summary, req_def, resp_def)
        functions.append(fn)

    tool_code = _TOOL_TEMPLATE.format(
        display_name=svc.display_name,
        group_description=group.description or tag,
        service_name=svc.name,
        tag=tag,
        tool_functions="\n\n".join(functions),
    )

    # Write to output directory
    out_dir = Path(svc.tool_generation.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{svc.name}_{tag}.py"
    out_file.write_text(tool_code)

    logger.info("Generated %d tools → %s", len(functions), out_file)
    return str(out_file)
