#!/bin/bash
# Install OLAV Cron Jobs
# Auto-generated by OLAV - Network Operations AI Assistant
#
# Usage:
#   ./scripts/install_cron.sh          # Install cron jobs
#   ./scripts/install_cron.sh --list   # List current cron jobs
#   ./scripts/install_cron.sh --remove # Remove OLAV cron jobs

set -e
set -u

# ============================================================================
# Configuration
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ============================================================================
# Helper Functions
# ============================================================================

show_help() {
    cat <<EOF
Install OLAV Cron Jobs

Usage:
  $0 [OPTIONS]

Options:
  --help          Show this help message
  --list          List current cron jobs
  --remove        Remove OLAV cron jobs
  (no options)    Install/update cron jobs

Examples:
  $0              # Install cron jobs
  $0 --list       # View installed jobs
  $0 --remove     # Uninstall

Cron Jobs:
  1. Daily Inspection    - Every day at 06:00
  2. Weekly Backup       - Every Sunday at 02:00
  3. Log Cleanup         - Every day at 01:00 (keep 7 days)

EOF
}

list_cron() {
    echo "Current cron jobs:"
    echo "=================="
    crontab -l 2>/dev/null || echo "(No cron jobs installed)"
}

remove_cron() {
    echo "Removing OLAV cron jobs..."
    
    # Get current crontab
    CURRENT=$(crontab -l 2>/dev/null || true)
    
    # Remove OLAV lines
    NEW_CRON=$(echo "$CURRENT" | grep -v "OLAV" | grep -v "$PROJECT_ROOT" || true)
    
    if [ -z "$NEW_CRON" ]; then
        # No cron jobs left, remove crontab
        crontab -r 2>/dev/null || true
        echo "✅ All OLAV cron jobs removed (crontab cleared)"
    else
        # Install filtered crontab
        echo "$NEW_CRON" | crontab -
        echo "✅ OLAV cron jobs removed"
    fi
}

install_cron() {
    echo "Installing OLAV cron jobs..."
    echo "Project: $PROJECT_ROOT"
    
    # Check if daily_inspection.sh exists
    if [ ! -f "$PROJECT_ROOT/scripts/daily_inspection.sh" ]; then
        echo "❌ Error: scripts/daily_inspection.sh not found"
        exit 1
    fi
    
    # Make scripts executable
    chmod +x "$PROJECT_ROOT/scripts/daily_inspection.sh"
    
    # Get current crontab
    CURRENT=$(crontab -l 2>/dev/null || true)
    
    # Remove existing OLAV entries
    FILTERED=$(echo "$CURRENT" | grep -v "OLAV" | grep -v "$PROJECT_ROOT" || true)
    
    # Create new crontab
    NEW_CRON=$(cat <<EOF
$FILTERED

# ============================================================================
# OLAV Network Inspection Cron Jobs
# Installed: $(date)
# Project: $PROJECT_ROOT
# ============================================================================

OLAV_HOME=$PROJECT_ROOT
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin

# Daily Inspection (06:00)
# Performs comprehensive network health check
0 6 * * * \$OLAV_HOME/scripts/daily_inspection.sh >> \$OLAV_HOME/.olav/logs/cron.log 2>&1

# Weekly Backup (Sunday 02:00)
# Backs up OLAV configuration
0 2 * * 0 cd \$OLAV_HOME && /usr/bin/uv run olav admin backup >> \$OLAV_HOME/.olav/logs/backup.log 2>&1

# Log Cleanup (Daily 01:00)
# Removes inspection logs older than 7 days
0 1 * * * find \$OLAV_HOME/.olav/logs -name "inspection_*.log" -mtime +7 -delete

EOF
)
    
    # Install new crontab
    echo "$NEW_CRON" | crontab -
    
    echo ""
    echo "✅ Cron jobs installed successfully!"
    echo ""
    echo "Installed jobs:"
    echo "  1. Daily Inspection:  Every day at 06:00"
    echo "  2. Weekly Backup:     Every Sunday at 02:00"
    echo "  3. Log Cleanup:       Every day at 01:00"
    echo ""
    echo "Logs:"
    echo "  - Inspection: $PROJECT_ROOT/.olav/logs/inspection_YYYYMMDD.log"
    echo "  - Cron:       $PROJECT_ROOT/.olav/logs/cron.log"
    echo "  - Backup:     $PROJECT_ROOT/.olav/logs/backup.log"
    echo ""
    echo "To view installed jobs: crontab -l"
    echo "To edit jobs:           crontab -e"
    echo "To remove jobs:         ./scripts/install_cron.sh --remove"
    echo ""
    echo "Next Steps:"
    echo "  1. Test manually:     $PROJECT_ROOT/scripts/daily_inspection.sh"
    echo "  2. Wait for execution or adjust time: crontab -e"
    echo "  3. Monitor logs:      tail -f $PROJECT_ROOT/.olav/logs/cron.log"
}

# ============================================================================
# Main
# ============================================================================

case "${1:-install}" in
    --help|-h)
        show_help
        ;;
    --list|-l)
        list_cron
        ;;
    --remove|-r)
        remove_cron
        ;;
    install|*)
        install_cron
        ;;
esac
