"""SCHEMA_REFERENCE.md contract tests — R83 data-access model.

History: this file was born as OC-8 ("SCHEMA_REFERENCE.md must document
OpenConfig JSON path query patterns"). R82 rewrote the reference around
the four canonical sources and R83 replaced OpenConfig JSON-path
querying with per-command zero-ETL auto-views; the OC-8 assertions went
strict-xfail on 2026-06-12 and were re-specified against the R83 model
on 2026-06-13. Each test below maps one original OC-8 intent onto its
R83 equivalent (noted per test).

The tests read the TRACKED bundle copy (src/olav/data/workspace) so
they work on a fresh checkout without `olav init`; the workspace drift
gate (tests/governance/test_workspace_drift_gate.py) guarantees the
runtime copy is byte-identical.
"""

from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
_REF = _REPO / "src" / "olav" / "data" / "workspace" / "core" / "references" / "SCHEMA_REFERENCE.md"


def _content() -> str:
    return _REF.read_text(encoding="utf-8")


class TestSchemaReferenceAutoViewModel:
    """OC-8 intent: "document the data-access model for parsed device state."

    R83 re-spec: the model is the two-layer auto-view architecture, not
    OpenConfig JSON paths — the reference must document both layers.
    """

    def test_reference_documents_semantic_views_layer(self):
        """Layer 1: cross-vendor semantic views for BGP / OSPF / L2."""
        content = _content()
        for view in (
            "v_bgp_neighbors_auto",
            "v_ospf_neighbors_auto",
            "v_l2_links_auto",
        ):
            assert view in content, f"SCHEMA_REFERENCE.md must document {view}"

    def test_reference_documents_per_command_autoview_layer(self):
        """Layer 2: per-command zero-ETL views generated by /netops_init."""
        content = _content()
        assert "v_%_auto" in content, (
            "Must document the auto-view discovery pattern "
            "(information_schema.views ... LIKE 'v_%_auto')"
        )
        assert "unnest" in content.lower() or "zero-etl" in content.lower(), (
            "Must explain that auto-views are DuckDB-native unnest/zero-ETL views"
        )
        assert "DESCRIBE" in content, (
            "Must teach DESCRIBE <view> as the column-discovery step"
        )


class TestSchemaReferenceJsonFallback:
    """OC-8 intent: "include JSON path query examples."

    R83 re-spec: raw JSON access survives only as the documented
    fallback for commands without an auto-view yet — the reference must
    keep both the simple projection and the LATERAL per-row pattern.
    """

    def test_reference_documents_json_extraction(self):
        content = _content()
        assert "json_extract" in content.lower() or "->>" in content, (
            "Must document JSON extraction against parsed_outputs.parsed_data"
        )

    def test_reference_documents_lateral_fallback(self):
        """Per-row filtering needs the LATERAL json_each pattern."""
        content = _content()
        assert "json_each" in content, (
            "Must keep the LATERAL json_each fallback for commands "
            "without an auto-view"
        )
        assert "LATERAL" in content

    def test_reference_documents_raw_output_fallback(self):
        """Tier-3: raw_output_store when no parser ran at all."""
        content = _content()
        assert "raw_output_store" in content, (
            "Must document the raw_output_store fallback tier"
        )


class TestSchemaReferenceDomainMapping:
    """OC-8 intent: "document the protocol-domain mapping" (openconfig-bgp etc.).

    R83 re-spec: protocol domains map to canonical sources; the
    reference must name them AND fence off hallucinated alternatives.
    """

    def test_reference_lists_canonical_sources_for_protocol_data(self):
        content = _content()
        for src in (
            "topology_links",
            "v_l2_links_auto",
            "v_bgp_neighbors_auto",
            "v_ospf_neighbors_auto",
        ):
            assert src in content, f"Canonical source {src} missing from reference"
        assert "only valid sources" in content, (
            "Must state that the canonical sources are the ONLY valid ones "
            "for neighbor/topology data"
        )

    def test_reference_fences_off_hallucinated_view_names(self):
        """The anti-pattern block must warn that commonly-guessed names
        (v_topo_links_clean etc.) do not exist."""
        # normalize: the warning wraps across a line break in the doc
        flat = " ".join(_content().split())
        assert "don't exist" in flat or "do not exist" in flat, (
            "Must explicitly warn that guessed view names don't exist"
        )
        content = _content()
        assert "v_topo_links_clean" in content, (
            "The fence list must name v_topo_links_clean (the most common "
            "hallucinated topology view)"
        )


class TestSchemaReferenceSnapshotGuidance:
    """OC-8 intent: "snapshot examples must not teach cross-table filters."

    R83 re-spec: the same-table rule is stated once up front, and
    auto-views embed the latest-snapshot filter so examples don't need
    explicit snapshot predicates at all.
    """

    def test_reference_states_same_table_snapshot_rule(self):
        content = _content()
        assert "MAX(snapshot_id) FROM <same_table>" in content, (
            "Must state the same-table snapshot rule "
            "(snapshot_id = (SELECT MAX(snapshot_id) FROM <same_table>))"
        )

    def test_reference_states_autoview_builtin_snapshot_filter(self):
        content = _content()
        assert "auto-filters to the latest snapshot" in content, (
            "Must state that per-command auto-views embed the "
            "latest-snapshot filter"
        )

    def test_reference_does_not_use_parsed_outputs_snapshot_for_views(self):
        """Negative guard kept from OC-8: no example may filter a view by
        ANOTHER table's MAX(snapshot_id)."""
        content = _content()
        bad_v_interfaces = "FROM v_interfaces\nWHERE device_name = 'SW1'\n  AND (admin_status != 'up' OR line_status != 'up')\n  AND snapshot_id = (SELECT MAX(snapshot_id) FROM parsed_outputs);"
        bad_v_bgp = "FROM v_bgp_neighbors\nWHERE state = 'Established'\n  AND snapshot_id = (SELECT MAX(snapshot_id) FROM parsed_outputs);"
        bad_topology = "FROM topology_links\nWHERE snapshot_id = (SELECT MAX(snapshot_id) FROM parsed_outputs);"
        assert bad_v_interfaces not in content
        assert bad_v_bgp not in content
        assert bad_topology not in content


class TestSchemaReferenceObjectInventory:
    """OC-8 intent: "object kinds must match the live main-schema catalog."

    R83 re-spec: the R82 rewrite dropped the object-kind table; the
    durable invariant is that the reference names exactly the R83 data
    plane (tables + both view layers) and nothing retired.
    """

    def test_reference_names_all_data_plane_tables(self):
        content = _content()
        for table in (
            "netops.devices",
            "netops.parsed_outputs",
            "netops.raw_output_store",
            "netops.topology_links",
            "netops.commands",
        ):
            assert table in content, f"Data-plane table {table} missing"

    def test_reference_does_not_teach_retired_objects(self):
        """Pre-R83 objects must not appear as queryable sources.

        yang_leaves / mapping_rules / bare v_interfaces belonged to the
        OC-8-era schema; teaching them would send agents at objects that
        no longer exist. (Names inside the explicit anti-pattern fence
        are checked separately and allowed there only.)"""
        content = _content()
        for retired in ("yang_leaves", "mapping_rules", "openconfig"):
            assert retired.lower() not in content.lower(), (
                f"Retired object/concept {retired!r} must not reappear in "
                "SCHEMA_REFERENCE.md — the R83 model replaced it"
            )
