approval_status: approved
approval_timestamp: '2026-02-08T14:06:10.517056'
approved_by: admin
created_at: '2026-02-08T14:06:10.486134'
cron_expression: 0 3 * * *
description: null
duration_hours: null
execution_count: 0
expires_at: null
failure_count: 0
last_execution_at: null
last_execution_result: null
modified_at: '2026-02-08T14:06:10.526538'
name: null
notifications: {}
permission_tier: yellow
query: UPDATE device_configs SET backup=true
rejected_by: null
rejection_reason: null
requires_approval: true
status: created
task_id: 00ba7823-8eb
timeout_seconds: 300
