approval_status: null
approval_timestamp: null
approved_by: null
created_at: '2026-02-08T14:06:46.213954'
cron_expression: '*/1 * * * *'
description: null
duration_hours: 0.001
execution_count: 0
expires_at: '2026-02-08T14:06:49.813954'
failure_count: 0
last_execution_at: null
last_execution_result: null
modified_at: '2026-02-08T14:06:46.213954'
name: null
notifications: {}
permission_tier: green
query: SELECT * FROM devices
rejected_by: null
rejection_reason: null
requires_approval: false
status: created
task_id: 0149aac3-e90
timeout_seconds: 300
