approval_status: approved
approval_timestamp: '2026-02-08T14:04:01.688124'
approved_by: admin
created_at: '2026-02-08T14:04:01.661722'
cron_expression: 0 3 * * *
description: null
duration_hours: null
execution_count: 0
expires_at: null
failure_count: 0
last_execution_at: null
last_execution_result: null
modified_at: '2026-02-08T14:04:01.694319'
name: null
notifications: {}
permission_tier: yellow
query: UPDATE device_configs SET backup=true
rejected_by: null
rejection_reason: null
requires_approval: true
status: created
task_id: 6316586f-59c
timeout_seconds: 300
