approval_status: approved
approval_timestamp: '2026-02-08T14:06:46.923675'
approved_by: admin
created_at: '2026-02-08T14:06:46.900224'
cron_expression: 0 3 * * *
description: null
duration_hours: null
execution_count: 0
expires_at: null
failure_count: 0
last_execution_at: null
last_execution_result: null
modified_at: '2026-02-08T14:06:46.929570'
name: null
notifications: {}
permission_tier: yellow
query: UPDATE device_configs SET backup=true
rejected_by: null
rejection_reason: null
requires_approval: true
status: created
task_id: f72b9a25-219
timeout_seconds: 300
